### ISSUE TITLE
Bash completion 

### ISSUE THREAD

**Issue by cyberkm** [fastbuild/fastbuild#100]
Hi, i wrote a small bash completion script for fbuild (including flags and targets completion)
its not exactly belongs to the code repository, whats the preferred way to distribute it?

**Comment by ffulin** [comment]
Hello

In the earlier days of FASTBuild, before it could compile itself on Linux and OSX, I used to maintain a "bootstrap" shell script.  I stopped maintaining it once FASTBuild was mature enough that it could build itself, mainly to avoid the hassle of keeping it updated.  The idea being that (as on Windows) you can just use the previous version.

However, on Linux (and less so OSX), this restricts the possible distros that it's available on (since the current release wont' work on older kernels), so I have been considering resurrecting this script.

I was thinking of a script that:
 - builds one config only (the debug config, which you could then use to build the proper Release config)
 - clearly prints out that it's just for bootstrapping (and that the exe result should not be the final one you use)

I think this would reduce the maintenance overhead.  We could use your script, or dust off the old one (or some combination of the two).

What do you think about this approach?

**Comment by cyberkm** [comment]
I don't think that it worth to maintain it at this point. Do you have
statiatics how many people tried to run it on older kernels and failed?
Maybe this bootstrap script is a solution for problem that doesn't really
exists.

Anyway, my script is something else. It's is argument completion for the
fastbuild when user is pressing tab. All options and defined build are
easily accessible this way.

**Comment by ffulin** [comment]
Ah... I'm sorry, I totally misunderstood.  Re-reading your original message though it's very clear what you meant though :)

In the source there is an "[Integration](https://github.com/fastbuild/fastbuild/tree/master/Code/Tools/FBuild/Integration)" directory which currently includes some files for syntax highlighying in IDEs (like Visual Studio and Notepad++).  It seems like this might be an appropriate place to host this.

**Comment by ffulin** [comment]
Is there any more info you'd like on this subject?  If not, I'd like to close this issue.

**Comment by cyberkm** [comment]
Sure, you can close it :)
