### ISSUE TITLE
Run executable in PATH from Exec()

### ISSUE THREAD

**Issue by eclazi** [fastbuild/fastbuild#1019]
I'm trying to run an executable contained in PATH in an Exec() function.

.ExecExecutable = "powershell.exe"

However it fails because it looks like ExecExecutable is always relative to the working dir, if not absolute. Is there a way to include PATH in search directories?

Or is there a better way to run powershell scripts as a build step?

**Comment by ffulin** [comment]
The easiest way to run powershell script is by using the full path as follows:
```
Exec( 'task' )
{
    .ExecExecutable         = 'c:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
    .ExecArguments          = '-Command Write-Host "hello"'
```

(Note that despite the "v1.0" in the path, this is actually whatever version you may have installed (in my case v5.1))

If you are concerned about portability between machines with non-standard Windows installation locations, you can leverage the WINDIR environment variable:

```
Exec( 'task' )
{
    #import WINDIR
    .ExecExecutable         = '$WINDIR$\System32\WindowsPowerShell\v1.0\powershell.exe'
```

If your task outputs an artifact you'll want to tell FASTBuild about that using (so that it knows when to rebuild it) as follows:
```
    .ExecOutput             = 'out/output.file'
```

If your task only generates output to stdout (does not create an output file), you can capture that as the output to satisfy FASTBuild's need for an output:
```
    .ExecOutput             = 'out/output.txt'
    .ExecUseStdOutAsOutput  = true
```

If you would also like the output to be printed every time the task is run (instead of the default of only printing details on failure to reduce spam), you can also specify this:
```
    .ExecAlwaysShowOutput   = true
```

**Comment by eclazi** [comment]
Thanks!

**Comment by rustydwemer** [comment]
Suggestion 1:  Can you add the fact that fbuild ignores Path system variable to the docs
Suggestion 2: Would you consider adding a property to Exec function that enables lookup in paths defined inside the Path system variable? 'cause it's really inconvenient to copy-paste paths to some basic stuff like cmd.exe or powershell.exe
