### ISSUE TITLE
mac: "File missing despite success" after creating directory

### ISSUE THREAD

**Issue by nedres** [fastbuild/fastbuild#1024]
[PreBuildDep_example.zip](https://github.com/fastbuild/fastbuild/files/14449452/PreBuildDep_example.zip)

Minimal repro project included: failure in PreBuildDependencies on mac platform.

The project compiles a hello-world program with an Exec step as dependency.

if "MAKE_FOLDER" is defined, the script uses `mkdir` to make a folder.  The step succeeds, but the build fails with `File missing despite success`.

if "MAKE_FOLDER" is not defined, the script uses `touch` to make a file.  The build succeeds.

**Comment by ffulin** [comment]
[Exec](https://fastbuild.org/docs/functions/exec.html) requires the creation of an output file to succeed:
```
.ExecOutput             ; Output file generated by executable
```
Given the sample you provided, it's expected that it will fail in the way you are seeing. (Side note: it looks as though this will incorrectly not fail on Windows due to bug in the FileExists check)

As your example appears to just be a test, it's hard to say what the best solve is, as a real-world use case would have different ideal solutions depending on the desired result. For example if the directory is intended to contain other build outputs, it will normally be created automatically, so manual creation isn't usually needed. If an empty directory is the only output, there are ways to leverage Exec to this effect.

Here are some possible solutions:

**Use ExecUseStdOutAsOutput and a tmp file**
If you need to create an empty folder only, or can't rely on other steps auto-creating it for some reason, you can leverage Exec() as you attempted with some slight changes:
```
{
    .ExecExecutable        = '/bin/mkdir'
    .ExecArguments         = '-p ./example'
    .ExecOutput            = '/tmp/example.log' // Log file somewhere in your intermediate build location
    .ExecUseStdOutAsOutput = true               // Capture stdout and write to ExecOutput
}
```

**Check if creation is needed at all**
Things like Exec, ObjectList and others that create output files generally automatically create the directory structure necessary for those output files to exist, so manual creation is usually not needed. Perhaps the Exec step you have isn't needed at all?

**Add a CreateDir function**
An explicit CreateDir function could be added to FASTBuild to allow for the creation of empty directories.

**Comment by ffulin** [comment]
The behavior of FileExists on Windows has now been fixed so that it matches OSX/Linux: https://github.com/fastbuild/fastbuild/commit/df7d7215000a53a1083b0d2c46d3b22b83e7b563

**Comment by nedres** [comment]
Great, thanks for explaining.  Closing this issue as not a bug.
