### ISSUE TITLE
ObjectList not rebuilt when PreBuildDependencies changes

### ISSUE THREAD

**Issue by eclazi** [fastbuild/fastbuild#1035]
Maybe I am misunderstanding but I am trying to have an ObjectList be rebuilt when a PreBuildDependencies is run.

Currently it looks like that if the outputs of a pre built dependency changes, it doesn't mark the object list as stale. Is that expected?

Roughly what I am trying to do

```
; Builds compiler.exe from python files
Exec('build-compiler')
{
   .ExecExecutable='compiler/build.cmd'
   .ExecInputPath='compiler'
   .ExecWorkingDir='compiler'
   .ExecInputPattern='*.py'
   .ExecOutput='compiler/compiler.exe'
}

Compiler("compiler")
{
   .Executable='compiler/compiler.exe'
   .CompilerFamily="custom"
}

ObjectList('things-to-compile')
{
  .Compiler='compiler'
  .CompilerInputPattern='*.proto'
  .PreBuildDependencies='build-compiler'
}
```

So when an input to 'build-compiler' changes, 'things-to-compile' is rebuilt. Right now it seems just the Exec is re-run

**Comment by ffulin** [comment]
PreBuildDependencies are intended for the special case where you want to schedule one step before another but not depend directly on it, but rather some side effect it has. A good example is code gen - you want to run code gen if the code generator changes, but you don't want to recompile the resulting code unless the output of codegen changed. PreBuildDependencias allow you to order operations so downstream ObjectLists directory listings are deferred.

In your example, it seems you just have a straight dependency from ObjectList -> Compiler -> Exec to make the compiler which should not require adding PreBuildDependencies. Things used in Input and Output params should have dependencies automatically linked.

I do note though that your examples are incomplete (missing command lines etc for example) so it's hard to say if there are other issues.

One feature that may be helpful in understanding what's going in is the [-why](https://fastbuild.org/docs/options.html#why) arg. That prints some dependency details and shows why things rebuild.

It is of course possible that there can be a bug, but at a glance it seems your example should work (assuming missing params are set sensibly).

This test seems to cover your use case, albeit using Executable to build a c++ "compiler" instead of Exec, but it *should* work the same way:
https://github.com/fastbuild/fastbuild/blob/main/Code/Tools/FBuild/FBuildTest/Data/TestCompiler/compile.bff

Let me know if you think there is a bug or if I can help you get it working.

**Comment by eclazi** [comment]
I think the quirk with my case is my compiler is not written in c / c++ but python, so Compiler / ObjectList doesn't quite work and I have to use Exec to call the python build step correctly.

**Comment by eclazi** [comment]
My "compiler" is a python application consisting of a few python files (that all need to be tracked as dependencies), converted to an exe using the command line `pyinstaller main.py`

This "compiler" then performs some code generation, generating c++ code.

**Comment by ffulin** [comment]
It should be possible to chain an exe you've created into Compile, even if that's made by an Exec stuff and generated from python. Additional PreBuildDependencies should not be needed.

I noticed you closed this issue. If you resolved them problem, it might help other to mention how.
If you didn't resolve it and want more help, let me know.
