### ISSUE TITLE
How to make full use of the build server

### ISSUE THREAD

**Issue by Hibeginner** [fastbuild/fastbuild#1038]
Environment:
VS2019
FastBuild v1.11

I have a FBuildWorker.exe running on a Windows Server 2022 Datacenter which has 512 logic cores.
I start the worker by command "FBuildWorkder.exe -cpus=502 -mode=dedicated".
![20240511-175503](https://github.com/fastbuild/fastbuild/assets/11421227/893c1779-5ba3-464e-bb4c-dbddad3efdf3)
In another win10 machine, I distribute the build tasks(UE4.27).

My question is, I can only use 50-60 cores in the Worker machine while the other cores are "idle". How can i improve the usage in the Worker machine?

**Comment by Hibeginner** [comment]
![screenshot-20240511-183545](https://github.com/fastbuild/fastbuild/assets/11421227/b7201cda-acd6-426f-9f60-e72dfe44c82c)
65 cores in total, 10 is local, 55 is remote Worker.

**Comment by ffulin** [comment]
It's hard to know for sure from the info provided, but my best guess is either one of the following:

**a) the local host is not fast enough to feed more than the 50-60 cores you are seeing.**
If that's the case, the bottleneck could be CPU, IO or Network, with CPU being the most likely.
Ideas to try:
* An update to a most recent version of FASTBuild (v1.13) might see some improvements as there have been several optimizations in more recent versions.
* Machine wide profiling of the local host might uncover bottlenecks specific to your situation, and perhaps uncover optimization opportunities for FASTBuild.

**b) Problems addressing the CPU architecture**
The FBuildWorker should be able to take advantage of many CPU cores. Systems with very large core counts (usually over 64 cores) require enumerating the NUMA configuration of the host and to the best of my knowledge the FBuildWorker does this and should utilize large core systems absent of other bottlenecks.
Ideas to try:
* If you use FASTBuild's built in -profile command line and examine the chrome tracing compatible fbuild_profile.json file it generates, you'll get a more accurate representation of the build which may provide additional insights into how cores are actually being used since it will actually show you which remote cores are being utilized (the Dashboard app you are using provides only a pseudo-utilization view and has some inaccuracies).

**c) FBuildWorker bottlenecks**
With as many cores as you have, it's entirely possible there are bottlenecks in the worker not seen on systems with fewer cores. Profiling of the worker might uncover bottlenecks which could be optimized (such as lock contention or other issues)

**Comment by Hibeginner** [comment]
Thanks for your advice.

> It's hard to know for sure from the info provided, but my best guess is one of the following:
> 
> **a) the local host is not fast enough to feed more than the 50-60 cores you are seeing.** If that's the case, the bottleneck could be CPU, IO or Network, with CPU being the most likely. Ideas to try:
> 
> * An update to a most recent version of FASTBuild (v1.13) might see some improvements as there have been several optimizations in more recent versions.
> * Machine wide profiling of the local host might uncover bottlenecks specific to your situation, and perhaps uncover optimization opportunities for FASTBuild.
> 
> **b) Problems addressing the CPU architecture** The FBuildWorker should be able to take advantage of many CPU cores. Systems with very large core counts (usually over 64 cores) require enumerating the NUMA configuration of the host and to the best of my knowledge the FBuildWorker does this and should utilize large core systems absent of other bottlenecks. Ideas to try:
> 
> * If you use FASTBuild's built in -profile command line and examine the chrome tracing compatible fbuild_profile.json file it generates, you'll get a more accurate representation of the build which may provide additional insights into how cores are actually being used since it will actually show you which remote cores are being utilized (the Dashboard app you are using provides only a pseudo-utilization view and has some inaccuracies).
> 
> **c) FBuildWorker bottlenecks** With as many cores as you have, it's entirely possible there are bottlenecks in the worker not seen on systems with fewer cores. Profiling of the worker might uncover bottlenecks which could be optimized (such as lock contention or other issues)
