### ISSUE TITLE
Show remaining tasks in the status line, and document it

### ISSUE THREAD

**Issue by miv-ableton** [fastbuild/fastbuild#1051]
Fastbuild's status line is mysterious to me, and it doesn't tell me what I want to know, which is how much longer (in steps) until my build is done.

```
97.7% [****************---] 12m 31s (8/69)
```

The `(8/69)` part suggests that eight steps/tasks are running, and 69 are left to go. However, the number 69 can suddenly increase by hundreds. I never know how much work is left.

I propose putting the number of completed steps and the total number of steps in the build at the end of the status line like so:

```
97.7% [****************---] 12m 31s (8/69) [441/1842]
```

Finally, it would be nice if the Fastbuild website documented what this line is. I don't understand what the number `69` is telling me. If the Fastbuild website is on GitHub, please let me know and I'll try to make a PR with a documentation update of what I know.

Thank you for making such great and useful software.

**Comment by ffulin** [comment]
Hello. Thanks for your thoughts and questions.

**>  it would be nice if the Fastbuild website documented what this line is**

I agree. There isn't an obvious place for this in the existing documentation, so in lieu of that, I'll at least detail it here so it's detailed *somewhere*.

**> Fastbuild's status line is mysterious to me, and it doesn't tell me what I want to know, which is how much longer (in steps) until my build is done.**

Progress is hard, as evidenced by almost every progress bar ever made :) 

For FASTBuild, the challenge comes from:
a) imperfect knowledge of what work remains, as work is discovered as the build is performed
b) wildy variable build timings between items
c) wildly variable timings between builds as what needs building differs based on what has changed

The only way to have an entirely correct progress indicator is to perform the build, at which point the progress is no longer needed. So the progress as it is:
a) provides visibility into what is known at any given point
b) a percentage estimate based on historical timings recorded from previous builds traversing the graph

The line:
```
97.7% [****************---] 12m 31s (8/69)
```
Indicates that, at the time it was displayed:
* there were 69 tasks that have been determined so far as needing to be built
* 8 tasks are currently being built (this usually matched the number of local CPU cores)

It's worth noting that in distributed compilation, you would see something more complex, like this:
```
97.7% [****************---] 12m 31s (8/29) + (30/40)
```
which indicates:
* there are 29 tasks that need doing that can only be done locally
* 8 CPU cores locally are processing tasks
* there are 40 tasks that can be done remotely or locally
* there are 30 tasks that are being performed by remote cores, or potentially local cores if there are no local tasks

**> However, the number 69 can suddenly increase by hundreds. I never know how much work is left.**
The number increases as FASTBuild discovers work.
One case where tasks are discovered is after doing a directory listing to find cpp files which then need compiling into objects. It's not desirable to front load these directory listings because that would make builds slower, but more importantly it's not possible in many cases because tasks can depend on other tasks. If for example you have code generation, it's not possible to know how many things will need to be compiled until after the code is generated. That code generator may itself be an executable that needs to be compiled. Arbitrary dependency graphs can exist.

**>I propose putting the number of completed steps and the total number of steps in the build at the end of the status line**
I don't think this would provide any additional insight, other than at the end of the build showing a total count of jobs done.
In your example, (X/Y) [Z/W], just as Y can increase in the middle of the build, W would similarly increase.

**Comment by miv-ableton** [comment]
Thank you for explaining the status line, and the context of what it displays.

> One case where tasks are discovered is after doing a directory listing to find cpp files which then need compiling into objects. It's not desirable to front load these directory listings because that would make builds slower, but more importantly it's not possible in many cases because tasks can depend on other tasks.

Ah! I didn't know this. My company generates Fastbuild project files, because we also need to support other build systems. As part of that generation, we do the directory scanning and know in advance how many cpp files will be processed. With this system it's possible to know the number of steps remaining from the first go, but I see that this is just something local to us.

Makes sense. My questions have been answered.

**Comment by ffulin** [comment]
It's possible that in some build setups the number of tasks would exactly match what is defined in the config, but even for trivial C++ projects the header files are discovered in this way during a build (as the cpp files are processed), so even then the task counts can increase during the build.

For now I'll close this task as completed. I'm happy to answer any followup questions. Additionally, if you see any other behavior that might seem suspect, don't hesitate to mention it.
