### ISSUE TITLE
Enumerating files in a directory

### ISSUE THREAD

**Issue by legends2k** [fastbuild/fastbuild#1060]
`Exec` is useful when there's a many (inputs) to one (output) mapping.  However, there're instances where we need `Exec` in 1:1 mapping e.g. shader compilation.  Every shader I've generates a corresponding C++ header.  For this I manually list all the shaders and do some array shenanigans with FBuild

```
.ShaderSources = [
  .Names = {
    'skinned',
    'blur',
    'noise',
  }

  .Profiles = {
    'vs_3_0',
    'ps_3_0',
    'cs_3_0',
  }
]

.ShaderTargets = [
  .Targets = { }
]

{
  Using (.ShaderSources)

  ForEach (.Name in .Names, .Profile in .Profiles) {
    Using (.ConfigFxc)

    Exec ('fxc-$Name$') {
      .ExecInput     = 'Shaders/$Name$.hlsl'
      .ExecOutput    = '$ShaderHeadersDir$/$Name$.h'
      .ExecArguments = ' /T $Profile$'
                     + ' /Vn "g_$Name$"'
                     + ' /Fh "%2"'
                     + ' "%1"'
    }

    .ThisTarget = [
      .Targets = { 'fxc-$Name$' }
    ]
    ^ShaderTargets + .ThisTarget
  }
}

Alias ('ShaderHeaders') {
  Using (.ShaderTargets)
}
```

It works but it isn't quite elegant.  Two questions:

1. Can the above be improved with what FBuild already gives?
2. [Long Term] Would it be good to provide a `ForEach` like construct to enumerate files in a directory?
    - It'd rid the developers from needing to add a line in every array for every shader authored

If you want to reject (2) I totally understand from a design point of view.  The lesser the surface area of a tool/API the better.  In that sense you run a tight ship (reviewing your replies to other issues/questions) and I admire it.  Great tool, btw, thank you!

**Comment by Dandielo** [comment]
You could make use of `Compiler` and `ObjectList` functions to achieve the results.

In the end FastBuild allows to define custom compilers, which are in the end just tools that take one input and produce one output. This can be used to run any kind of simple task.
And object lists are just glorified `ForEach` loops working in the inputs you passed to them using the specific `Complier`.

**Comment by ffulin** [comment]
As @Dandielo says, you can utilize a custom Compiler used with an ObjectList to invoke an arbitrary executable from a directly listing when you want it invoked once per file. For cases where you want an executable to be invoked once with the entire list, you can use Exec.

It would not be possible to iterate directory listings inside the bff parsing, because the bff files are only parsed when they change and only to define the build rules. i.e. it is not a script that is executed during the build.

I think @Dandielo answered your question, so I'm going to close this issue, but let me know if I can provide any more info.

**Comment by ffulin** [comment]
As @Dandielo says, you can utilize a custom Compiler used with an ObjectList to invoke an arbitrary executable from a directly listing when you want it invoked once per file. For cases where you want an executable to be invoked once with the entire list, you can use Exec.

It would not be possible to iterate directory listings inside the bff parsing, because the bff files are only parsed when they change and only to define the build rules. i.e. it is not a script that is executed during the build.

I think @Dandielo answered your question, so I'm going to close this issue, but let me know if I can provide any more info.
