### ISSUE TITLE
.lib Node built with lib.exe mistakenly being detected as Exe node instead of Library node

### ISSUE THREAD

**Issue by missmah** [fastbuild/fastbuild#122]
We're working from the FastBuild for UE4 wiki (https://github.com/fastbuild/fastbuild/wiki/fastbuild-for-Unreal-Engine-4), which we've modified a bit, but are still struggling to make work properly. We're with a branch of UE4 4.12.5.

We're getting this error:

```
29>  BFF file 'D:\dev\UE4\UnrealEngine\Engine\Intermediate\Build\fbuild.bff' has changed (reparsing will occur).
29>  D:\dev\UE4\UnrealEngine\Engine\Intermediate\Build\fbuild.bff(23,1): FASTBuild Error #1005 - DLL() - Unsupported node type in 'Libraries'. (Node: 'D:\dev\UE4\UnrealEngine\Engine\Intermediate\Build\Win64\UE4Editor\Development\UE4Editor-UnrealEd.lib', Type: 'Exe')
29>  DLL('DLL-2')
```

And here's the related excerpt from the fbuild.bff file:

```
DLL('DLL-1')
{
    .Linker                 = '$VSBasePath$/bin/amd64/lib.exe' 
    .LinkerOutput         =  'D:\dev\UE4\UnrealEngine\Engine\Intermediate\Build\Win64\UE4Editor\Development\UE4Editor-UnrealEd.lib' 
    .Libraries         = 'D:\dev\UE4\UnrealEngine\Engine\Intermediate\Build\Win64\UE4Editor\Development\UE4Editor-UnrealEd.lib.response' 
    .LinkerOptions       = ' /NOLOGO /errorReport:prompt /MACHINE:x64 /SUBSYSTEM:WINDOWS /DEF /NAME:"UE4Editor-UnrealEd.dll" /LIBPATH:"ThirdParty/Ogg/libogg-1.2.2/lib/Win64/VS2015" /LIBPATH:"ThirdParty/Vorbis/libvorbis-1.3.2/Lib/win64/VS2015/" /LIBPATH:"ThirdParty/Vorbis/libvorbis-1.3.2/Lib/win64/VS2015/" /LIBPATH:"ThirdParty/Windows/DirectX/Lib/x64" /LIBPATH:"ThirdParty/HACD/HACD_1.0/lib/Win64/VS2015/" /LIBPATH:"ThirdParty/VHACD/lib/Win64/VS2015/" /LIBPATH:"ThirdParty/FBX/2016.1.1/lib/vs2015/x64/release/" /LIBPATH:"ThirdParty/FreeType2/FreeType2-2.6/Lib/Win64/VS2015" /LIBPATH:"ThirdParty/PhysX/PhysX-3.3/lib/Win64/VS2015" /LIBPATH:"ThirdParty/PhysX/APEX-1.3/lib/Win64/VS2015" /LIBPATH:"../Binaries/ThirdParty/libsndfile/Win64" /NODEFAULTLIB:"LIBCMT" /NODEFAULTLIB:"LIBCPMT" /NODEFAULTLIB:"LIBCMTD" /NODEFAULTLIB:"LIBCPMTD" /NODEFAULTLIB:"MSVCRTD" /NODEFAULTLIB:"MSVCPRTD" /NODEFAULTLIB:"LIBC" /NODEFAULTLIB:"LIBCP" /NODEFAULTLIB:"LIBCD" /NODEFAULTLIB:"LIBCPD" @"%1" /OUT:"%2"'
}
DLL('DLL-2')
{
    .Linker                 = '$VSBasePath$/bin/amd64/link.exe' 
    .LinkerOutput         =  'D:\dev\UE4\UnrealEngine\Engine\Binaries\Win64\UE4Editor-Engine.dll' 
    .Libraries         = { 'DLL-1' } 
    .LinkerOptions       = ' /MANIFEST:NO /NOLOGO /DEBUG /errorReport:prompt /MACHINE:x64 /SUBSYSTEM:WINDOWS /FIXED:No /NXCOMPAT /STACK:5000000 /DELAY:UNLOAD /DLL /PDBALTPATH:%_PDB% /OPT:NOREF /OPT:NOICF /INCREMENTAL:NO /ignore:4199 /ignore:4099 /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"PhysX3PROFILE_x64.dll" /DELAYLOAD:"PhysX3CookingPROFILE_x64.dll" /DELAYLOAD:"PhysX3CommonPROFILE_x64.dll" /DELAYLOAD:"nvToolsExt64_1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"APEXFrameworkPROFILE_x64.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"libogg_64.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"libvorbis_64.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"libvorbisfile_64.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /DELAYLOAD:"vulkan-1.dll" /LIBPATH:"ThirdParty/PhysX/PhysX-3.3/lib/Win64/VS2015" /LIBPATH:"ThirdParty/PhysX/APEX-1.3/lib/Win64/VS2015" /LIBPATH:"D:\dev\UE4\UnrealEngine\Engine\Source\ThirdParty\Box2D\Box2D_v2.3.1\build\vs2015\bin\x64\Release" /LIBPATH:"ThirdParty/Ogg/libogg-1.2.2/lib/Win64/VS2015" /LIBPATH:"ThirdParty/Vorbis/libvorbis-1.3.2/Lib/win64/VS2015/" /LIBPATH:"ThirdParty/Vorbis/libvorbis-1.3.2/Lib/win64/VS2015/" /LIBPATH:"ThirdParty/libOpus/opus-1.1/win32/VS2012/x64/Release/" /LIBPATH:"ThirdParty/DirectShow/DirectShow-1.0.0/Lib/Win64/vs2015/" /NODEFAULTLIB:"LIBCMT" /NODEFAULTLIB:"LIBCPMT" /NODEFAULTLIB:"LIBCMTD" /NODEFAULTLIB:"LIBCPMTD" /NODEFAULTLIB:"MSVCRTD" /NODEFAULTLIB:"MSVCPRTD" /NODEFAULTLIB:"LIBC" /NODEFAULTLIB:"LIBCP" /NODEFAULTLIB:"LIBCD" /NODEFAULTLIB:"LIBCPD" @"D:\dev\UE4\UnrealEngine\Engine\Intermediate\Build\Win64\UE4Editor\Development\UE4Editor-Engine.dll.response" /OUT:"%2" /IMPLIB:"D:\dev\UE4\UnrealEngine\Engine\Intermediate\Build\Win64\UE4Editor\Development\UE4Editor-Engine.lib" /PDB:"D:\dev\UE4\UnrealEngine\Engine\Binaries\Win64\UE4Editor-Engine.pdb" /ignore:4078 %1'
}
```

Is there a better way to go about this? It seems like a DLL node should be able to use a .lib/Library as a dependency. Unfortunately, to make DLL('DLL-1') into a proper Library Node (e.g. Library('LIB-1')) looks like it would expect a compiler, and to actually compile the object files in the same FastBuild step as executing the librarian...

Also, it seems to only not like .lib files within the DLL Node construct because it uses lib.exe instead of link.exe + /DLL... It almost seems like it should work if not for whatever code is doing that heuristic/regex check?

**Comment by kylawl** [comment]
Fast build annoyingly relies on output file extensions rather than simply respecting the wishes of the user. In general, it's parsing of command lines and and other "heuristic" behavior is the weakest part because it leads to confusion.

It's a great build system but it would be amazing if it was more general and only did what you tell it.

**Comment by ffulin** [comment]
> Fast build annoyingly relies on output file extensions

@kylawl FASTBuild tries to rely on the contents of the command line as minimally as possible, but to realize some of the optimizations, it has to have an understanding of what's being built.

For example, FASTBuild needs to know a DLL is specifically a DLL so that it can avoid re-linking downstream DLLs and Executables if the exported functions don't change.  This is a major optimization over MSBuild that I've seen cut minutes of build times when iterating core libraries in dll heavy projects. If FASTBuild was completely output agnostic, this optimization would not be possible.

This sort of optimization is a delicate balance. and despite trying to make it as minimally dependent on the cmd line as possible, it's entirely possible that it's unnecessarily restrictive in some cases.  If you've been frustrated by something that you think is unnecessarily restrictive, perhaps it can be improved?

> Fast build annoyingly relies on output file extensions
Do you have an example of this?  In the case we're talking about here it doesn't seem to me that this is a factor at all.  You can build a dll called thing.stuff if you want, but it has to be a DLL.  You should also name the import lib whatever you want (/IMPORTLIB:) but if you omit the name, it will expect the default name as generated by the MSVC linker.
Is there some other case you've seen a problem where FASTBuild does rely on file extension in an unsafe or restrictive way?  Perhaps that's a bug worthy of a new issue?

**Comment by ffulin** [comment]
It seems the Unreal script (authored by cjsu) is making some bad assumptions about DLL() and how it functions (either due to lack of docs on my part, or perhaps some missing functionality).  It seems like it needs to be changed to use Library() for static libraries.

I've raised an issue on cjsu's github to see if we can get to the bottom of this: https://github.com/cjsu/fastbuild-ue4/issues/1

**Comment by ClxS** [comment]
Hi @missmah, I mentioned a workaround here (requires a small change to FBuild): https://github.com/cjsu/fastbuild-ue4/commit/37ccda5a5a0e3c22d71528e637ef43de32713c3e#commitcomment-15908076

That may be a temporary solution, the real issue is my misuse of DLL nodes in FBuild and not FBuild itself.

**Comment by missmah** [comment]
Thanks for the help @ffulin and @ClxS! For now, using @ClxS's modification for EXE nodes works well, though an updated version which does the right thing will be great!

One odd thing is that for single .cpp file changes, FastBuild is slower than UE4+VS. Even when skipping the UE4 build steps and passing the .bff file directly to FastBuild, it still takes considerably longer to build the .obj file. Linking seems equally fast, though.

In fact, in general, it seems like FastBuild builds objs considerably slower than the native approach, which is puzzling because the compiler toolchain is the same. I wonder whether it's some compiler options, but I haven't narrowed it down to anything specific yet.

Overall, for a full build, I'm seeing equal build times with FastBuild distribution and with UBT+VC14 native - I believe that if the object file build times weren't slower for FastBuild, it would be considerably faster than the native solution (especially with more nodes and caching). Does anyone have any thoughts here?

Thanks again!

**Comment by ffulin** [comment]
> In fact, in general, it seems like FastBuild builds objs considerably slower than the native approach,

This is strange.  Certainly compiling with the same settings should yield at least the same performance. One thing I did notice in the UE4 script's documentation:
```C++
bUsePCHFiles = false; //temporary until compilation issue fixed
```
If this is indeed disabling the use of precompiled headers, that would likely have a very large negative impact on compile times.

**Comment by ClxS** [comment]
Ah yes, PCH support is still not enabled in the version on GitHub. I have it working locally now so I'll include support for them in the version that adds proper Library usage. (Issue here: https://github.com/ClxS/FASTBuild-UE4/issues/4). 
If I remember correctly, enabling PCHs reduced our full rebuild time from 8 minutes to 5 minutes, but without FASTBuild/IncrediBuild, we had 45 minute build times.

I don't think that @missmah 's issue would be due to that though since I'm assuming she kept that option disabled for the non-fbuild test. I assume the slowness is on the first pass where the object gets built, could this be due to preprocessing and compiling from the preprocessed source being plain slower than compiling directly from cpp, at least in MSVC?

**Comment by missmah** [comment]
Actually, I have PCHs enabled for both FastBuild and non-FastBuild tests. UE4 doesn't build properly without PCHs (with or without FastBuild, and it was just too much work to get it to build properly, so we tried switching FastBuild to PCHs and that's what we're using :))

**Comment by missmah** [comment]
Currently, we completely disable FastBuild for single file rebuilds due to the slowness - we aren't using the cache yet but it is enabled, so I should also try disabling caching and distribution for single-file builds, just to see if that fixes it as you say, @ClxS :+1:

**Comment by missmah** [comment]
So, making the C# script check the number of actions and disable distribution and caching below a certain threshold seems to have fixed the issues with it taking a very long time to compile into object files. I've checked this into our mainline now so that we can always have FastBuild enabled without net slowdowns vs. native Unreal builds.

**Comment by ffulin** [comment]
It would be nice to work out why you are getting worse performance in the single file rebuild case.

With the MS compiler, -dist and -cacheread have a small overhead, but mostly that shouldn't be noticeable.

-cachewrite (or -cache) on the other hand has a significant overhead with the MS compiler because it effectively disables the precompiled headers. This is because historically, sharing precompiled headers between computers was not possible. In newer VS versions this is possible, so this might be something that can be improved. This tradeoff is described here: http://fastbuild.org/docs/features/caching.html

With FASTBuild caching right now, with the MS compiler, the ideal case is to have your automated build system populate the cache (-cache), and your developers only read from the cache (-cachread).

Is it possible you are running in -cache or -cachewrite mode?  You might find that instead of disabling the cache you can set it to -cacheread mode instead.

**Comment by yass007** [comment]
Hi!

After trying to narrow down this issue it looks like the performance loss might be coming from the fact that in the distributed build scenario (using -dist) the local compilation jobs are not using PCH and thus slower compared to non distributed builds.

Why?
Because the way we build the unreal bff in our Unreal FASTBuild integration (https://github.com/liamkf/Unreal_FASTBuild)  is as follows:
ObjectList A
 - Creates PCHHeader.pch
 - Uses PCHHeader.pch
 - Compiles: PCHHeader.cpp
 - Outputs: PCHHeader.cpp.obj

ObjectList B
 - Uses PCHHeader.pch
 - Compiles: ObjectB.cpp
 - Ouputs: ObjectB.cpp.obj

ObjectList C
 - Uses PCHHeader.pch
 - Compiles: ObjectC.cpp
 - Ouputs: ObjectC.cpp.obj

In this scenario what would happen in a distributed build scenario is that ObjectB and ObjectC will not be considered as using a PCH (GetFlag( FLAG_USING_PCH ) == false) which means that in ObjectNode::DoBuildWithPreProcessor2() the following code
```
		if ( GetFlag( FLAG_MSVC ) )
		{
			// If building a distributable/cacheable job locally, and
			// we are not going to write it to the cache, then we should
			// use the PCH as it will be much faster
			if ( GetFlag( FLAG_USING_PCH ) &&
				 ( FBuild::Get().GetOptions().m_UseCacheWrite == false ) )
			{
				usePreProcessedOutput = false;
			}
		}

```
Will result into usePreProcessedOutput == true, which will cause the ObjectNode::BuildArgs() to strip the /Yu and /Fp args:
```
			if ( pass == PASS_COMPILE_PREPROCESSED )
			{
				// Can't use the precompiled header when compiling the preprocessed output
				// as this would prevent cacheing.
				if ( StripTokenWithArg( "/Yu", token, i ) )
				{
					continue; // skip this token in both cases 
				}
				if ( StripTokenWithArg( "/Fp", token, i ) )
				{
					continue; // skip this token in both cases 
				}
```

Here are some suggestions for potential fixes:
1) Group all objects using a specific PCH into one single ObjectList. This is how FASTBuild is expecting PCH usage I believe.
So from our example above:
ObjectList A
 - Creates PCHHeader.pch
 - Uses PCHHeader.pch
 - Compiles: PCHHeader.cpp, ObjectB.cpp, ObjectC.cpp
 - Outputs: PCHHeader.cpp.obj

The advantage of this is that it makes the parsing faster and a more readable bff.
The downside is that all these objects would have to share the exact same compilation flags.

2) A quick hacky code fix in Node::BuildResult ObjectNode::DoBuildWithPreProcessor2()
```
		if ( GetFlag( FLAG_MSVC ) )
		{
			bool bIsUsingPCH = GetFlag(FLAG_USING_PCH) || m_CompilerArgs.Find("/Yu");

			// If building a distributable/cacheable job locally, and
			// we are not going to write it to the cache, then we should
			// use the PCH as it will be much faster
			if ( bIsUsingPCH &&
				 ( FBuild::Get().GetOptions().m_UseCacheWrite == false ) )
			{
				usePreProcessedOutput = false;
			}
		}
```

I quickly tried option 2) which fixed our slow distributed build over 4 machines. We are building the UnrealTournament 4 code base.

A non Distributed build with PCHs was giving 12minutes.
A Distributed build **WITHOUT** the local PCH fix was giving 24minutes.
A Distributed build **WITH** the local PC fix is giving around 12minutes.

So it still doesn't seem that we are getting much benefits from the 3 remote workers.
Some potential explanations could be:
- The cost/benefit ratio of pre-processing/distribution is not positive in our case. The compilation happening on the remote workers is considerably slower than on the host (no pch, transfer in/out cost).
- It also like there might be some potential scheduling improvements that could be done to make work overlap better between workers. Maybe the fact that we are clearing the fdb cache (regenerating  the bff) on every build and not using previous build metrics is not helping our case.

Finally, I'm attaching is a snapshot of a visualizer we have been developing (integrated to Visual Studio). It allows us to see how work is spread out across the machines. I have added some comments to it as well.
We are working on finishing some last features + documentation before releasing it.

![visualizer](https://cloud.githubusercontent.com/assets/2611324/17374966/fb36f056-597c-11e6-96af-cb5f3c08098c.png)

**Comment by ffulin** [comment]
I've just merged some changes from the Perforce mainline (https://github.com/fastbuild/fastbuild/commit/9866da8d72ea0abd5f95227100263255eaf43cd8) which change the way that precompiled headers are managed when using the cache.

The changes mean that:
 - Precompiled headers can now be cached
 - Objects built using precompiled headers are now cached while still using the precompiled header (compiling faster and not adding link-time overhead)
 - Running the cached in -cachewrite or -cache mode has no additional overhead compared to -cacheread mode

The end result of these changes is significantly improved compile and link times when using the cache (10%-30% in the cases I've seen)

These changes will be in the next version (v0.91) but if you build your own exe from the dev branch you can try them right away.

**Comment by yass007** [comment]
Nice work!

I have tried your changes and can confirm that PCHs and all OBJs using them are getting cached which speeds up the full rebuild (with no changes) quite a lot. 

This is the monitor screenshot with all the Pink timespans representing the cache hits, the light blue corresponds to the dlls linking actions.
![image](https://cloud.githubusercontent.com/assets/2611324/17607096/6fc722ae-5ff1-11e6-8953-9b71a2125808.png)

I have also added a system graphs feature to the monitor which shows various performance stats.
It seems like when we are at 100% cache hits we are averaging at 50% of CPU time (I guess it's due to preprocessing work) and we are maxing out our IO (copying from the local cache to the build locations).

**Comment by poppolopoppo** [comment]
Wow, nice work and very nice monitor :)
Are you planning to release it at some point ?

**Comment by yass007** [comment]
@poppolopoppo thanks! yes the plan is to release it soon as a VS extension. Hopefully it will be useful as a visualization/debugging/profiling tool for FASTBuild.
The required code hooks on the FASTBuild side should be minimal so it'll hopefully be an easy integration. 
I'll start a new thread about this where we can discuss the integration details and get your feedback.

**Comment by ffulin** [comment]
That visualizer is very nice!  It's great to be able to see the scheduling across PCs. Would be great to spin up another ticket to talk about how to move forward on that as you suggested.

FASTBuild uses [LZ4](https://github.com/Cyan4973/lz4) for compression of the cache objects.  It uses the default compression settings, which give around 2.1:1 compression.  Depending on your use case, it could be interesting to expose a toggle that enables the High Compression mode. This is about 10% of the speed to compress, but decompresses at the same speed and provides around a ~2.7:1 compression ratio. I could see a case where a build machine is populating the cache and developers are consuming it that this might be an interesting trade-off.  I'm also toying with the idea of adding a command line option to FASTBuild where it would iterate and re-compress the cache independently of any build as another way to approach this trade-off.

On the profiling front, just to make sure it's known if needed, if you are building your own FASTBuild executable, you can use the "Profile" build configuration to spit out a "profile.json" in the working dir which can be visualized in Chrome's "chrome://tracing" viewer. That can be interesting to make sure nothing is unexpectedly slow for a particular use-case. Here's an example of what that looks like:
![profiling](https://cloud.githubusercontent.com/assets/11589403/17645216/1f7f164e-6154-11e6-9bee-2bce83f78e88.PNG)

PS - That Unreal link time is pretty unfortunate :(

**Comment by missmah** [comment]
@yass007 Awesome stuff!!! We've been planning to write our own visualizer, and by the looks of it, yours has pretty much everything we'd want, so it may just take that TODO off my task list if you do release it! :+1: If I can be of help along the way, please let me know!

**Comment by missmah** [comment]
@ffulin Thanks for the cache updates! Does this mean that it makes sense to have worker machines populating their own cache now, versus only enabling cachewrite on a build machine?

**Comment by yass007** [comment]
@missmah Great to see that it would be useful to you. 
A first version has been released already and I opened a ticket to discuss the integration with @ffulin here:  https://github.com/fastbuild/fastbuild/issues/127

If you want to give it a shot you can find the vsix extension package and the setup instructions here: https://github.com/yass007/FASTBuildMonitor

**Comment by ffulin** [comment]
@missmah 
**> Does this mean that it makes sense to have worker machines populating their own cache now, versus only enabling cachewrite on a build machine?**
I guess it depends on the environment, but I tend to think having the build machines being the only writers to the cache is probably preferable, since local edits by users would generally be ephemeral and not that useful to put into the cache, so limiting bandwidth/disk-space usage of the cache is probably better than the cache improvement you may sometimes get.
This is how I have it setup.

(Note that FASTBuild does intelligently avoid caching some ephemeral object files already like those created if using UnityInputIsolateWritableFiles)

**Comment by ffulin** [comment]
How does everyone feel about closing out this ticket?  I think we've forked off new tickets for anything outstanding (like the Visualizer).
