### ISSUE TITLE
FastBuild not distributing linking steps

### ISSUE THREAD

**Issue by missmah** [fastbuild/fastbuild#123]
This particular .BFF was entirely linking steps, and for some reason, despite having 3 workers in the pool, none of the steps were distributed. Is this expected? Thanks in advance for the help!

48>  --- Summary -----------------------------------------------------
48>                                   /----- Cache -----\
48>  Build:          Seen    Built   Hit     Miss    Store   CPU
48>   - File       : 26      26      -       -       -       0.000s
48>   - Alias      : 1       1       -       -       -       0.000s
48>   - Exe        : 27      27      -       -       -       9.743s
48>   - DLL        : 363     363     -       -       -       8m 35.706s
48>  Cache:
48>   - Hits       : 0 (0.0 %)
48>   - Misses     : 0
48>   - Stores     : 0
48>  Time:
48>   - Real       : 1m 14.508s
48>   - Local CPU  : 8m 45.449s (7.1:1)
48>   - Remote CPU : 0.000s (0.0:1)
48>  -----------------------------------------------------------------
48>  FBuild: OK: all
48>  Time: 1m 14.656s

**Comment by missmah** [comment]
Just to clarify, I understand that a single linking step can't be distributed; but, many of these DLLs/Libraries are independent of each other, and so I'd expect that linking them in a parallel and distributed manner should be trivial on a system like FastBuild.

**Comment by ffulin** [comment]
Only compilation is distributed to remote workers.  Linking can only be done on the local machine. You can see that linking was parallelized locally however, since the Local CPU time is 8m45s, while the wall-clock time was 1m14s.

Looking at your summary it's a little strange to see something that is entirely comprised of only linking. Is there no compilation as part of this build?

Is this is a side-effect of the Unreal build system script using DLL() incorrectly? If DLL() was used for compilation steps, that would prevent distribution (as well as causing other problems like missing dependency tracking).

**Comment by ClxS** [comment]
The huge compilation only projects are likely due to my approach to my UE4 script. It makes it far simpler to split compilation into two passes- an object compilation pass, then a link pass. This avoided having to parse response files on the linker actions and made no real different to compilation time.

DLL nodes do not get used for compilation steps, but there are many, many linker actions in a full UE4 rebuild.

**Comment by missmah** [comment]
As ClxS said, it's due to the UE4 script's approach, which I've modified a bit to be able to run certain steps in isolation, as was the case here. :)

I still can't see why linking can only be done on the local machine. What's the limitation here? If the build steps are independent, they should be able to be run remotely (in theory, anyway - I understand that FastBuild doesn't currently support this).

What would be required (besides bandwidth), code changes, and possibly changes to how dependencies are done remotely, to distribute linking?

**Comment by ffulin** [comment]
Linking (for .dlls or .exes using link.exe) is technically possible to distribute, but would be very heavily network bound - it's not uncommon to require hundreds of MiB or even GiBs of input .lib and .pdbs. Similarly, the returned debug .pdb can be similarly huge.  There certainly could be situations where it's an overall win.  FASTBuild could be modified to support this distribution, but it might require some limitations (like no implicit linking via #pragma lib for example), 

Static libraries on the other hand (for .lib using lib.exe) tend to be very fast and entirely IO bound (very little CPU usage) and thus generally would cost far more time in transfer than would be gained through distribution.

On the subject of the UE4 script - running the build in two passes is a missed opportunity for performance.  Firstly, no compilation and linking can overlap (could be linking a dll while remote compiling some code).  Secondly, the rescheduling between builds cannot optimize across the two passes (there is an adaptive re-ordering of compilation that aims to reduce total build time by using previous build timing info)

**Comment by missmah** [comment]
We have multiple 40Gbit/sec networks, so I'm not sure that would still be true about being network limited? :)

But in any case, it does sound like making everything build in one pass would be a net win.

Another bit is that we end up with many .bff files during the course of the build, and every new build over-writes the .bff file (sometimes multiple times). It seems like then both UE4's UBT and FastBuild are doing redundant dependency checking.

Ideally, I'm guessing we'd want to create a single .bff file for FastBuild for the entire UE4 project, and not touch that file again until the next time it was necessary to run UE4's GenerateProjectFiles.bat (meaning there were new or removed files which needed to be accounted for).

@ClxS what do you think of this? Between the three of us, do you think we could get there?

**Comment by ClxS** [comment]
You're right that the dependency checking by FBuild is redundant, as that's already handled by the UBT by the time FBuild gets a bff. This is why two-pass compilation had minimal impact on performance for us - as we wouldn't have been receiving the performance benefit in a single-pass approach anyway.

I see there being more problems than it's worth trying to replace the UBT tool with a single BFF generation really.  There's a long-term stability issue as it'll likely break with future UE updates. The main pro to a single .bff generation is something that Unreal mostly achieves before passing the object anyway. Since the UBT is tailored for building Unreal, I feel it'd be a huge amount of work to get FBuild to do the job just as well. I mean, it's possible, if I remember correctly there was a way to get the UBT to export a cmake file back in 4.5, and I heard of work on a cmake FASTBuild generator you'd be able to use - but I wont be doing it. :)

One pass compilation which allows compilation/linking overlap is definitely something I'm intending to add though.

**Comment by liamkf** [comment]
Ahoy! Just to add to what Carl was saying, we did a version awhile back of [FASTBuild.cs](https://github.com/liamkf/Unreal_FASTBuild/blob/master/FASTBuild.cs) to generate a bff file from the Unreal build actions. We had dreams of skipping some of the UBT dependencies as well but got discouraged when we saw we'd likely be running it anyways for the shader compiler, header tool and all the build.cs glue code that would be a lot of work to handle. All that to say it would be amazing if it worked... :)

Our version does have the compilation and linking in one step if you want to give it a try (with some hacks to fake Executable nodes having PrebuildDependencies), but I'd be surprised if it saves more than a couple of seconds versus doing it in two passes for Unreal: linking doesn't seem to be our bottleneck very often.

**Comment by hillin** [comment]
Actually IncrediBuild does distribute linking tasks

**Comment by comicfans** [comment]
@hillin could you please provide this information link ? from incredibuild [website](http://xoreax.helpserve.com/Knowledgebase/Article/View/14/0/can-incredibuild-distribute-and-parallelize-links-andor-custom-steps), it said that link tasks is not distributed

**Comment by hillin** [comment]
@comicfans yes it does. As we can see in the following screenshot, IncrediBuild aggressively distributes the linking steps to all agents (the screenshot is from a build I made several minutes ago).

![xge-linking](https://cloud.githubusercontent.com/assets/13517745/26769423/752c505e-49e1-11e7-8b3e-29dadb61dfd0.png)

**Comment by comicfans** [comment]
@hillin thanks for this information .

**Comment by hillin** [comment]
I hope @ffulin can look into this again and maybe someday we can have distributed linking in FASTBuild. In our tests, by distributing linking steps, IncrediBuild can save up to 2 minutes while building Unreal Engine.

**Comment by ffulin** [comment]
It's still a possibility that linking could be distributed in the future, but it would take significant changes to the worker protocol to make it even remotely likely to be worth it. We'd really have to cache common objects to avoid a network transfer size explosion, and that brings with it remote worker disk space management issues. All possible, just not trivial.

On a related note, is the Unreal support for FASTBuild still doing two (or more) passes? (compiling and then linking explicitly in two phases)? If so, fixing that would restore a great deal of parallelism.

**Comment by hillin** [comment]
@ffulin The two-pass build process is adopted by the UnrealBuildTool, but not the FASTBuild wrapper. I didn't dwell very deep into the Unreal Engine's build process, but it seems they have some special reasons to do that, maybe shared PCH is one of them.

**Comment by ffulin** [comment]
> The two-pass build process is adopted by the UnrealBuildTool,

Interesting. I wonder if that something that could be fixed, and whether that's worth it or not.
