### ISSUE TITLE
Nodes with LinkerLinkObjects do not correctly add response file dependencies

### ISSUE THREAD

**Issue by ClxS** [fastbuild/fastbuild#138]
Hi there,

I'm just wrapping up being able to use Library nodes with UBT properly and ran into this bug.
This BFF configuration will encounter the problem (stripped out unimportant stuff for brevity):
```
Library('DLL-1134')
{
	.Compiler		 			= 'Null'	
	.CompilerOptions 			= '%1 %2 %3'	
	.CompilerOutputPath		 	= ' '	
	.Librarian		            = '$VSBasePath$/bin/amd64/lib.exe' 
 	.LibrarianOutput		  	=  'UE4Editor-Niagara.lib' 
	.LibrarianOptions		 	= '/NOLOGO /NAME:"UE4Editor-Niagara.dll" @"%1" /OUT:"%2"'
	.LibrarianAdditionalInputs	= { 'UE4Editor-Niagara.lib.response' } 
 }
DLL('DLL-1124')
{
	.Linker		            	= '$VSBasePath$/bin/amd64/link.exe' 
 	.LinkerOutput		  		=  UE4Editor-Internationalization.dll'
 	.LinkerOptions		 		= '/DLL @"UE4Editor-Internationalization.dll.response" "%1" /OUT:"%2" /IMPLIB:"UE4Editor-Internationalization.lib" /PDB:"UE4Editor-Internationalization.pdb" /ignore:4078'
	.Libraries		            = { 'DLL-1134' } 
}
```
(I realise the ultimate fix is to just not use FASTBuild like that - but this style works very well with the UnrealBuildTool. Extracting the response file lines and using that increases the BFF file size by 10-20x)

The problem is caused by ObjectListNode::GetInputFiles not properly handling files with .response extensions, and results in BuildArgs returning something like this:
`/DLL @"UE4Editor-Internationalization.dll.response" "UE4Editor-Niagara.lib.response"   /OUT:"UE4Editor-Internationalization.dll" /IMPLIB:"UE4Editor-Internationalization.lib" /PDB:"UE4Editor-Internationalization.pdb" /ignore:4078 `

**Comment by ffulin** [comment]
FASTBuild has no awareness of use of custom response files.  FASTBuild is designed with the expectation that you provide all the dependency information in the bff and it creates a response file as needed.

I don't know if there is a good way to support what you want.  The issue is that normally you list the libraries used as static dependencies in the bff, but by offloading them to a response file, FASTBuild will have to parse that at build time, but discovering the dependencies of a library at build time is too late to enforce proper build ordering. I think this would require considerable refactoring to support.

Out of interest, what is the concern with writing the dependencies directly into the bff file as you suggested? The size of the bff shouldn't be an issue for FASTBuild. Is there some other problem that causes?

**Comment by ClxS** [comment]
My hope was that it would just use the proper \@ include when encountering a .response as I already remove files built by fbuild nodes from the .response when constructing the BFF, but I see what you mean, it'd be pretty incomplete without also adding the resolving into FASTBuild itself.

I did encounter a few other issues when expanding the response files when tried in the past but I may have just handled them incorrectly. I'll have a look into that. In my case just disabling LinkerLinkObjects on the problematic nodes works fine.
