### ISSUE TITLE
Heterogeneous OS distributed compilation

### ISSUE THREAD

**Issue by cyberkm** [fastbuild/fastbuild#139]
Hi, I am just wondering if there is a fast way to build compilation farm across several different operating systems:

More specific case, I have several Mac, Windows and Linux boxes. I would like to force them all to use same clang version to cross compile for arm architecture using fastbulid --dist option.

The fbuild.bff script theoretically can be run from any of those machines.

Is it doable, and what are pitfalls that can await me?

**Comment by ffulin** [comment]
What you are proposing is an interesting idea, and should be technically possible, but is not currently supported by FASTBuild. 

The definition for the local compiler and the files to synchronize to make the toolchain available remotely are currently the same thing - both defined in the Compiler() section of the bff, and assumed to be for the same OS.

To do what you are proposing would require:
 - The Compiler() section to contain alternative toolchain mappings, associate with different OS versions
 - The Compiler at run-time to encapsulate this in multiple ToolManifest structures
 - The network handshake packet to contain info about the FBuildWorker OS type
 - The ToolManifest synchronization to send the correct files for the remote OS
 - Some mechanism to say that we want to support cross-OS connectivity between workers, because we'd normally consider that to be an error (though right now FASTBuild assumes you would separate the worker pools via unique brokerage paths and has no explicit check for this, though it probably should :) )

Additionally, it might require:
 - Moving distributed compilation support for OSX and Linux from Alpha status to Beta status - it is currently missing a couple of bits to be at feature parity:
  -- Idle CPU detection (you could work around this by running in "always" mode)
  -- Implementing the FBuildWorker UI for OSX (you could just use the console version which is currently implemented)

There might be other issues of course, but that's what I can think of right now :)

**Comment by rickvanprim** [comment]
Aside from FastBuild looking at the compiler name and inferring things from that, could this not be accomplished with some scripting and evil'y named scripts?  Essentially if the BFF file always called "<project root>/Windows/clang", but on each machine "<project root>/Windows/clang" is a script that invokes "/clang <machine specific cross compiling arguments> $*".  This would require you move all the cross compiling specific logic into scripts that would have to be set up on each machine, though that could likely be accomplished by having them in your repo named specifically for which source->target mapping they are, and then symlinking them into the right spot once per build machine.

**Comment by ffulin** [comment]
I don't think you could create a file called "clang" that is some sort of script that would seamlessly run on all machines. It sounds pretty hacky in any case.

**Comment by rickvanprim** [comment]
Naming it "clang" to fool FastBuild would be the part I consider hacky.  My point was, if FastBuild doesn't understand which platform it's being run on relative to which target it's trying to build (to accommodate different cross compiling options for the same intended output), that could probably be worked around by some local differences on the individual build machines, per target, to account for being on different platforms.  This way FastBuild just invokes the same distributed compile across all machines and gathers the same output, and doesn't need to know any of the cross compiling specifics, just the output target type.

This doesn't address FastBuild not allowing a distributed build to be run across platforms, but should address the other issues.

**Comment by ffulin** [comment]
I'm going to close this issue. While being able to target a single platform in a distributed compile using workers of different OS types is certainly an interesting idea, it's not something I plan to support.
