### ISSUE TITLE
Project could have additional information about vendorized toolchain approach

### ISSUE THREAD

**Issue by fitzymj** [fastbuild/fastbuild#153]
FASTBuild's project structure seems somewhat unique in that it expects compilation toolchains to live inside the project tree, rather than be installed locally on the user's system.  It would be great if the project documentation expounded upon that approach, either broadly (i.e., the philosophy behind it) or practically (what setup is necessary for new users to compile FASTBuild).

**Comment by rickvanprim** [comment]
To get FastBuild to build, you should just need to go into the External folder and symbolically link in a few VS directories.  I don't have it in front of me at the moment, so I can't give exact paths.  Note that doing this isn't really following the vendorized toolchain model.

For size (and presumably legal) reasons, I wouldn't expect to see those directories in the GitHub repo.  However in a private environment (such as where I work), we have all toolchain checked in to source control, which means that in order to build the product, all you do is sync the files, and run FastBuild.  There are no local dependencies on installed tools, libraries, etc.  Another perk is it decouples the project from the IDE, so it's trivial to locally upgrade to the latest Visual Studio and enjoy the new editor features, without having to move the whole project from one version of the toolchain to the next.

**Comment by poppolopoppo** [comment]
I had the same problem the first time I tried to compile FASTBuild, which lead me to write a windows script to configure the externals :
https://github.com/poppolopoppo/fastbuild/commit/39801eb348bc4631ef80f1a2800ae44fa34c0c96

Hope it helps some people while waiting for a more better solution.

**Comment by fitzymj** [comment]
Out of curiosity, how big do those checked-in toolchains end up being?  The Android NDK installation, for example, is ~3GB.  How do you pare that down?

**Comment by ffulin** [comment]
> Out of curiosity, how big do those checked-in toolchains end up being?

It definitely gets pretty big.  For FASTBuild it's 14GiB for the "External" folder right now. I haven't worried about trimming it down much and I've kept all the historical versions I'm no longer actively using for convenience.  For a *very* large project, 30-50GiB is probably the top end of what I've seen.

By default I tend to just take an SDK in its entirety, as it's simpler, but when space is at a premium, there are some pretty easy ways to trim down:
 - remove libraries/dlls/compilers for platforms you don't need (the Visual Studio contains x86, x64, arm and arm64 (and some cross compilers) so you can easily delete the ones you don't need)
 - remove documentation. Some libraries have massive amounts of documentation. If it's a public API, then you will probably use google for your documentation anyway :)
 - remove unused binaries. You can sometimes go to the effort of deleting executables not needed for compilation.

I'm not familiar with that Android NDK, but I downloaded it and took a quick look.  It seems there are similar opportunities for saving in there:
 - stuff for targeting arm vs mips vs aarch64 vs x86 vs x86_64 architectures (80-160 MiB each)
 - libraries for different android versions (9, 12, 13, 14, 15, 16, 17, 18, 19, 21,22, 23, 24) (40-140 MiB each)

If you are using Git, then it's probably still too big.  It's a real shame the Git can't support large files properly.

**Comment by jairbubbles** [comment]
One way to prevent so much binary data into Perforce is to use a package manager (like NuGet for instance).
In Perforce you'll just need to store the information of which version of a specific package you need for a specific project in a specific branch. The main interesting point is that you won't have binary duplication when creating new branches or new projects using the same exact package (on the server but also on your desktop). All aforementioned benefits are also true with that approach.

Anyway for it to work properly you need everything to be packaged properly but it's not that complex. You're already creating vendorized versions of SDKs so you would just need to add .nuspec and create a package with that folder (sadly because of legal reasons I'm not sure you could upload it on official servers).

> If you are using Git, then it's probably still too big. It's a real shame the Git can't support large files properly.

I would say provocatively that it's great Git does not support large files properly as it has forced developpers to do things the good way (ie don't put binaries in SOURCE control). And/or it's a shame Perforce handles so well binary data as it has made us lazy developpers ending up submitting everything in source control (without even caring about the size of our depots).

**Comment by ffulin** [comment]
I don't want this to descend into a Git vs Perforce argument. (The only way to win that is not to play at all :) ).  However, I think it's worth responding to your comments to provide some additional background on why I so strongly hold the "everything in one place" point of view.

> One way to prevent so much binary data into Perforce is to use a package manager 

If using Git, this is one of your options. There are also efforts around the place to "fix" Git such that it's capable of referencing a large asset depot (things like [git-lfs](https://git-lfs.github.com/)).

I'm not a fan of either of these approaches because:

**Relying on external repos in your build pipeline is bad.** Internet connectivity can be lost, external services can go offline or packages can be revoked ([left-pad](http://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos/) anyone?).  I don't want to be in a situation where I can't do a build and the reason I can't do a build is outside of my control.  Relying on external package managers is also a security vulnerability.  As you noted, licensing will often prevent the use of an external repo anyway.

**Creating a local package repo is another thing to manage.** Less is more.  If I can run one thing instead of two, I'd prefer that.  Particularly if (as a game developer for example) I'm already using something like Perforce out of necessity to manage revision history of binary assets for all my artists and content creators.  My entire build inputs (all code and data) can be in one place.  This is important when (as is often the case) there are dependencies between code and data (I don't want to have to commit to two different places).

> I would say provocatively that it's great Git does not support large files properly as it has forced developpers to do things the good way

This is very provocative :)  Lack of large file support is a serious problem with Git outside of the vendorization discussion.  I already noted the "data" and "two systems" issues above, but in addition to that there are other issues, such as:

**3rd party libraries when you need to make custom modifications**
It is very common in the world of game development to have source code for only a portion of a 3rd party library (like a Physics engine for example) and to need to make modifications to it in order to integrate with your own code.  When an engineer makes an update to one of these external libraries, it often involves changes to our code as well as this 3rd party library.  Being able to see both of those, together in the context of source control revision history and code reviews is very important.  Having to arbitrarily split this code from the provided libraries and (for example) have to create a package to roll out to other developers because of a limitation in the source control is not a feature.

**Binary resources in source code**
It's pretty common to have binary assets that need to be embedded in your executable.  Git forcing you to control those assets in a completely different way is pretty annoying.

**Who decides what is "data" and what is "too big"**
Let's say I'm developing an application or game with a lot of HTML, CSS, JavaScript and PNG content.  Should I make all my developers check some of these files into one place, and put the other files in another? Which of these files should be in Git and which ones shouldn't?  Which of these files are "code" and ok to go in Git?  Which of these are "binary data" and shouldn't go in Git? PNGs are not that big, so it's proabably fine, but what about if I add movie files to this list?  What about when I have 100 developers and the total size of the Git repo continues to grow over time?At what point is a file "too big" for Git? I could develop a bunch of systems and rules for managing this, or I could just put it all in one place and spend that time working on the actual thing I want to ship to my users/players. :)

The TL;DR: for me is that Git forces you to do things a specific way regardless of whether that is best for your project or your overall workflows and that's definitely not a feature.

**Comment by jairbubbles** [comment]
Well it was not a Git vs Perforce argument at all ! :-D 

> Relying on external repos in your build pipeline is bad.

Yes completely true. That's why the best practice with package managers at least in enterprise is to have an internal server which mirrors external package plus add you owns.

> 3rd party libraries when you need to make custom modifications

Of course and you'll need specific depot in your enterprise to allow that. You can use Perforce if you want ;-)

And clearly for all the other aspects of course we need to put binary data along with code. 

I was very provocative, I use perforce all the time, I just feel like we forgot to be smart when using it ending up with monolithic ang huge code base. I just like collaborative forkflows around git.

The idea between package manager is to have an indirection for you binaries referencement. The tricks you do with symbolic links and vendorized is pretty similar to that. It's nice because it's simple and you reuse your existing P4 infrastucture. NuGet is just a formalism around that idea which is just more generic and not linked to Perforce or Git for instance. It adds some complexity though I agree.

**Comment by fitzymj** [comment]
A lot of this back-and-forth makes sense to me—thanks for elaborating!  Mostly I like to hear about how other people and places solve problems like this.  :)

One drawback of toolchain inclusion that still bugs me a bit, is that when you've got multiple projects or project branches synced to your computer (say via Perforce), you have multiple copies of that ~20GB set of toolchain binaries.  Is that just a necessary downside of the model, or is there a smart way to manage this (either internally or externally to Perforce)?  Do people just buy bigger hard drives to manage this?

**Comment by jairbubbles** [comment]
You can put all your extern SDKs in a depot:

Extern - WinSDK
           - DirectXSDK
           - ...
ProjectA - master
              - dev
              - ...
ProjectB - master
             - dev
             - ...

Exten can be really big and it's hard to know for a given project what you really need but at least you don't have duplicaton of the same SDK.

For me a package manager is just a more advanced version of that scheme. For each project you know which are the depedencies so you can sync them smartly. You can clearly do that with perforce and really simple scripts.

**Comment by ffulin** [comment]
I tend to work with one depot for an entire project, so for a game that would include all the tools used for authoring data as well as things like maya/photostop exporters and also all the tools used during the data build/cooking process.  This means most of External is only stored once and shared by all those things.

When it comes to branches, I tend to avoid those as much as possible, with the exception of creating branches for things like snapshots for releases or important milestones.  This generally means, at any given time you only need one or two branches on your local machine. If working in games, you'll need much more space for all the content than for code anyway, possibly by an order or magnitude, so this cost really isn't too much of an issue :)

Something like jairbubbles suggests might be a solution if you really have a lot of unrelated depots and you are really tight on space, but a bigger hard drive is the solution I'd go for. Good 1TiB SSD drives are getting pretty cheap @ ~$250-300.

**Comment by nedwardsnae** [comment]
Hi @ffulin, I appreciate you detailing the philosophy behind vendorization - there is a certain lack of information online about this. In fact, this issue is one of the main results on google when searching for vendorization.

Is there any chance you could provide any additional detail regarding your approach to including all dependencies in source control? Specifically, whether you simply install things like Visual Studio directly into a folder in your Perforce workspace, or whether you use a script like https://github.com/Leandros/VisualStudioStandalone to copy a pre-existing install. Especially since certain dependencies may still install certain components outside of the target install location.

Thanks again for providing this info!

**Comment by ffulin** [comment]
It'd probably warrant a blog post someday to completely describe things, but in the interim, I can provide a TL;DR:

The method I use for vendorization is fairly low-tech. I install the toolchain (on Windows, Linux or OSX) as normal into whatever place is the usual default for the OS (Program Files for example). I then copy the directory into the P4 repo, usually trimming out junk that is not needed (like documentation or libs for unused platforms). There is a balance to be struck between simplicity (just copy the whole thing) and saving space. Having done it a few times, particularly for MSVC, you get pretty good at knowing which folders are important and it's only something you usually do a few times a year.

Occasionally, when the structure of one of these toolchains changes significantly, it can be useful to verify the vendorized SDK on a new machine by utilizing a VM. A clean install of the OS and syncing the repo only ensures nothing is missed.

I hope that (very brief) info helps. I can probably elaborate further if you want some more specific details.

**Comment by claimred** [comment]
@ffulin how do you solve CI problems with a repository like that? My understanding was that doing a clean checkout on a build agent is a must have.

**Comment by ffulin** [comment]
All the build systems I use (or have used) allow you to set affinity for certain tasks with certain nodes, so that all your builds are incremental, both in terms of syncing from source control and the actual compilation itself.

With this setup you can build every commit in isolation as well, so you know exactly when a change "broke the build".

**Comment by claimred** [comment]
Another thing I was wondering about is how do you deal with inhouse patches to 3rd party libs? Just store them inside the repo as separate commits and when the time comes to update the library rebase onto new version?

**Comment by ffulin** [comment]
> how do you deal with inhouse patches to 3rd party libs? 

I usually keep the following folder structure for all 3rd party code:

External/<library>/version/

When committing a new version, the first commit is the pristine untouched code. And changes (hopefully none, but sometimes they are needed) are made as followup commits, including potentially re-creating or integrating fixes from a previous version. This keeps a clear revision history.

A nice thing about this approach is that it also allows multiple versions to be used at the same time, which can be great when one platform has a bug that requires a rollback but you need to keep a change or fix in the latest version for a different platform.
Additionally, it allows the commits of the new version to be seperate from the single bff change that "switches" the versions, allowing for trivial update/rollback.
