### ISSUE TITLE
Build-In Variable: Current Time

### ISSUE THREAD

**Issue by Leandros** [fastbuild/fastbuild#156]
I like to include the build time in my projects as a simply diagnostic when each build was started.
Would be great if there could be a simple build-in variable holding the current time in some predefined format (for example ISO-8601, it's standardized, easy to parse and human readable).

**Comment by ffulin** [comment]
Just to clarify, do you mean a single timestamp to appear at the start of the build output?

Also, can you please clarify what you mean by a "built-in variable" holding the current time?  How would you expect to use that?

**Comment by Leandros** [comment]
Similar to the already existing build-time substitutions, simply instead of holding the current processed file, hold the value of the time when the build was initiated. 

I normally have something along the lines of:

```
CPPFLAGS += -D__BUILDTIME__="$(shell date -u +"%Y-%m-%dT%H:%M:%SZ")"
```

in my Makefiles to get the buildtime as a cpp constant (often combined with a VCS revision, like `git describe` or similar for p4).
I would be great if I could achieve the same in FASTBuild, since I find it very useful for various things.

**Comment by ffulin** [comment]
Thinking about this some more, it seems this should be possible (and not very difficult).

There is a drawback however: This substitution would disable caching for any objects that use this token in the args (since retrieving from the cache would not yield the expected objects otherwise). This is the same as use of __TIME__ in any code (and to a lesser extent __DATE__) which also prevents caching.

If the goal is to embed a build time in your final executable, I generally recommend that you inject it post-link (with a custom fixup exe), rather than doing it at compile time.  This ensures the date/time is always correct (doesn't rely on specific objects being built) and doesn't prevent caching.

**Comment by Leandros** [comment]
That is a fair point I haven't really thought about. Given the implications, this is sort of losing it's appeal to me.
