### ISSUE TITLE
gethostname doesn't contains the domain name

### ISSUE THREAD

**Issue by ktamail666** [fastbuild/fastbuild#160]
Our servers are in different domain. In this case the ip that the worker got was wrong because the WorkerBrokerage don't saved the domain.
Similar at nslookup can return two different ip depend on I used the netbios name or FQDN.
I hope it is understandable.
This little change solve the problem on Windows in Network.cpp:
`TCHAR local[256];`
`DWORD hstSize = sizeof(local);`
`GetComputerNameEx(ComputerNameDnsDomain, local, &hstSize);`
`if ( ::gethostname( buffer, 64 ) == 0 )`
  `{`
       `hostName = buffer;`
     `hostName += ".";`
    `hostName += local;`
 `}`

**Comment by ffulin** [comment]
This seems reasonable enough and presumably we'd need something similar for Linux and OSX.

**Comment by ffulin** [comment]
In the next release (v1.03), the brokerage token name is the IP address instead of the host name. The IP address is used to initiate the connection instead of the hostname, which improves connectivity in various scenarios. That should resolve this issue. I will leave this issue open until that version is released.

**Comment by ffulin** [comment]
v1.03 has now been released and contains the changes described above.
