### ISSUE TITLE
Does fastbuild use dependencies to determine build order?

### ISSUE THREAD

**Issue by TheClassic** [fastbuild/fastbuild#161]
I'm under the impression that it doesn't. Any plan to support a feature along this line?

For example, I have on the order of 100 different dll's I'm building for a product, some depending on the others. My Visual Studio projects allow me to specify the project references and when I build the solution, it determines the appropriate order to build.

If I generate a .bff for each library, I'm under the impression that when including these in a product .bff that I need to specify these in the correct order so that the required libraries are available for linking. Is my understanding correct?

**Comment by rickvanprim** [comment]
FastBuild is building things in dependency order.  Each DLL (as in the DLL() node in a .bff) can build separately as the root of your dependency tree.  From there each is going to depend on various Library()'s, which in turn may depend on other Library()'s, etc., and from this things will get built starting at the leaf nodes, and ultimately working back up to the DLL()'s.

It's not really possible to not build in dependency order.  Otherwise most of your builds would fail due to their dependencies not yet having been built.  If you're running into errors of that nature, then presumably your dependencies are not set up correctly in the .bff config.

**Comment by ffulin** [comment]
The answer is perhaps a bit more nuanced than you might expect, so bear with me....

Strictly speaking, the order of bff includes doesn't impact the build order.  What does impact the build order is the dependencies you specify within those bffs.  For example, if you define Dll A and then defined Dll B, which links against Dll A, that imposes a dependency constraint which FASTBuild understands.  This is roughly analogous to specifying the "Project Dependencies" in Visual Studio which it then uses to determine the "project Build Order" (but not entirely the same for reasons I'll explain below).

FASTBuild requires that you declare something before you use it, so that means you typically include the bff for Dll A in the example above before Dll B, but this in and of itself is not the direct mechanism that controls the build order.

To be more specific, when you define a dll for linking, it is the .Libraries parameter that tells FASTBuild about the dependencies:
```C++
DLL( 'DllB' )
{
    .Libraries = 'DllA' // FASTBuild knows to link DllA first because of this, not because of the include order
```

Now here's where it gets a bit more subtle:

FASTBuild is smart enough to know that compiling a library/dll and linking it are two different things and that while a Dll can't link until the dependent Dlls link, it can be compiled at any time (even before the Dll it depends on).  
This feature of FASTBuild is a reason why it is frequently significantly faster than Visual Studio (particularly for Dll Builds) even before you talk about distributed compilation or caching.  In short, since it can parallelize far more often, it's a much better utilizer of system resources.

FASTBuild can freely order the object files down to the individually .obj level, so that in our example it might even build things in an order like this:
 - Compile half of Dll B
 - Compile Dll A
 - Link Dll A while compiling the rest of Dll B in parallel
 - Link Dll B

It decides on this order, by utlizing timing from previous runs and considers whether you are doing a full build or an incremental build - i.e. FASTBuild always tries to find the optimal scheduling order to have the build finish as quickly as possible within the constraints of creating a valid build.

I hope that makes sense and answers your question :)

**Comment by TheClassic** [comment]
Thanks for the excellent answers. The documentation on the fastbuild site is good, but allowing contributions, either through a wiki or documentation compiled from the source would probably benefit everybody

**Comment by ffulin** [comment]
> allowing contributions, either through a wiki or documentation compiled from the source would probably benefit everybody

The documentation in the source download and the website are the same thing, and it's already available on GitHub: https://github.com/fastbuild/fastbuild/tree/dev/Code/Tools/FBuild/Documentation

Improvements to the documentation are welcome.
