### ISSUE TITLE
Example for VCXProject incorrect

### ISSUE THREAD

**Issue by Leandros** [fastbuild/fastbuild#171]
In the documentation for the `VCXProject` function, the elements `.ProjectBuildCommand`, `.ProjectRebuildCommand` and `.ProjectCleanCommand` contain a literal ampersand, which will be included in the generated .vcxproj file.
Due to .vcxproj being in XML, the ampersand produces parser error and subsequently Visual Studio will refuse to parse the file. Replacing the ampersand with it's "escaped" XML version `&amp;` will fix the problem.

**Comment by ffulin** [comment]
Thanks for reporting this. The problem was that the ampersand in the &amp; needed escaping in the html documentation (double escaping).  I've fixed the documentation and this will be part of the next release. Thanks for reporting this.

I'll keep this issue open until the next version is released (v0.93).

**Comment by ffulin** [comment]
v0.93 has now been release which includes this fix.
