### ISSUE TITLE
Changing env var 'LIB' forces rebuild

### ISSUE THREAD

**Issue by Leandros** [fastbuild/fastbuild#172]
If the environment variable `LIB` changes, FASTBuild is re-parsing and re-building the project.

    'LIB' Environment variable has changed - BFF will be re-parsed

This is particularly annoying if I jump between building via command-line and building via Visual Studio integration.
I understand the intention behind this, but do not understand where 'LIB' is actually used and how it might affect compilation?
I would also like to disable it, since I never `#import` it anywhere, nor use pre-defined library paths (due to using a similar vendored toolchain approach as FASTBuild itself is using).

**Comment by dummyunit** [comment]
I am setting up a clear enviromnent in the config, this solves this `LIB` issue and protects from other variables affecting build results. This is what I have (approximately) in my configs:
```
Settings
{
	// Use clean environment to prevent rebuilds caused by changes in it.
	// All important variables are imported exclicitly.
#import SystemRoot
	.Environment =
	{
		'SystemRoot=$SystemRoot$' // required by cl.exe (error D8037)
		'TMP=$SystemRoot$/temp' // required by cl.exe (error D8050)
	}
}
```

**Comment by Leandros** [comment]
Awesome!
Works like a charm.

**Comment by ffulin** [comment]
The LIB environment variable can be used to determine the location of libraries used for linking when they are provided without absolute paths.  FASTBuild needs to know the location of these in order to track the dependencies correctly.  If LIB changes, the dependencies need re-evaluating and this logic is currently done during BFF parsing.

Suppressing the LIB environment variable as suggested by dummyunit means you can avoid this if you know your setup doesn't rely on the LIB env var.

(Any reparsing of the bff causing a full-rebuild is a known limitation of FASTBuild which is being addressed.  More details here if you are interested: https://github.com/fastbuild/fastbuild/issues/108)
