### ISSUE TITLE
-dist, Visual Studio, and precompiled headers

### ISSUE THREAD

**Issue by haferburg** [fastbuild/fastbuild#173]
What are the implications of using -dist on a project that uses precompiled headers? Is that really supported? I would expect that every worker compiles their own PCH first, then uses their own local copy, but that doesn't seem to happen. Is that not possible?

When I build with -dist and one worker I currently have longer build times than when I build without -dist. I'm seeing similar results with a real world project I'm testing with. What am I missing? I would appreciate any pointers on how to make -dist work.

```
G:\dev\src\fastbuild\testproject>fbuild -clean -dist -j1
Distributed Compilation : 1 Workers in pool
1> Obj: B:\build_test_fb_x64\libA\libAPCH.pch
1> Obj: B:\build_test_fb_x64\libA\g.obj
1> Obj: B:\build_test_fb_x64\libA\d.obj
-> Obj: B:\build_test_fb_x64\libA\g.obj <REMOTE: 192.168.66.179>
1> Obj: B:\build_test_fb_x64\libA\b.obj
-> Obj: B:\build_test_fb_x64\libA\d.obj <REMOTE: 192.168.66.179>
1> Obj: B:\build_test_fb_x64\libA\f.obj
-> Obj: B:\build_test_fb_x64\libA\b.obj <REMOTE: 192.168.66.179>
1> Obj: B:\build_test_fb_x64\libA\e.obj
-> Obj: B:\build_test_fb_x64\libA\f.obj <REMOTE: 192.168.66.179>
1> Obj: B:\build_test_fb_x64\libA\a.obj
-> Obj: B:\build_test_fb_x64\libA\e.obj <REMOTE: 192.168.66.179>
1> Obj: B:\build_test_fb_x64\libA\c.obj
-> Obj: B:\build_test_fb_x64\libA\a.obj <REMOTE: 192.168.66.179>
1> Obj: B:\build_test_fb_x64\libA\h.obj
-> Obj: B:\build_test_fb_x64\libA\c.obj <REMOTE: 192.168.66.179>
1> Obj: B:\build_test_fb_x64\libA\h.obj <LOCAL>
1> Obj: B:\build_test_fb_x64\libA\c.obj <LOCAL RACE>
1> DLL: B:\build_test_fb_x64\libA64d.dll
FBuild: OK: all
Time: 1.693s

G:\dev\src\fastbuild\testproject>fbuild -clean -j1
1> Obj: B:\build_test_fb_x64\libA\libAPCH.pch
1> Obj: B:\build_test_fb_x64\libA\e.obj
1> Obj: B:\build_test_fb_x64\libA\a.obj
1> Obj: B:\build_test_fb_x64\libA\g.obj
1> Obj: B:\build_test_fb_x64\libA\b.obj
1> Obj: B:\build_test_fb_x64\libA\d.obj
1> Obj: B:\build_test_fb_x64\libA\f.obj
1> Obj: B:\build_test_fb_x64\libA\h.obj
1> Obj: B:\build_test_fb_x64\libA\c.obj
1> DLL: B:\build_test_fb_x64\libA64d.dll
FBuild: OK: all
Time: 0.817s
```
[testproject.zip](https://github.com/fastbuild/fastbuild/files/619520/testproject.zip)

**Comment by ffulin** [comment]
There are several factors that likely explain what you are seeing here. Some combination (or all) of the following is certainly at play:
 - How FASTBuild handles precompiled headers/distribution
 - Limiting local host to once CPU core
 - Artificial cpp files
 - Small build

I'll go into all these in a bit of detail below.  But to answer your primary question:

> Is that really supported?

The answer is certainly yes. I have actively used precompiled headers with FASTBuild on several projects and am using it right now. It provides significant speedups, varying from project to project. My current project sees around 4x speedup purely from distributed compilation, which becomes ~8x when combined with caching.  If combining Unity, Distribution and Caching, it's possible to see compile time improvements as high as 20x or more.  I've seen projects go from literally 40+ minutes to 1 minute when everything is in place!

Let me know if I can better explain any of the following:

**Precompiled headers**
FASTBuild uses the compiler's preprocessor to flatten the code required for compilation. It then sends that proprocessed source to the remote machine for compilation. When precompiled headers are used (at least with MSVC), this preprocessing is not possible (you can't mix precompiled headers and preprocessed code). 

In order to support distributed compilation when using precompiled headers with MSVC, FASTBuild effectively disables use of the precompiled header on the remote machines. This overhead is usually compensated for by virtue of adding more distributed compilation resources. The break-even point depends on the code and the speed number of CPUs.

**Limiting local host to once CPU core**
In distributed compilation, the local machine is generally the primary bottleneck. With that in mind, limiting the local machine to 1 CPU core will significantly negatively impact the speed of distributed compilation. I presume for your test you did this because without it, it's likely the local machine ends up doing the work instead of waiting for the remote machine. This is expected/desireable behavior - the local machine will race remote machines for any remaining work if there is no other work to do.

**Artificial cpp files**
It seems you are using artificially generated cpp files. Given the overall timings you've reported, it seems there is very little code actually being compiled within each object file. With artificially small cpp files, the normally small overhead of distributed compilation becomes significant.  It it takes 50ms to compile a cpp file locally, that's likely less time than it takes to send and receive that data, negating any benefit of running in distributed mode.

**Small build/startup time**
It takes some time for the primary FASTBuild exe to discover and connect to the remote workers.  Depending on various factors, half a second or so can elapse before the first host is found. Naturally this is an area where some time has been spent optimizing to try to minimize this time (and perhaps more is possible), but with a build that normally takes 800ms locally, taking 100-500ms to discover/connect to the worker(s) becomes significant. (In the very first build the first connection will require syncing the compiler which also takes time, though I imagine you've run your test a few times so that's probably not a factor here)

**Comment by ffulin** [comment]
A couple of resource that might be useful in your testing:

A visual monitor for distributed compilation: https://github.com/fastbuild/fastbuild/issues/127. This is being incorporated directly into FASTBuild, but you can pull the current external git repo.

A way to artificially make test cpp files take (tunably) longer time to compile: https://randomascii.wordpress.com/2014/03/10/making-compiles-slow/

**Comment by haferburg** [comment]
Our main library consist of 1229 TUs, and it takes 2800 s CPU time to compile them (without -cache or -dist). The precompiled header takes about 9 s seconds to compile (Boost, Qt are the most expensive), so every single TU would take a hit about that big on the remote machines, even /MP doesn't mitigate this. So the average TU takes 2.25 s to compile, on a 4+4 core machine that's about 0.285 s real time on average. But because the precompiled header contents are included again and again, every TU now takes at least 9 more seconds to compile, right? So that would mean I need 9/0.285 = 32 workers only to break even, and even more to see any benefits? Even if the hit from not having a PCH is only half of that, that's more machines than I have/than what seems reasonable.

Of course unity builds would mitigate this effect because it reduces the number of TUs.

So I'm asking myself, how many workers do you typically use, and how long does your precompiled header take to compile? Do you still /FI the precompiled header, even without /Yu?

Another question is: How do you create the unity blobs? Do you manage them manually? Do you have a rule of thumb of how long a blob should take to compile, esp in relation to the PCH compile time? Do you try to balance the blob compile time? Maybe another strategy, e. g. group by includes?

Do you think it would be possible to preprocess without the precompiled header, copy PCH+precompiled.hpp to the worker, then include the hpp with /FI? In my case, the time it takes to copy that 122 MB PCH, even if it's 3 seconds, would easily be worth it.

**Comment by ffulin** [comment]
Thanks for the extra info.

> So that would mean I need 9/0.285 = 32 workers only to break even

Based on your numbers, my math comes out as follows. I'll break it down below, but let me know if I messed something up:

2800s CPU time / 1226 TUs = 2.28s each
2.28s + 9s = 11.28s
11.28s x 1226 TUs = 13829.28s CPU time
13829.28 / 2800 = 4.93

So from my numbers, you'd need 4 extra machines to break even in the worst case (it actually won't be as bad as that because the local machine will still use the PCH, so there's a 20% or so improvement, so you likely are closer to 3 extra machines)

Now this isn't great just to break even (your case is on the less ideal end of the spectrum for sure), but maybe you have enough machines in your pool to make it worthwhile?

> Of course unity builds would mitigate this effect

Unity builds will almost certainly give you the epic speedups you'd want. I haven't seen a case where they didn't help *at lot*. They will help even before you look at -dist or -cache and as you say will also make those work a lot better, particularly the -dist, as it will amortize the overheads.

> how many workers do you typically use, and how long does your precompiled header take to compile? 

One of my current projects uses a precompiled header for one of the main libray which takes around 15 seconds.  Each unity object in the library takes around 20 seconds and there are around 30 of them.  There are also a bunch of smaller libraries that use unity with no precompiled header as they compile the entire library in one unity file (so it's actually better to not have a PCH at all).

> Another question is: How do you create the unity blobs? 

FASTBuild's built in Unity() support (http://fastbuild.org/docs/functions/unity.html) by default will create one unity file for all the input/library. This is ideal for small libs, but for larger libs, a good rule of thumb is that you want to end up with 30-40 source cpp files per unity file.  So for your case, 1229/40 = 30 seems like a good place to start.  Once it's working, tuning based on compile time is often worth it - 20s per unity file is a good starting point.  Your other, smaller libs (if you have them) might be cool with just one unity file as is the case for my project.

**Comment by ffulin** [comment]
Closing old issues. Let me know if you need more info or want to investigate further and we can re-open if needed.
