### ISSUE TITLE
Build takes significantly longer with -cache

### ISSUE THREAD

**Issue by haferburg** [fastbuild/fastbuild#174]
Delete everything in build dir, then `fbuild` -> 5.148s

Delete everything in build dir, then `fbuild -cache` -> 17.751s

I then do `fbuild -clean -cache`, FBuild says `<CACHE>` after all the TUs -> 13.111s

Touch the PCH, then `fbuild -cache` -> 13.718s

So it always takes at least twice as long with `-cache`.

This is on Windows with VS 2010 x86_amd64. I'm building with /Z7, as the docs state. The cache dir is on the same physical drive (SSD) as the build directory.

When I build with /Zi, the hit from -cache is much more reasonable. Why is /Z7 necessary?

Please let me know what I can do to help debug this, and what information you need from me.

**Comment by ffulin** [comment]
It's hard to say from the information given, but certainly something seems off. Can you please provide some more information about the nature of the source code being generated? For example:
 - how many object files are there
 - is most time is being spent on the precompiled header or the object files
 - is there linking involved in your test and if so, what is the time spent on that
This info can be gained by running with -summary.

> When I build with /Zi, the hit from -cache is much more reasonable. Why is /Z7 necessary?

FASTBuild currently doesn't support caching for objects compiled with Zi, so setting the debug info to 7i is simply disabling caching.

**Comment by haferburg** [comment]
Thank you for your answer. Our application consists of a small library (which takes 8 s to build in VS 2010) and a big one (~7 minutes). For both libraries, it takes about twice as long to build when I enable -cache. Here I'm testing with the small one.

Without cache:
```
> fbuild -version
FASTBuild - v0.92 x64  - Copyright 2012-2016 Franta Fulin - http://www.fastbuild
.org

> fbuild -clean -summary scopiscore
--- Most Expensive ----------------------------------------------
Time (s)  Name:
2.344     B:\build_trunk_fb_x64\ScopisCore\ScopisCore.pch
2.138     B:\build_trunk_fb_x64\ScopisCore\LogManager.obj
2.069     B:\build_trunk_fb_x64\ScopisCore\RenderHints.obj
1.803     B:\build_trunk_fb_x64\ScopisCore\InjectionContainer.obj
1.709     B:\build_trunk_fb_x64\ScopisCore\Constants2.obj
1.341     B:\build_trunk_fb_x64\ScopisCore\PolynomialDistortionParameter.obj
--- Summary -----------------------------------------------------
                                 /----- Cache -----\
Build:          Seen    Built   Hit     Miss    Store   CPU
 - File       : 1453    62      -       -       -       0.000s
 - Object     : 38      38      -       -       -       20.964s
 - Alias      : 1       1       -       -       -       0.000s
 - Compiler   : 1       1       -       -       -       0.000s
 - DLL        : 1       1       -       -       -       0.905s
 - ObjectList : 1       1       -       -       -       0.000s
Cache:
 - Hits       : 0 (0.0 %)
 - Misses     : 0
 - Stores     : 0
Time:
 - Real       : 6.459s
 - Local CPU  : 21.869s (3.4:1)
 - Remote CPU : 0.000s (0.0:1)
-----------------------------------------------------------------
FBuild: OK: scopiscore
Time: 6.651s
```

With cache:
```
> fbuild -clean -cache -summary scopiscore
--- Most Expensive ----------------------------------------------
Time (s)  Name:
7.074     B:\build_trunk_fb_x64\ScopisCore\LogManager.obj
6.507     B:\build_trunk_fb_x64\ScopisCore\PolynomialDistortionParameter.obj
5.552     B:\build_trunk_fb_x64\ScopisCore\Constants2.obj
5.227     B:\build_trunk_fb_x64\ScopisCore\RenderHints.obj
4.699     B:\build_trunk_fb_x64\ScopisCore\Line3.obj
--- Summary -----------------------------------------------------
                                 /----- Cache -----\
Build:          Seen    Built   Hit     Miss    Store   CPU
 - File       : 1453    62      -       -       -       0.000s
 - Object     : 38      38      0       38      38      2m 1.980s
 - Alias      : 1       1       -       -       -       0.000s
 - Compiler   : 1       1       -       -       -       0.000s
 - DLL        : 1       1       -       -       -       0.614s
 - ObjectList : 1       1       -       -       -       0.000s
Cache:
 - Hits       : 0 (0.0 %)
 - Misses     : 38
 - Stores     : 38
Time:
 - Real       : 19.344s
 - Local CPU  : 2m 2.594s (6.3:1)
 - Remote CPU : 0.000s (0.0:1)
-----------------------------------------------------------------
FBuild: OK: scopiscore
Time: 19.351s
```

Touch the precompiled header .hpp file to trigger a rebuild (is that a good test?):
```
> fbuild -cache -summary scopiscore
1> Obj: B:\build_trunk_fb_x64\ScopisCore\ScopisCore.pch
1> Obj: B:\build_trunk_fb_x64\ScopisCore\ScopisCore.pch <CACHE>
...
--- Most Expensive ----------------------------------------------
Time (s)  Name:
3.254     B:\build_trunk_fb_x64\ScopisCore\Constants2.obj
3.170     B:\build_trunk_fb_x64\ScopisCore\LogManager.obj
2.977     B:\build_trunk_fb_x64\ScopisCore\PolynomialDistortionParameter.obj
2.729     B:\build_trunk_fb_x64\ScopisCore\Line3.obj
2.705     B:\build_trunk_fb_x64\ScopisCore\Observables.obj
--- Summary -----------------------------------------------------
                                 /----- Cache -----\
Build:          Seen    Built   Hit     Miss    Store   CPU
 - File       : 1453    62      -       -       -       0.000s
 - Object     : 38      0       38      0       0       1m 27.629s
 - Alias      : 1       1       -       -       -       0.000s
 - Compiler   : 1       0       -       -       -       0.000s
 - DLL        : 1       1       -       -       -       0.277s
 - ObjectList : 1       1       -       -       -       0.000s
Cache:
 - Hits       : 38 (100.0 %)
 - Misses     : 0
 - Stores     : 0
Time:
 - Real       : 13.070s
 - Local CPU  : 1m 27.906s (6.7:1)
 - Remote CPU : 0.000s (0.0:1)
-----------------------------------------------------------------
FBuild: OK: scopiscore
Time: 13.084s
```

```
G:\dev\src\fastbuild>dir  B:\build_trunk_fb_x64\ScopisCore /O-S
 Volume in drive B is g
 Volume Serial Number is E60B-C991

 Directory of B:\build_trunk_fb_x64\ScopisCore

05.12.2016  10:44        44.695.552 ScopisCore.pch
05.12.2016  10:44         6.353.781 InjectionContainer.obj
05.12.2016  10:44         5.718.502 RenderHints.obj
05.12.2016  10:44         4.733.524 PolynomialDistortionParameter.obj
05.12.2016  10:44         4.618.737 Line3.obj
05.12.2016  10:44         2.831.485 LogManager.obj
```

The .CompilerOptions is 3570 characters long, could that be a problem?

**Comment by ffulin** [comment]
Thanks for the more detailed numbers.  That's very strange to see a single object be so much more expensive (2x+). Let's focus on a single object and see if we can get some more detailed timing info.

If you can run the following commands:
```C++
fbuild -verbose B:\build_trunk_fb_x64\ScopisCore\PolynomialDistortionParameter.obj -clean
fbuild -verbose B:\build_trunk_fb_x64\ScopisCore\PolynomialDistortionParameter.obj -clean -cachewrite
fbuild -verbose B:\build_trunk_fb_x64\ScopisCore\PolynomialDistortionParameter.obj -clean -cacheread
```
That will give us some slightly finer grained info, like the time it takes to hash/store/retrieve from the cache. 

Possible causes of slowness I can think of:
 - SSD not as fast as we'd like (IO bound)
 - Antivirus
 - VS2010, particularly the preprocessor speed (it's at least 2x faster in 2013 or later)

The additional info above might help steer our inquiries.

(The compiler options length should not be a problem at all)

**Comment by yass007** [comment]
Just a wild guess here but could the difference be that with caching enabled the compilation is not using the pch output which means that it's not able to benefit from the boost this provides on a local machine ?

Looking briefly at the code this theory doesn't seem possible since compiling a local job will discard the preprocessed ouput and keep going with the PCH flags (on MSVC)...

Yeah looking at the exact compiler flags with the verbose options above will help confirm this.
Also by using the FB visual monitor you be able to see how much time was spent during the preprocessing step, the IO and CPU loads.

**Comment by ffulin** [comment]
A while ago caching used to disable precompiled headers, but that hasn't been the case since v0.91 (that was the massive performance improvement of caching in v0.91). Everything from the logs so far indicates that it's working correctly (except for the slowness of course).

What I generally expect is that -cachewrite is ~10% more expensive than the "normal" compile. -cache read should be significantly faster than the "normal" compile when retrieving from the cache.

The 2010 compiler is known to be very slow compared to more recent versions, but the numbers we're seeing here are slower than anything I've seen, so it's entirely possible multiple things are at play.

(Good idea about using the monitor as another way to get more info on this problem)

**Comment by haferburg** [comment]
Franta, I ran the tests that you suggested. I'll send the log as an email to fastbuild@fastbuild.org. I ran it on a different machine so the numbers are different.

What I noticed is that when using `-cache` it compiles an additional time with `/E`, probably to compute a hash. There are no separate timings for the compile steps even with `-verbose`, but it seems that this is the reason why it's so slow. When I run the compiler commands manually (piping output into files) it takes about as long as `-cache*`.

That is also the reason why `-dist` doesn't work for us (https://github.com/fastbuild/fastbuild/issues/173). `/E` is so slow that the main machine can't provide work fast enough for the workers, even on the small library that has a smaller PCH. I tested with 6 workers, and the main machine can't even keep one worker busy.

So `/E` is way too slow. What can we do? Would it be significantly faster with a VS version newer than VS10?

**Comment by ffulin** [comment]
I took a a look at the log you sent (thanks!). It confirms my theory that the cost is associated with the preprocessor. In your case it appears to be a combination of:
- unfavourable pch to obj file code size (lost of small object files)
- slow preprocessor with VS2010 (/E)
- caching flattening the PCH into the object for use by the cache multiplying the above issues

Here's what I think we should do (in order):

**a) Activate Unity**
The best option is to enable the use of Unity. This will tilt the unfavorable pch to object file ratio massively. It will reduce by 20x or more the preprocessor overheads we are seeing.  It will also effectively provide PCH-style acceleration for headers within the library not covered by the pch. This alone will probably be enough to fix this problem. (It has some nice link-time side-effects which you'll eventually reap later on as well).

You should be able to verify seeing the expected speedups very quickly if you apply this to your smaller library first before diving too deep into it. Let me know if you need some help configuring this.

**b) Upgrade your compiler**
VS2010 is pretty old and later versions of VS have in general faster compilation and linking as well as faster preprocessing.  I think this would be worth updating even if you weren't using FASTBuild. Lowering the preprocessor cost will help FASTBuild in all caching and distribution scenarios.  It will further accelerate the Unity case. Express editions are free (even for commercial use), so the only downside is potential code changes due to new std libraries etc.

Before committing to an upgrade, you could verify the preprocessor speedups with your actual code pretty easily (to confirm how much we can expect it to help before going too nuts). If you preprocess one object file on the cmd line with 2010 (using the FASTBuild -showcmds option to get the /E cmd line) and then target the new version cl.exe with the same command line) we should have a good idea of what to expect.

If for some reason upgrading the compiler is not possible there is another interesting option: FASTBuild can use the pre-processor from one version while still using the compiler of another. A full upgrade is of course desirable anyway, but this could be an option since upgrading from VS2010 might be painful.

To give you an idea of relative performance I've seen to date, I dug out an old test script (updated it for the incoming 2017) and ran it on some real-world code I have:

![preprocessorspeed](https://cloud.githubusercontent.com/assets/11589403/21364028/ec5b40fc-c6a3-11e6-8436-51e3e9924097.png)

**Comment by dummyunit** [comment]
> FASTBuild can use the pre-processor from one version while still using the compiler of another.

I would strongly recommend against doing that. Different version of the compiler will have different set of predefined macros (at least `_MSC_VER` and `_MSC_FULL_VER`). This, for example, will break checks for compiler features found in many libraries.

**Comment by ffulin** [comment]
> I would strongly recommend against doing that. Different version of the compiler will have different set of predefined macros (at least _MSC_VER and _MSC_FULL_VER). 

This is a good gotcha to call out. Some care needs to be taken if compiling code that relies on _MSC_VER - you can overcome this problem though my manually defining it to the desired version using the /D command line option.

**Comment by ffulin** [comment]
I'm going to close this issue as there doesn't seem to be anything actionable on my end. Let me know if you want to investigate anything further, or if there is anything to be done on the FASTBuild side and we can re-open or create a new issue as needed.

**Comment by fran6co** [comment]
I had this issue as well and it was fixed by using light cache with MSVC

**Comment by ffulin** [comment]
The LightCache is certainly much more performant (an order of mangnitude is not uncommon), but the feature is still in experimental as of v0.99, so take care :)
