### ISSUE TITLE
fastbuild with precompiled headers

### ISSUE THREAD

**Issue by TomKuhn** [fastbuild/fastbuild#179]
We are trying to use fast build to cache obj files and also use distributed compilation.
In all cases we are using MSVC and VS2015 with a project that contains precompiled headers.

a.	What is PCHOptions for? What’s different between that and CompilerOptions within an ObjectList() block?
b.	Do precompiled headers get disabled (i.e. when Yu/Yc/Fp are passed in as CompilerOptions) as soon as you enabled distribution or caching, even when building locally? It does appear to be the case, as caching requires the pre-processor to run to calculate the hash.
c.	Caching does not seem to work unless every machine doing the build has an identical workspace, e.g d:\project vs c:\project on another machine, as full paths are used in the data that is hashed (pre-processed flattened source, compiler options etc)
d.	When a pre-process step is used (/E appended to cl.exe args) /Yu seems to get stripped out during the compile, but left in during the pre-process step. What does this cause the compiler to do? Use precompiled headers and run the pre-processor seems to be an unsupported workflow
e.	Is it correct to supply PCHOptions to create a pch in the ObjectList block that creates the precompiled header, and PCHOptions to use a pch in the Object list blocks that use the header? Because it seems from the code if you supply PCHOptions then you also need to supply PCHInputFile and PCHOutputFile or else you get an error. Why do I need to supply PCHOutputFile on a step that *uses* a precompiled header? In fact if we have more than one file using a PCH then fastbuild throws an error saying the PCH node is already defined.
f.	Incredibuild (our current solution) is quite happy about generating a PCH file locally and then sending it to a remote machine for compilation (even though every documentation I can find says do not do this) – I assume fastbuild never does this?
g.    We have noticed that there is a difference when linking object files that have been created without precompiled headers and ones that have been created with. i.e. when the source is flattened and compiled - the linker takes over 15 mins and then crashes with an out of memory. When we use precompiled headers, the linker completes in 4 mins. We were wondering if there was a different in the obj output from the compiler when PCH/non PCH is used.

I appreciate some of these questions have been asked before in the issues section but I wanted to keep them all together!

Thanks in advance

Tom

**Comment by ffulin** [comment]
Hello. I've tried to answer your questions below. Let me know if I can provide some more info!

> a. What is PCHOptions for? What’s different between that and CompilerOptions within an ObjectList() block?

.CompilerOptions is used to set the compiler options to use when compiling an object file which consumes the precompiled header, while .PCHOptions is used when compiling the precompiled header itself.  With MSVC, this allows for the different options such as /Yu and /Yc to be set appropriately.

For example:
```C++
Library( 'MyLib' )
{
    .CommonOptions = '/Z7 /nologo /c /W4 /WX'

    // Precompiled Header Creation
    .PCHInputFile               = '$ProjectPath$/$PCHName$.cpp'
    .PCHOutputFile              = '$OutputBase$/$ProjectName$/$PCHName$.pch'
    .PCHOptions                 = '"%1" $CommonOptions$ /Yc"$ProjectPath$/$PCHName$.h"'

    // Precompiled Header Use
    .CompilerOptions            = '"%1" $CommonOptions$ /Yu"$ProjectPath$/$PCHName$.h" /Fp"$PCHOutputFile$"'
            ...
```
> b. Do precompiled headers get disabled ... as soon as you enabled distribution or caching, even when building locally? 

FASTBuild will flatten the objects using the pre-processor for distribution to remote machines. When compiled remotely, the PCH will be disabled. When compiling locally (whether using the cache or not), the PCH will still be used.

> c. Caching does not seem to work unless every machine doing the build has an identical workspace, e.g d:\project vs c:\project on another machine

That's correct. This is a limitation imposed by the compiler because it embeds paths in the object files for at least the following things:
a) Debug info
b) __FILE__
If FASTBuild didn't consider the path in the cache lookup, you could have a situation where debug info didn't work correctly (in the a) case) or worse, the code was just wrong (imagine sizeof(__FILE__) in the b) case).

> d. When a pre-process step is used (/E appended to cl.exe args) /Yu seems to get stripped out during the compile, but left in during the pre-process step.

/Yu is stripped during the remote compile as noted above (in a)).  It's left in during the local pre-processing as it's simply ignored by the compiler (no need to be stripped, though it could be).

> e. Why do I need to supply PCHOutputFile on a step that uses a precompiled header? In fact if we have more than one file using a PCH then fastbuild throws an error saying the PCH node is already defined.

PCHOutput file specifies the file which will be generated when compiling the precompiled header file (the .pch in the case of MSVC). You can only define a precompiled header once.  Typically, you cannot share a precompiled header across multiple libraries. You also generally cannot have different compiler settings between objects using a precompiled header, so typically you want one ObjectList or Library per precompiled header.
What is the case you have that requires multiple users of a single precompiled header? If you can provide some more details, we can work out what to do.

> f. Incredibuild (our current solution) is quite happy about generating a PCH file locally and then sending it to a remote machine for compilation (even though every documentation I can find says do not do this) – I assume fastbuild never does this?

Some time ago, precompiled headers (for the MS compiler) were machine-specific. i.e. they were a literally memory-mapped in some cases so sending to a remote machine was not reliable.  For some time now (several VS versions at least), this hasn't been the case, so precompiled headers can be sent and used on other machines.

However, precompiled headers cannot be used when compiling preprocessed code. Technically it does work (I have had a prototype working), but it results in double macro expansion and so cannot be safely used. In order to fix this, FASTBuild would need to do its own preprocessing (flatten includes but not expand macros) instead of using the compiler. This is something that may happen in the very long term, but it's a non-trivial undertaking!

Incredibuild's distribution (as far as I understand it) virtualizes the filesystem on the remote machine, so that it avoids this issue.

g. We have noticed that there is a difference when linking object files that have been created without precompiled headers and ones that have been created with.

Objects built remotely are larger if they use precompiled headers. The linker must do extra work to collapse these together. The cost of this overhead can vary a lot depending on the project. Your numbers are at the worse end of the scale for sure.

There are a few things that can be done to help mitigate this which are worth trying (I'll list them all for completeness, but a) is your best bet):
**a) Use Unity.** This is by far the single biggest speedup possible. In addition to the massive local speedups this provides, it can greatly re-balance the PCH to object file ratio, greatly reducing the work the linker must do. This single thing may be enough to resolve this issue, so I recommend trying it first.
**b) Try /Zi instead of /Z7 ** Z7 is typically faster to compile, but slower to link. In some extreme cases, the link-time hit can be massive. If you are using /Z7, try /Zi.  (Distributed compilation will still work, but caching will be disabled)
**c)Make sure you are linking via .lib files** If you are linking object files into your exe directly, try going via a lib.  The lib effectively does some of the work of symbol de-duplication, but can be parallelized and is effectively incremental (assuming you have multiple libraries).
**d)Experiment with /Gy, /OPT:REF and /OPT:ICF ** These compiler/linker options when working together strip unused code from the final exe/pdb, sometimes massively reducing link times. (Weirdly, in certain scenarios I've seen this **increase** link times, so it's also worth trying disabled!  It's also tyring REF and ICF individually!)

**Comment by dummyunit** [comment]
> Use Unity. This is by far the single biggest speedup possible.

This can't be stressed enough.

Just a couple of real examples from my job -- we use some external libraries, in particular live555 and libtorrent. Converting them to use unity builds sped-up compilation from 85s to just 3s (in case of live555, with 1 unity file, 1 core and `/O0`) and from 90s to 15s (in case of libtorrent, with 4 unity file, 4 cores and `/O0`).

**Comment by TomKuhn** [comment]
@ffulin thankyou for your response, I hope you had a good xmas.

Some more context: We use Unreal Engine. In order to interface between UnrealBuildTool and fastbuild, we use https://github.com/liamkf/Unreal_FASTBuild, which generates the bff file.

This doesn't seem to make any "lib" blocks/nodes at all, it just writes a flat load of 
ObjectList('Action_1') 
{
// make a pch
 .PCHOptions/PCHInput/PCHOutput etc
}
ObjectList('Action_2') 
{
// compile a cpp and pass /Yu and /Fp to the compiler with the location of the pch created by action 1
}
ObjectList('Action_3') 
{
// compile a cpp and pass /Yu and /Fp to the compiler with the location of the pch created by action 1
}
... etc etc etc

I'm not sure FastBuild is happy with this, although it does seem to generate the code and link it. Action_2 and Action_3 use a precompile header but fastbuild I think it's totally unaware of this due to there being no PCH node.

We are already using Unreal's unity builds where it groups a load of cpp files into one CU.

Because it's unreal - if we flatten one of our cpp files, it turns into over 600,000 lines of preprocessed output - just to find out the hash to see if the corresponding obj file is in the cache. This alone instantly adds 6 minutes of time to the build as it flattens each of our sourcefiles. 

Looking at the fastbuild code, it looks like maybe it's trying store a hash of the precompiled header as part of the cpp hash in the cache (the d part in a_b_c_d.v filename) so that it doesn't have to flatten the precompiled header when it's looking it up? I wasn't quite sure how that part was supposed to work - and as mentioned before I don't think we're using it properly as the cpp compile actions don't have a precompiled header node anyway!

Thanks

Tom

**Comment by ffulin** [comment]
The preprocessed files are hashed when the cache is active. This is part of the cache lookup.

In the case of precompiled headers, both the flattened precompiled header and the flattened code using the pch will be hashed. Both of these are needed for safe lookup into the cache, because the object file must match the exact precompiled header used to compile it (it is internally stamped somehow).

What this means is that if you are using a pch, but doing so without FASTBuild managing the dependency, the caching will be unsafe - i.e. you can get occassional build failures; specifically errors about the pch needding to be rebuilt.

**Comment by ffulin** [comment]
I'm going to close this issue. Feel free to re-open if you need more info.

**Comment by john-blackburn** [comment]
I've recently written a preprocessor library to deal with the problem described here. The preprocessor is written in C++ and doesn't use any external libraries so would be easy to incorporate into FASTBuild. You preprocess a file by calling a single function which then returns the post-processed code as a string or writes it to a file of your choice. As well as standard "full" compile, it also supports a "flatten" mode where only `#if` and `#include` are processed but macros are not expanded. I believe this library could be easily slotted into FASTBuild allowing it to use PCH on distributed computers. (and also giving it the native ability to preprocess without invoking the compiler) 

https://github.com/john-blackburn/preprocessor

**Comment by yhyu13** [comment]
@ffulin Building Our test in Unreal Engine 5 shows a full-rebuild with FASTBuild w/o PCH for remote job result in 3 times slower the compilation time in compare to no distribution, which renders distributed compiling futile. 

Moreover, local jobs cannot benefit from PCH when ```-dist``` is set because compilation units generated by remote worker, when later used locally, cannot apply PCH anymore. So as long as ```-dist``` is set, **both local and remote worker disables PCH effectively.**

Would it be on the schedule to see an integration with @john-blackburn's preprocessor into future release of FASTBuild? I believe it would be a big leap for FASTBuild adopation into UE5. Epic had some effecort in integrating with FB into UE4, but they abandoned it when moving to UE5, probably because of the PCH issue.

Also, another point to mention here is that ```-cache``` options are not really relavent to UE5. Because most of the time, a rebuild is triggered by a global macro change which effectively invalidate caches. So may be we can ignore caches when considering bringing PCH in a distributed manner in this case.

**Comment by ffulin** [comment]
@yhyu13 Distributed compilation comes with some overheads, depending on the nature of the code. For most codebases a single additional worker is enough to have a net positive, but heavy use of very large pre-compiled headers requires more workers to break even and start seeing gains. Several users of FASTBuild have seen massive speedups with FASTBuild using Unreal 4.xx. I'm not certain of usage with Unreal 5.

You haven't said what version of FASTBuild you are using but Unreal 4.xx ships with a very old version (several years old). Are you doing your tests with the lastest version (v1.07)? There have been significant improvements to essentially all aspects of build performance.

Apart from using an old version, there are many other factors that can impact performance include:
a) slow host (not fast enough to feed workers)
b) not enough workers or poor hardware
c) poor network speed or connectivity problems
d) security software

As an example, prior to v1.06 some users, particularly with Unreal were seeing lots of disconnections crippling builld performance.

If you use the most recent version of FASTBuild you can use the -profile feature to gain some insight into the bottlenecks and any problems that might be present in your setup. If you find some issues you'd like some help understanding, it'd probably be best to start up a new thread/issue.

**> Moreover, local jobs cannot benefit from PCH when -dist is set...**

While distributed jobs cannot use the PCH, local jobs can, whether distributed compilation is active or not.

**Would it be on the schedule to see an integration with @john-blackburn's preprocessor into future release of FASTBuild?**

John did some great work on this pre-processor, but unfortunately it's not possible to integrate into FASTBuild in its current state. As an example, it uses language features, memory allocation strategies and the C++ standard library, all of which are incompatible with FASTBuilds requirements. It would be a significant modification to the library to solve those issues and that would result in an unattractive maintenance burden. There are additionally licensing compatibility concerns.

The general idea (a light-weight partial pre-processor) is what is desired for FASTBuild, but an ideal implementation would be in FASTBuild itself. As well as alleviating the concerns above, it would allow for an entirely new level of optimization: to avoid redundant preprocessing between compilation units (in the same way the LightCache does today).

**> Epic had some effecort in integrating with FB into UE4, but they abandoned it when moving to UE5, probably because of the PCH issue.**

I don't believe this is the reason why integration stalled/was abandoned. I'm not sure how much of their plans are public so I won't provide any further details here.

**Also, another point to mention here is that -cache options are not really relavent to UE5.** 

The most common/useful scenario is to have your build machines populate a network backed cache to share compiled object files between developers and other build machines. Several titles using Unreal 4.xx are using caching it this way to great effect (order of magnitude speedups when syncing latest code for example). (This is the recommended setup for all users, Unreal or not)

The least useful scenario if pointing the cache at a local folder (not sharing between machines). There are cases where this can be useful, but it is rarely desirable.

A common gotcha is use of __TIME__ which is build determinism killer.

In any case, use of the cache is orthogonal to PCH use. If your use-case is such that no two machines ever build the same thing you can disable caching, even if that sound very surprising to me.

**Comment by yhyu13** [comment]
@ffulin I was building with v1.07, with 12th i7 + R95950X, pcei4.0 SSDs, 2.5G network network/card/switch/cat-6+ wire, etc. The hardware is competent enough, even better than my work machine. Still, a single machine with 32 logic cores could only strike a full editor re-build in 40mins which is not ideal to me. I would like to achieve what XGE offers in about 15mins with about 80 cores (with several other machines of my colleagues when they are free) at home. That's why I started experimenting with FASTBuild.

**PCH**
I did a test on a R9 5950X machine with -dist flag but was forced to send build jobs to a local FBuildworker (pretty much like -forceremote?) which result in the same time as compiling UE5 without using PCH (turning it off in the UBT build option), both were around 3 times slower than using no -dist with PCH enabled. All tests run with FASTBuild v1.07, and all CPU cores run at 100% all the time, so I think it is not a problem with the performance of FASTBuild or my hardware. 

It is obvious that PCH is the most important factor in terms of compiling in UE5 to me now. I tried forcing to not strip away /YU /FP for the local machine, but it resulted in compilation errors for compilation targets that use results from remote workers that were not using PCH.  

The PCHs for UE5 are mostly around 200MB big each, XGE uses the network to distribute them heavily, sometimes hitting the limit 1Gbs upload rate. I found flattened compilation target with a preprocessor does not utilize network that heavily and consumes more local compiler process memory and compiles slower.

I believe FASTBuild is excellent for distributing compiling gpu shaders, compressing textures, cooking art assets, etc. But just not compiling with PCH in a distributed manner, which is a bummer. My current strategy for homebrew development is to disable -dist flag only when compiling.

**Unity**
The Unity build (c++ files lumped together) is supported by UBT(UnrealBuildTool). FASTBuild simply executes what UBT has to feed. So Unity is enabled unless we turn it off via UBT. 

**Cache**
The thing with cache is that my use case for UE5 is to add/remove different global macros to enable/disable program features. They are very much different from time to time. This invalidates all previous caches effectively, and every source build of UE5 results in 20+GB of cache that can hardly be hit again. I believe the cache feature should be useful for other use cases

**Comment by ffulin** [comment]
Your hardware certainly seems decent. As a next step I'd recommend doing your build with -profile to get some better insight into what's going on. That might show something unexpected or provide some hints.

Additionally, I'd suggest building some specific objects **individually** to see how three scenarios compare:
 - local build only
 - local build with -dist
 - local build with -dist -forceremote

That should give you:
 - local build with pch
 - local build with pch after preprocessing and discarding preprocessed output
 - remote build without pch

Those can all be combined with -profile to see the scheduling and -showcmds to verify use of the pch (for the local tasks).
 
Another potential avenue of investigation would be to check the Unreal Build Tool integration you are using to make sure it isn't disabling precompiled headers for the local tasks in some situation. (As above can be checked with -showcmds)

To be clear: there is a world in the future where FASTBuild can use precompiled headers remotely, powered by a custom preprocessor, and there is likely a very large speedup to be had, but from what you've described so far, I think something else might be going on.
