### ISSUE TITLE
Using .PCHInputFile .PCHOutputFile .PCHOptions in ObjectList gives 1301 error

### ISSUE THREAD

**Issue by jafarsoltani** [fastbuild/fastbuild#182]
Hello,
I'm trying to setup an objectlist to generate obj file for a cpp file using precompiled headers. Should I be using .PCHInputFile .PCHOutputFile .PCHOptions ? If I use them then I get 1301 error. What's the purpose of setting those inside objectlist of a cpp as opposed to having a specific objectlist for pch files I'm intending to generate?
I'm using fbuild 0.92 with VS2015

**Comment by ffulin** [comment]
You need to set all 3 options in order to create a PCH file.  The ObjectList or Library you set them in is then expected to use that precompiled header.
In this way, the ObjectList or Library declares both how to build the PCH and how to use it.

The setup would look something like this:
For example:
```C++
Library( 'MyLib' )
{
    .CommonOptions = '/Z7 /nologo /c /W4 /WX'

    // Precompiled Header Creation
    .PCHInputFile               = '$ProjectPath$/$PCHName$.cpp'
    .PCHOutputFile              = '$OutputBase$/$ProjectName$/$PCHName$.pch'
    .PCHOptions                 = '"%1" $CommonOptions$ /Yc"$ProjectPath$/$PCHName$.h"'

    // Precompiled Header Use
    .CompilerOptions            = '"%1" $CommonOptions$ /Yu"$ProjectPath$/$PCHName$.h" /Fp"$PCHOutputFile$"'
            ...
```

I hope that answers your question. Let me know if I missed something or if you want some more info.

**Comment by jafarsoltani** [comment]
Thanks for your reply. My case is slightly different. The way I setup my bff file is I'm compiling pch in an objectlist and I have a few more objectlists that consume pch and eventually an Executable that links. However, it looks like I need to specify both PCHOptions and CompilerOptions (and CompilerOutputPath) in Objectlist for PCH otherwise I get 1101 error. It also seems like in my pch objectlist, CompilerOptions and PCHOptions are almost identical except PCHOptions has /yc and CompilerOptions has /yu. Is that correct?

**Comment by ffulin** [comment]
Currently an ObjectList can't define *only* a pch. It has to define something that consumes it as well. Are you able to change your setup to work that way?

Some combination of the following could be added to FASTBuild in the future to make this more flexible/easy/intuitive:
a) The ability for ObjectList to define only a PCH.
b) An explicit PrecompiledHeader() function
c) The ability for multiple ObjectList/Library to redundantly define the same PCH (as long as they define the same thing)

> PCHOptions are almost identical except PCHOptions has /yc and CompilerOptions has /yu. Is that correct?

Generally they are almost identical, especially since MSVC required most optimization and define settings match. With MSVC, /Yc and /Yu are typically the only options that are different. With other compilers, it is possible to have larger differences which could be useful in some build configurations).

**Comment by TheClassic** [comment]
Hopefully, I'm not threadjacking... I think what I'm experiencing is related to some functionality that ffulin is suggesting. I've come across some projects where individual files have compiler settings different than the rest of the project, specifically the Multiprocessor compilation (/Mp I think). I don't know how to set this up without creating two different object lists, however this leads to error #1301 due to the pch being specified in both object lists. Typically I resolve this by making the settings consistent and simplifying to a single objectlist, however I anticipate a case where this won't be possible. Is there a way of using precompiled headers with different compiler settings for a given library/project, or is this another vote for ffulin's ideas?

**Comment by ffulin** [comment]
If I'm understanding you correctly, it does sound like either of the 3 options I suggested would handle your use case as well.

**Comment by ffulin** [comment]
A change has been made (https://github.com/fastbuild/fastbuild/commit/4cd6eaf9061a98b676a0357ccd19cd62d8d101a8) which allows much greater flexibility for precompiled headers:
 - an ObjectList can be use a previously defined PCH
 - an ObjectList can defined only a PCH

This change will be in the next release (v1.00). I'll leave this issue open until that version is released.

**Comment by ffulin** [comment]
v1.00 has now been released. It includes the enhancements which allow much greater flexibility in PCH usage.
