### ISSUE TITLE
ObjectList possible regression in dev branch

### ISSUE THREAD

**Issue by poppolopoppo** [fastbuild/fastbuild#189]
Since 372b7ad58086d447af1e9ec77717ab70d6d6cf58 the following BFF will fail despite being accepted by previous versions :
````
ObjectList( 'test' )
{
    .Compiler = 'cl.exe'
    .CompilerOptions = '-c %1 %2'
    .CompilerOutputPath = 'Output'
    .PreprocessorOptions = ''
}
````
With this error message :
````
FASTBuild Error #1004 - ObjectList() - Empty string not allowed for property '.PreprocessorOptions'.
ObjectList( 'test' )
^
\--here
````
ObjectListNode should still handle this empty string nicely though :
````cpp
CompilerNode * ObjectListNode::GetPreprocessor() const
{
    // Do we have a preprocessor?
    if ( m_PreprocessorOptions.IsEmpty() )
    {
        return nullptr;
    }
   [...]
}
````

Was this intended ?

Thanks !

**Comment by ffulin** [comment]
My thinking historically was that if something was being set, then setting it to an empty string would raise an error, since that was most likely an error. The logic being that if you didn't want it set, you just wouldn't set it.

With the refactoring that is currently underway, a lot more consistency is being introduced into how this sort of thing is handled across different functions exposed to the bff. It seems like this is a case where this was actually "wrong" before, but is now behaving consitently.

Having said all that, I've actually been thinking about changing this behaviour, so that if a property is optional, you can set it to an empty string with no ill-effect. The idea is that this increases flexibility (you could define something globally while still being able to disable it in a more confined scope.

Let me know what you think.

**Comment by poppolopoppo** [comment]
Thanks for you explanations,
I am exactly in the case which you described :)

I am defining `.PreprocessorOptions` to an empty string early in my BFF, so that every other client can append to it. So considering optional properties as valid when they're empty totally suits me, and  like you said this is generally more flexible.

**Comment by ffulin** [comment]
I've made the change to allow properties to be set to empty strings if they are optional (https://github.com/fastbuild/fastbuild/commit/5f4f7448022efe08e6c5d90ac03ef0f08e67b6a7). This change will be in the next release (v0.93). I'll keep this issue open until that version is released.

**Comment by poppolopoppo** [comment]
Thanks, it's working again :)
