### ISSUE TITLE
Alternate TMP directory on worker machine not working

### ISSUE THREAD

**Issue by gkoreman** [fastbuild/fastbuild#194]
If a remote worker has set their TMP directory to something non-standard then fastbuild fails.

A few of our users moved their tmp directory to a secondary drive in order to free up space on their C: but this caused their remote workers to continuously fail.

Here is an example excerpt from a log:
PROBLEM: C:\Users\gkoreman\AppData\Local\Temp\UnrealShaderWorkingDir\263F66F64CCD23C0AEAEC0845284E7B5\FASTBuild\0\66\Worker.out
build	14-Jan-2017 13:20:44	UE4Editor-Cmd: Failed to build Object (error 0xc0000005) 'D:\TMP\.fbuild.tmp\0x00000000\core_1003\Worker.out'

On FASTBuild Workers that have standard TMP folders this issue does not occur.

**Comment by ffulin** [comment]
FASTBuild queries the OS to get the Temp dir. On Windows this is done via the GetTempPath() function which supposedly always returns a \ terminated string. However, in your output, it seems the string is missing the trailing slash, so when we concatenate the paths, we end up with:
```C++ 'D:\TMP.fbuild.tmp\0x00000000\core_1003\Worker.out' ```
instead of:
```C++ 'D:\TMP\.fbuild.tmp\0x00000000\core_1003\Worker.out' ```

Perhaps the MSDN documentation is wrong about the trailing slash. If so, that should be easy enough to fix :)

Could you please confirm for me the value of the TMP and TEMP environment variables on one of your remote machines - i.e. do they have a trailing slash or not? That will help ensure I can repro the exact case you have.

**Comment by gkoreman** [comment]
Unfortunately all of the machines have been changed back. I may be able to
get someone to reproduce it next week.

**Comment by ffulin** [comment]
Since I don't have a good repro for this, I can't really fix this. I've checked the source code to make sure that any place we get TMP directly via the env var is not assuming anything about the trailing slash, and there is only one place we do that and the code only forwards the env var.

With that in mind, I'm going to close this issue for now. If we get a repro case, we can re-open this and create a targeted fix (no problem making FASTBuild add a slash if missing if I know where it's going wrong :) ).

**Comment by PhilipSoDisguise** [comment]
Hi, I have same issue as this I believe
my server D: drive has died and I moved the Fbuildworker.exe to C:
it shows like this:

![Image](https://github.com/user-attachments/assets/2df2bf5a-8d7b-4ec3-b7a7-7176836456c0)

I tried look into registry / environment variable and no luck
download a different version with no luck
run from various different folder in C: with no luck

how can I resolve this?
