### ISSUE TITLE
only trigger associated node rebuild  when env var changed

### ISSUE THREAD

**Issue by comicfans** [fastbuild/fastbuild#203]
I've found NodeGraph treats LIB env var change as OK_BFF_CHANGED, but accoding to 
https://msdn.microsoft.com/en-us/library/6y6t9esh.aspx
LIB env var only affect linker behavoir (and only apply to MSVC toolchain), can we only marks linker node as out of date ? 
also  there're more env var can affect compile lib or link 
https://msdn.microsoft.com/en-us/library/kezkeayy.aspx
https://gcc.gnu.org/onlinedocs/gcc/Environment-Variables.html
so I think a better soluation may be introduce a "EnvNode" , and let associated compile/link/lib node depends on them, so we can trigger less (and more correct) node when these env var changed.
this env var dependency can also extend to support ExecNode , so fbuild can tell if ExecNode needs to rebuild if it depends on user specified env vars.

**Comment by Leandros** [comment]
You can counter that by simply manually importing the environment variable. See this ticket for further information: https://github.com/fastbuild/fastbuild/issues/172

**Comment by comicfans** [comment]
I think this can be improved .  manually import environment variable can achieve this but not best,   it trigger more work than needed.

**Comment by ffulin** [comment]
Changes to the LIB environment variable are considered part of the build configuration because the linker behaviour is impacted by the env var and FASTBuild must re-evaluate where the libs come from in order to correctly track dependencies.  This is currently done at parse time instead of build time, because there isn't a good mechanism to trigger the node as "dirty" due to an env variable change.

FASTBuild needs a general mechanism to rebuild only the things that change rather than triggering a rebuild. That work is underway. Some background is described here: https://github.com/fastbuild/fastbuild/issues/108

When that general work is done, this issue should also be addressed.  i.e. the config would still be re-parsed when the env var changes, but only the affected nodes would be "dirtied" instead of the whole DB.

**Comment by ffulin** [comment]
v0.99 has been released which includes a feature that migrates the dependency database when a bff is re-parsed (either due to edits or environment variables changing). When the LIB environment variable changes, dependencies for the linker will be re-evaluated and linking should reoccur only if needed.
