### ISSUE TITLE
/ShowIncludes and /P /Fi cl.exe flags

### ISSUE THREAD

**Issue by poppolopoppo** [fastbuild/fastbuild#24]
Hi,

I need to call the preprocessor in my build chain. For that I use an ObjectList() with my compiler and just add '/P /Fi "%2"' to _.CompilerOptions_, which causes cl.exe to [write preprocessor output](https://msdn.microsoft.com/en-us/library/ee207218.aspx) to %2.

This fits in nicely in theory, but I got an access violation when running it. With a debugger I found the crash in ObjectNode::ProcessIncludesMSCL(), dereferencing output which was null. This is only asserted and not handled :
````cpp
// FBuild\FBuildCore\Graph\ObjectNode.cpp(437)
// ProcessIncludesMSCL
//------------------------------------------------------------------------------
bool ObjectNode::ProcessIncludesMSCL( const char * output, uint32_t outputSize )
{
	Timer t;

	{
		ASSERT( output && outputSize );

		CIncludeParser parser;
		bool result = parser.ParseMSCL_Output( output, outputSize );
		if ( result == false )
		{
			FLOG_ERROR( "Failed to process includes for '%s'", GetName().Get() );
			return false;
		}
````
Called from here :
````cpp
    // FBuild\FBuildCore\Graph\ObjectNode.cpp(247)
	// compiled ok, try to extract includes
	if ( ProcessIncludesMSCL( ch.GetOut().Get(), ch.GetOutSize() ) == false )
	{
		return NODE_RESULT_FAILED; // ProcessIncludesMSCL will have emitted an error
	}
````

The problem seems to come from the /ShowIncludes flag of cl.exe. [On the MSDN](https://msdn.microsoft.com/en-us/library/hdkef6tk.aspx) we can read :
> The /showIncludes option emits to **stderr**, not **stdout**.

For some obscure reason this is not the case when calling cl.exe with "/c %1 /Fo %2" or even by adding "/E" or "/EP", in those cases -and in fact most of the time- the output is written on **stdout**.
But when I add "/P /Fi" then /ShowIncludes will write on **stderr**, stdout will be empty and ch.GetOutput() will return nullptr.

**Comment by ffulin** [comment]
As you pointed out, /showIncludes seems to go to stdout.  I'm very surprised to see the documentation say otherwise!

We could fix this problem in two ways:

**Option A - Emulate /Fi**
 - detect and note the /Fi flag
 - remove the /Fi and fo normal /E preprocessing (same as if we were using the cache or distribution), so FASTBuild captures the output and does pre-processing as normal
 - have FASTBuild write the output to the file specified in /Fi to retain the same overall behaviour
 - note that we only want to do preprocessing, and don't do the second phase of compilation (similarly disable the case and distribution)

**Option B - Respect /Fi**
 - detect the /Fi flag
 - disable caching/distribution
 - go through a special path (like compile other)
 - pass the stderr /showIncludes output to the MSVC function

I think in either case we'd definitely want to extend the unit tests to cover this if support was added.

**Comment by poppolopoppo** [comment]
I am testing a patch for solution B), it seems to be working well.

https://github.com/poppolopoppo/fastbuild/commit/9cbbbea097c48f7f303509137f9e7a6d1b8b75e2

**Comment by ffulin** [comment]
Looks good so far.

**Comment by ffulin** [comment]
A fix for this (use of /P with or without /Fi) has been integrated into the Perforce mainline and will be part of the next release (v0.84).

Fix is a derivation of: https://github.com/fastbuild/fastbuild/pull/34

**Comment by ffulin** [comment]
v0.84 has now been released.  Closing this issue.
