### ISSUE TITLE
[New User]Fbuildworker firewall blocked

### ISSUE THREAD

**Issue by ajeet-virus-bit** [fastbuild/fastbuild#246]
Hi Experts,

When I started executing FBuildWorker in my machine, a popup came saying that firewall blocked some of the feature of the programme. 

What I need to do here, can you please help me here?

**Comment by ffulin** [comment]
The FBuildWorker listens on the network in order to be able to distributed compilation for other machines on your network. If you want that, you'll need to add an exception to your firewall rules. How you do that depends on which firewall you are using. If you are using the build in Windows Firewall, pressing the Allow Access button the first time should keep it working from that point onwards. (It might be necessary to re-allow future versions when you upgrade).

**Comment by ffulin** [comment]
If you need it, the information regarding which ports are used by FASTBuild's distributed compilation can be found here: http://fastbuild.org/docs/troubleshooting/distribution.html

**Comment by ffulin** [comment]
Are you ok to close this issue?  Do you have the information you need?
