### ISSUE TITLE
Distributed Build Performance Issue under Low-Bandwidth Network

### ISSUE THREAD

**Issue by hillin** [fastbuild/fastbuild#248]
In a low bandwidth network (say, 100 Mbps Ethernet), distributed build is drastically slow, even slower than non-distributed build. 
I've made a test, to build the source code of Unreal Engine 4.15:

### Test Environment
- CPU: Intel Core i7-4790 (3.6 GHz, 4 cores, 8 threads). All agents use the same CPU model
- RAM: 32 GB
- Hard Drive: TOSHIBA Q300 SSD
- Windows 10 v1703
- Visual Studio 2017 with VS2015 Toolchain
- Unreal Engine 4.15 (NVIDIA VRWorks variant), in *Development Editor Win64* configuration.
- FASTBuild: 9 workers, with maximally 38 distributed threads. Caching turned off
- IncrediBuild: 13 agents, with maximally 50 distributed threads
### Test Result

| | Network | Time (minutes) | |
|------------|-----------|----:|-------------------|
|Non-distributed | | 32.3 |████████████████░
|IncrediBuild | 100 Mbps | 13.6 |██████▓
|IncrediBuild | 1 Gbps | 9.8 |█████
|FASTBuild | 100 Mbps | 43.5 |█████████████████████▓
|FASTBuild | 1 Gbps | 14.4 |███████░
|FASTBuild | cache all hit | 6.5 |███▒

**Comment by ffulin** [comment]
FASTBuild and Incredibuild manage their distributed compilation quite differently. Because of the way FASTBuild works, it requires significant network bandwidth compared to Incredibuild for the same source code. Over a Gigabit network, this is generally not a problem, and FASTBuild distributed compilation has been mostly tuned with a gigabit network in mind. Over 100 Mbps network, particularly with a large code base like Unreal, it's highly likely the workers are starved for data. (This seems to fit with the massive speed increase you see when half your workers switch to Gigabit).

Additionally, I recently noticed that FASTBuild was timing our connections very aggressively, which in network bound scenarios would cause connections to be frequently dropped. A fix for this (https://github.com/fastbuild/fastbuild/commit/5252c74d82bcef496d550171c3a3e29eb3d399c7) will be in the next release (v0.94). It's pretty likely this fix will have a significant for 100 Mbps network connections. If you are in a position to build the dev branch, you could try this before that version is released.

Assuming you can't just switch everyone to Gigabit connections :), what you might like to do in the short term is only run the workers on the gigabit machines.  That won't improve the situation for  your 100 Mbps users, but would potentially improve it for the 1 Gbps users (since the 100 Mbps connections are likely just using bandwidth for the 1 Gbps users, but just causing dropping connections and getting no useful work done). With this in mind, it would be super interesting if you were able to do your test with just the 1Gbps connections (i.e. just remove the 100 Mbps connections). Even if it's less workers than your mixed test, it's possible you'll see improved overall performance.

Let me know what you think.

**Comment by hillin** [comment]
@ffulin thank you for the explanation. It's a shame our new office only have 100 Mbps intranet connections by default, and for now all we can get is a 8 port gigabit switch.
Some more thoughts:
- Since we have **local race** threads, why is it so much slower while comparing 100 Mbps distributed build with non-distributed build? It's reasonable there could be an overhead for distributed build, but here we are talking about 25% more slower.
- What's the difference between FASTBuild and IncrediBuild, in term of network handling? I mean, it shouldn't be too costly if we just send out source code files and receive the yield, right? If it's because FASTBuild also delivers the entire toolchain, is it possible implement a *lightweight* mode to reuse the existing toolchain on worker machines, if they already have? For example, the host (the one who is initiating the build) could broadcast a manifest of all the required files, like the compiler program, SDK etc., and only transfer the files to those who can't resolve.

**Comment by ffulin** [comment]
A distributed build with no workers incurs some local overhead because FASTBuild uses the preprocessor locally to prepare the work to be remotely compiled. It varies by codebase and compiler, but 20% is not unheard of. My theory is that with a 100 Mbps network, the network is so slow that the overhead isn't compensated for, particularly if the keep-alive timeout was too short and it was potentially dropping and reconnecting so frequently. i.e.you may have been getting almost or literally zero benefit from distribution, but still paying the overhead.

That's why running with the timeout fix might be interesting - if we were sending a bunch of data, only to then drop the connection, we should see and improvement and it'll tell us if we're on the right track overall.  Another way we might be able to work that out is if you run FASTBuild with -summary  on the command line. It should tell you how much CPU work ended up being done remotely in your various test scenarios. If I'm right, the pure 100 Mbps setup would mean you would see little to no useful remote work shown in the summary.

The bulk of the data transmitted by FASTBuild is the preprocessed source I mentioned above, and the returned compiled object and debug info.  For a code base which is very large (like Unreal) this preprocessed source and the returned objects can be pretty huge: tens of megabytes outgoing, and tens (or even hundreds) of megabytes incoming for the compiler object/debug info.  (If you ever looked at your on-disk PDB sizes for Unreal, I'm sure you know what I mean :) ) The toolchain (in terms of the compiler executable) is relatively small compared to everything else, and is cached between builds, so it's effectively zero cost after the first build.  The SDK (in terms of headers etc) is flattened into the preprocessed file. No other data (such as libs to link against) is sent.

Incredibuild (as far as I understand it) sends individual source files, and (I am speculating) hooks the operating system to intercept file access. This makes it able to send much less data, and likely share source files between objects. That gives it a significant leg up in a low speed network environment. I chose not to take this hooking the OS approach for FASTBuild, and to use a preprocessor based approach because:
a) it would be very difficult to implement hooking the OS, and I would have to do it 3 times (for Windows, Linux and OSX)
b) hashing the preprocessed output (plus some other things) is the equivalent of hashing all the inputs, which is what I need to do to generate unique keys for cache lookup (so the distribution and caching amortize the overhead in a sense)

Anyway, I'll be very happy if we can improve the perf for you, since any improvement to distributed compilation will positively impact all scenarios. Let me know how you go!

**Comment by hillin** [comment]
@ffulin Thank you, now I'm clear how huge the source and yield could be - and the preprocessing approach is brilliant because the performance boost of caching is really amazing. 
Just wondered, does FASTBuild compress the content sent through network? I suppose it could get the network traffic significantly reduced.

**Comment by ffulin** [comment]
@hillin FASTBuild compresses data sent across the network, both for the data sent to remote workers (the preprocessed data) and the data returned (the compiled objects and debug info). It uses the excellent LZ4 compression library (https://github.com/lz4/lz4). The compression has to be very fast to (100MiB/s+ on a gigabit network) to make it an overall win, which is why I chose LZ4: incredibly fast with decent compression yields. Over a 100Mbps network, it's possible more agressive compression could be used, but that would also use up more local CPU time and would also be difficult to remain inefficient in a mixed environment.

On another note, I have submitted some changes today that expose a new -distverbose command line option. This will print information about connections and disconnections (including the reason for disconnection, such as timeout or send failure) (https://github.com/fastbuild/fastbuild/commit/f4a02361ffbb2dfe087bac706c5860bad08d6818) I think this might prove interesting for debugging your use-case.

While developing the above, I noticed that the timeout on network sends is quite low (2s). I suspect this might be a cause for many disconnections in your use-case (and possibly in the Gbps network scenario). If so, that's another potential area to improve things.

**Comment by missmah** [comment]
Is it possible to toggle compression? On 40gbps network I wonder whether the compression will take up majority of CPU time even though the network has plenty of remaining bandwidth?                                                                                                                                                                                                                                                                                                                                                     From: ffulinSent: Sunday, June 11, 2017 13:12To: fastbuild/fastbuildReply To: fastbuild/fastbuildCc: SubscribedSubject: Re: [fastbuild/fastbuild] Distributed Build Performance Issue under Low-Bandwidth Network (#248)@hillin FASTBuild compresses data sent across the network, both for the data sent to remote workers (the preprocessed data) and the data returned (the compiled objects and debug info). It uses the excellent LZ4 compression library (https://github.com/lz4/lz4). The compression has to be very fast to (100MiB/s+ on a gigabit network) to make it an overall win, which is why I chose LZ4: incredibly fast with decent compression yields. Over a 100Mbps network, it's possible more agressive compression could be used, but that would also use up more local CPU time and would also be difficult to remain inefficient in a mixed environment.
On another note, I have submitted some changes today that expose a new -distverbose command line option. This will print information about connections and disconnections (including the reason for disconnection, such as timeout or send failure) (f4a0236) I think this might prove interesting for debugging your use-case.
While developing the above, I noticed that the timeout on network sends is quite low (2s). I suspect this might be a cause for many disconnections in your use-case (and possibly in the Gbps network scenario). If so, that's another potential area to improve things.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/fastbuild/fastbuild","title":"fastbuild/fastbuild","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/fastbuild/fastbuild"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ffulin in #248: @hillin FASTBuild compresses data sent across the network, both for the data sent to remote workers (the preprocessed data) and the data returned (the compiled objects and debug info). It uses the excellent LZ4 compression library (https://github.com/lz4/lz4). The compression has to be very fast to (100MiB/s+ on a gigabit network) to make it an overall win, which is why I chose LZ4: incredibly fast with decent compression yields. Over a 100Mbps network, it's possible more agressive compression could be used, but that would also use up more local CPU time and would also be difficult to remain inefficient in a mixed environment.\r\n\r\nOn another note, I have submitted some changes today that expose a new -distverbose command line option. This will print information about connections and disconnections (including the reason for disconnection, such as timeout or send failure) (https://github.com/fastbuild/fastbuild/commit/f4a02361ffbb2dfe087bac706c5860bad08d6818) I think this might prove interesting for debugging your use-case.\r\n\r\nWhile developing the above, I noticed that the timeout on network sends is quite low (2s). I suspect this might be a cause for many disconnections in your use-case (and possibly in the Gbps network scenario). If so, that's another potential area to improve things."}],"action":{"name":"View Issue","url":"https://github.com/fastbuild/fastbuild/issues/248#issuecomment-307642931"}}}

**Comment by ffulin** [comment]
**> On 40gbps network I wonder whether the compression will take up majority of CPU time**

It's an interesting question to ask. There are many things to consider:
- Compression of the outgoing object files is about 5:1 and operates at 600MiB/s+ (on a mobile i7).
- Decompression is ~1600MiB/s (on same mobile i7)
 - compression of the object files being returned is ~400MiB/s at a 2.5:1 ratio
 - decompression is ~3GiB/s
 - those numbers are for a single CPU core though so on an 8 core machine, you can do a lot more (maybe 4x) If you have more cores than that you can of course do even more, but at some point (particularly on the decompression) you are going to start to hit memory bandwidth limits
 - for the data being compressed on the remote end, we're spreading that work across all the CPUs in the pool, so the bandwidth reduction tradeoff is different
 - the locally compressed preprocesssed data waiting to be sent is kept in memory compressed, reducing the memory footprint and allowing us to get ahead of the remote workers in some cases
 - the obj/debug data being returned needs to be compressed anyway if using the cache, so having that work done remotely saves local work

To satisfy my own curiosity, I thought I'd do some napkin math. Considering just the outgoing compression to start with:

Single Threaded 100MiB preprocessed file:

| Network| Compress |  Send | Decompress | Total |
| --- | --- | --- | --- | --- |
| 100Mbps Uncompressed | - | 10s | - | 10s |
| | 0.16s Compressed | 2s | 0.03s | 2.19s |
| 1Gbps Uncompressed |  - | 1s |  | 1s |
| 1Gbps Compressed | 0.16s Compressed | 0.2s |  0.03s | 0.39s |
| 10Gbps Uncompressed |  - | 0.1s |  | 0.1s |
| 10Gbps Compressed | 0.16s | 0.02s |  0.03s | 0.21s |
| 40Gbps Uncompressed |  - | 0.025s |  | 0.025s |
| 40Gbps Compressed | 0.16s  | 0.005s |  0.03s | 0.195s |

For a single thread, compression is easily a win up to and including 1Gbps. Over that it seems a loss. However, single threaded isn't really the case we're usually worried about.

8 preprocessed files 100MiB each on an 8 core machine (assuming 4x threading parallelization):

| Network| Compress |  Send | Decompress | Total |
| --- | --- | --- | --- | --- |
| 100Mbps Uncompressed | - | 80s | - | 80s |
| 100Mbps Compressed | 0.32s| 16s | 0.06s | 16.38s |
| 1Gbps Uncompressed |  - | 8s |  - | 8s |
| 1Gbps Compressed | 0.32s | 1.6s |  0.06s | 1.98s |
| 10Gbps Uncompressed |  - | 0.8s | -  | 0.8s |
| 10Gbps Compressed | 0.32s | 0.16s |  0.06s | 0.52s |
| 40Gbps Uncompressed |  - | 0.2s |  | 0.2s |
| 40Gbps Compressed | 0.32s  | 0.04s |  0.06s | 0.42s |

For this case, it seems like compression up to and including 10Gbps is a win, and 40Gbps is a loss.  With more CPU cores, the numbers obviously change though.  It seems like 16 cores would be enough to break even and more would make it a win again for 40Gbps.

Now ultimately this is napkin math, and I could have made a mistake above, or i could be way off on the parallelization estimate. The only way we'd know for sure would be to profile (as always :) ).  Disabling the outgoing compression is not exposed right now, but it would be a trivial thing to try locally by modifying the code (the protocol already supports sending uncompressed data for the rare case when the result is larger than the input).  You could test this on your 40Gbps setup and see what happens.

If it proves to be faster without compression in your case, then depending on the numbers, there are some other interesting options. For example, LZ4 has a relatively new "fast mode" which trades a small drop in compression yield for a 33% reduction in CPU usage. That could move the tradeoff line significantly.

**Comment by hillin** [comment]
@ffulin thanks again for the in-depth explanations, learnt a lot today :) I'll try the new commits once I can get my hands on it (or maybe v0.94 will come earlier haha)

**Comment by missmah** [comment]
@ffulin Thanks for that info! Will look further soon!

I'd like to propose a way to disable compression for certain SimpleDistribution build tasks.

We're going to be distributing our image compressor this way with fastbuild, and re-compressing highly compressed data on the way out is likely quite a *huge* waste of time. It might be worthwhile on the way in, but even then, the CPU overhead is probably not worth it when we have 40gbps and rarely saturate the network :)

Even when compression looks like a win in isolation, I think it often becomes a loss when you consider that we're never network bound and always CPU bound, and could have been using that CPU time to do other useful work, for an aggregate build time win. (I realize that a 40gbps network is probably not the norm, though!) :-)

**Comment by ffulin** [comment]
@hillin While working recently to eliminate some rare crash fixes in the distributed compilation, I noticed *another* cause of unnecessary network disconnects (too low Send timeout) that I think would also be disproportionately impacting low-speed connections.  I've submitted a fix for this (https://github.com/fastbuild/fastbuild/commit/1bb24d3294ccf98be92f5ecdd5bb72edee6420b6) which will also be in the next version (v0.94). If you've been able to run your own compiled version with the other fix, it might be good to try with this as well.

@missmah I think we could expose some properties on the Compiler() to control outbound and inbound compression. Seems like that might make sense for your image compression case. The outbound case would be trivial to implement, but the inbound case would require a protocol change (to tell the remote end not to compress) so it would be a little more involved (though still not too hard). For compilation itself, I think you'd have to profile your setup to really see what the overall behaviour with and without compression is like since there are so many variables in play.

**Comment by hillin** [comment]
@ffulin A good news and a bad one: the good one is, our IT finally managed to get a gigabit switch with enough ports for our team, so we're all on gigabit network now. Thus the bad one is, it might not be possible for me to coerce our team to go back to 100Mbps network, so I cannot test how much your fixes could improve in such an environment. Sorry about that - and once again, thanks for your effort.

I tried to compile UE4 again, with exactly the same configuration mentioned in the main post, FASTBuild yielded in 14.4 minutes, which is somewhat close to IncrediBuild - considering we have more IncrediBuild agents, and IncrediBuild utilizes more CPU resources of agent machines thanks to its dynamic CPU allocation mechanism. I've updated the test result in the main post. 

Something off-topic but worth mentioning, as discussed in [this post](https://github.com/fastbuild/fastbuild/issues/123), IncrediBuild seems to profit a lot from distributing linking steps. A rough observation shows IncrediBuild took ~60 seconds (in wallclock time) to complete linking, while FASTBuild took 12.6 minutes of CPU time - divide by 8 threads it's 94 seconds, not to mention that there is not only linking but also some other tasks and idles in IncrediBuild's 60 seconds, I presume it could save up even more time.

**Comment by ffulin** [comment]
v0.94 has now been released, which includes fixes for several disconnection issues that are particularly common in low-bandwidth networks. Given the original creator of the ticket has a speedier new network :), I'm going to close this for now. We can raise new issues for any future problems.
