### ISSUE TITLE
Compile WPF project with XAML files with Fastbuild.

### ISSUE THREAD

**Issue by souoliv1** [fastbuild/fastbuild#265]
Hi! We use FastBuild in my company for our cpp projects. We want to compile WPF projects with XAML forms with FastBuild. Is it possible easily? We begin to think the easiest solution is to keep the csproj file and call MsBuild with FastBuild on it.

**Comment by ffulin** [comment]
From what I understand, it used to be possible to compile xaml files by invoking a command line tool, but for some reason, MS retired this tool and now the only way to compile these files is by invoking msbuild. This is actually super annoying, since it's one of the things that is preventing me from integrating the FASTBuild visualizer plugin into FASTBuild proper.

I haven't looked into whether it's possible to invoke msbuild directly for each xaml file, or if a vcxproj file is needed. I'm open to good suggestions about how to make this work nicely in FASTBuild - perhaps FASTBuild could generate the csproj or something (to avoid having to author them by hand)?

**Comment by ffulin** [comment]
Closing old issues. Let me know if you want to investigate this further and we can re-open.
