### ISSUE TITLE
Fastbuild question: scoping and includes

### ISSUE THREAD

**Issue by g3cko** [fastbuild/fastbuild#270]
I'm trying to further my understanding of fastbuild and have hit a few things, that I wanted to ask if I'm going against the "fastbuild way" or thinking about things wrong. 

```
root/
   libs/
      lib-a/
         default.bff         - auto-generated stub to setup each library/target 
         deps.bff
      lib-b/
         default.bff
         deps.bff
   plugin/
   tools/

(for the output)
   _build
      libs/
      platform/
         config/
               dir of generated includes
               bin/... 
```

I can add more details, but the jist of what I am hitting - in each config, I specify a "generated code dir" which I need to use to specify extra includes (if a lib uses generated code)

```
.GeneratedCodeDir = '$root$/_fbuild/$Platform$/$Target$/_gen'

.Configs = 
{ 
    .DebugConfig, 
    .ReleaseConfig, 
    .ProfileConfig,
    .MasterConfig,
    .GoldMasterConfig,
}
```
   
In default.bff - I do something like this
```
.SupportedConfigs = .Configs
ForEach (.Config in .SupportedConfigs )
{
    Using( .Config )
    #include "deps.bff"  // -- this needs access to the .Config GeneratedCodeDir 
```

Including inside the loop gives me the GeneratedCodeDir variable, but it doesn't seem to include it each iteration, so the variables that I used from inside deps.bff  don't seem to persist.  On the second iteration (release), I get an unknown variable error.  

If I include outside the ForEach loop it works, but I would have to do something different for the GeneratedCodeDir for the include 

This probably sounds a bit convoluted, but this was my first pass at trying to mirror some of the stuff we support now.  

Any thoughts?

**Comment by ffulin** [comment]
Hi there. It's a bit hard to know if this is the best way to do things without really knowing your code-base, but what you are trying to do (use #include in a loop) should work.

The only reason I can think that this would not work is if you have the #once directive inside the included file - this explicitly makes it only take effect the first time it is included, instead of each time it is included. Is it possible you have a #once directive somewhere by accident?

**Comment by g3cko** [comment]
Thanks for the reply.  I forgot about that, I do use #once in the default.bff (which includes deps.bff).. 

I may be misunderstanding the actual error, or how the scoping works, so let me add a little more context.


default.bff
```
#once 
// imports
...
// default variables (to make what is defined in deps.bff optional)
.engine_toolslibs_tpropertyinit_deps_debug = {}
.engine_toolslibs_tpropertyinit_includes_debug = { '$RAD_PROJECT_DIR$/src/engine\toolslibs'}
.engine_toolslibs_tpropertyinit_compileopts_debug = ''
.engine_toolslibs_tpropertyinit_extrafiles_debug = {}
.engine_toolslibs_tpropertyinit_inputpattern_debug = { '*.cpp' }
.engine_toolslibs_tpropertyinit_inputexcludepattern_debug = { '' }
//... for each flavor.

**QUESTION 1:  **
//#include "deps.bff" 

.SupportedConfigs = .Configs
ForEach (.Config in .SupportedConfigs )
{
    Using( .Config )
   **QUESTION 2:**
    #include "deps.bff"

    .IncludeList = .'engine_toolslibs_tpropertyinit_includes_$Target$'

    // -- add any includes our dependencies use
    ForEach (.Dep in .'engine_toolslibs_tpropertyinit_deps_$Target$' )
     {
        Print('$Dep$_includes_$Target$')
        Print(.'$Dep$_includes_$Target$')
        ^IncludeList +  .'$Dep$_includes_$Target$'
      }
```
deps.bff
```
.IncludesCommon = { 
                    "$RAD_PROJECT_DIR$/src/engine/plugins",
}

^engine_toolslibs_tpropertyinit_includes_debug + .IncludesCommon
^engine_toolslibs_tpropertyinit_includes_release + .IncludesCommon
^engine_toolslibs_tpropertyinit_includes_profile + .IncludesCommon
^engine_toolslibs_tpropertyinit_includes_master + .IncludesCommon
^engine_toolslibs_tpropertyinit_includes_goldmaster + .IncludesCommon

```
**QUESTION 1:**  
Would an include be able to modify the above variables, or do they simply replace in the current scope?   

**QUESTION 2:**  
At this point, the variables inside deps.bff should be able to use above defaults to add/modify? Is that correct?  And doing so, will simply reset the next loop when the next #include happens?   

**The problem?**  
Ok, I "think" this is a simpler version my problem.  If deps.bff includes a different  default.bff (to get it's variables, eg includes it forces you require), and default.bff uses #once, should those variables persist through the ForEach, or just the first iteration?  It seems like it is only the first loop... 

```
.var = somevalue 
ForEach(..)
{
    // loop 0
    #include "file.bff" 
         #include "other.bff"
              #once
              .foo = something
         .var = somethingelse
    use .foo  // all is ok 
    // loop 1
    #include "file.bff" 
         #include "other.bff"
              .foo = something
         .var = somethingelse
    use .foo  // doesn't exist in this scope 

}
```
This appears to be my problem, although I'm not clear if this is intended behavior for Fastbuild.  If I'm understanding this, I should be able to work around this by pulling the includes internal to deps.bff and putting them outside the ForEach

**Comment by ffulin** [comment]
If you think about the #include just injecting the contents of the file being included directly into the one doing the including, that might help to understand how it will behave. If you include something in a loop, and that thing being included uses the ^ operator, it is the same as just using the ^ operator directly in thelop - i.e. it will append to the variable outside the loop, for every iteration of the loop, which is probably not what you want.

Including something in a loop that has a #once in it is likely not what you want either, since it will only take effect for the first iteration of the loop.

**Comment by ffulin** [comment]
I thought about it some more - one thing that might be tripping you up is that the way includes work in FASTBuild config files is that they are re-injected every time the include is seen, which in a loop means for each iteration of the loop. So if you include something that has #once in it, it has zero effect for everything after the first loop iteration.

**Comment by g3cko** [comment]
Thanks again for the further info and help.   You're right, that was tripping me up but I see how this works now now.

It does still seem slightly odd though, will includes in a loop ever do anything useful if something included (directly or indirectly) uses #once?

**Comment by ffulin** [comment]
> It does still seem slightly odd though, will includes in a loop ever do anything useful if something included (directly or indirectly) uses #once?

If you're using #include in a loop, I can't think of a situation where you'd usefully combine that with #once. #once is useful when you want to have a hierarchy that represents libraries, and those libraries can include others in order to reference them. In that case, you'd always have your includes outside of the loops.

**Comment by g3cko** [comment]
Ok - I was mostly curious if I was overlooking any use cases for that.

Thanks for the help on this

**Comment by g3cko** [comment]
Woops --- slightly related,  is /showIncludes somehow getting eaten by fastbuild?

**Comment by ffulin** [comment]
FASTBuild uses /showincludes in some cases for dependency tracking. A side effect of that is that it strips /showincludes during compilation. If it didn't you still wouldn't get to see the output though, since FASTBuild will suppress the output unless there is an error.

If you just need it occasionally for debugging, you can use -showcmds on the command line to get the full command line for compilation which you can then invoke directly, adding the /showIncludes. (The -report option might also be of interest as it shows includes used by objects)

If you have something more elaborate in mind, if you could describe your use-case, perhaps it would highlight something that could be changed about FASTBuild.

**Comment by g3cko** [comment]
My use case was pretty simply;  but it is probably more of a side effect of how I was trying to use fastbuild.  Our code has a lot of inter-library dependencies, and one of the things we have now, is a way for each library to specify things like include/lib paths, dlls to copy, etc.  When other libraries reference a library that has added includes/libs/dlls, it can sort of "inherit" those dependencies.  

The hitch I hit porting things over, is "missing includes" and tracking those down is not quite as simple without the /showIncludes output, which makes it very easy to see who is including a specific header.  The work around is definitely doable, but not as usable as a more native approach.

My current thought - maybe it makes sense to have a way to write the "raw" output to disk, or to the report somewhere?  Possibly under 'Compiler' or 'Settings' or as a separate cmd line flag?  If I were to add a custom compiler, I would probably want access to the output when it runs.     

Small disclaimer: I haven't yet looked over any of the code for fastbuild itself - I plan to dig into this more soon.  The other item I would like to get an idea on is conditionals for variables in the bff files, I feel like this would be a huge simplification for how I'm using fbuild.

**Comment by Leandros** [comment]
A possibly related question:

If I'm including platform toolchains in a loop, how could I push the resulting struct which includes the compiler definitions into the global scope?

```
ForEach(.Arch in .Archs)
{
    ForEach(.Toolchain in .Toolchains)
    {
        #include "$Toolchain$-Win-$Arch$.bff"
    }
}
```

The `#include` will create a struct called `.Compiler$Toolchain$$Arch$`, but due to being scoped to the `ForEach`, I cannot access it in any meaningful way in the global scope.

**Comment by g3cko** [comment]
@Leandros  What do you need at a global scope?   I seem to have been able to use structs and the 'Using' keyword, but all of the state I use is internal to my ForEach loops  (for each platform, for each config ... )

**Comment by Leandros** [comment]
I would like to only have a single `ForEach` loop in my build files, which will make the resulting structures available at global scope. This would remove the need to loop through all configs for each build target.

**Comment by ffulin** [comment]
@Leandros Variables can be pushed to a parent scope using the ^ operator, but only if they already exist (this is because if they don't exist, the desired scope level is unclear).  For most use-cases this is fine, since you can create an empty array or variable outside the loop, but for your toolchain use-case, where you presumably want some global structures, I don't think there is a good way to do that currently.

**Comment by ffulin** [comment]
Closing old issues. Let me know if you need more info and we can re-open if needed.
