### ISSUE TITLE
(New Feature) A GUI for FASTBuild

### ISSUE THREAD

**Issue by hillin** [fastbuild/fastbuild#272]
Hi,

Thanks for making such an amazing tool. 

I'm recently writing a GUI program for FASTBuild, namely [FASTBuilder](https://github.com/hillin/FASTBuilder). As our team is migrating from IncrediBuild to FASTBuild, a GUI program is in need. I started by looking into the existing tool [FASTBuild Monitor](https://github.com/yass007/FASTBuildMonitor). Although it's totally functional (and a great start), it hasn't been maintained for months and doesn't support Visual Studio 2017. Also, only a few people in our team are Visual Studio users (others are designers and artists), so we prefer a standalone tool that everyone can use. I tried to make use of its source code, but (with all due respect) the code is quite messy and lacking maintainability. Finally I decide to start a new project.

The log interface between FASTBuild and the Monitor is really well-designed (thanks to @yass007 and @liamkf), and I guess for now it's the best way for an external program to communicate with FASTBuild, so I reused this protocol. I've implemented the build monitor, the worker monitor and a simple settings interface. For the worker monitor part, as you've mentioned there will be a console mode(#229) in the next release and maybe a service mode in the future, I've used some tricky Windows API to manipulate it for now. The GUI is totally non-invasive, so it can work with fbuild.exe and fbuildworker.exe (only tested on v0.93) directly.

A screenshot:
![Screenshot](https://raw.githubusercontent.com/hillin/FASTBuilder/master/Documentations/Screenshots/FASTBuild-Dashboard.0.93.1.png)

The latest version is v0.93.1. It's still buggy and I'm keeping improving it. I've also included an fbuildworker.exe in the most recent release, I checked the licence terms and seems it's legal. Also I'd like to ask if you have any problem with the name (FASTBuilder), I can change it if it makes you uncomfortable 😊. Another question is, can I use an icon derived from FASTBuild's as the icon of this GUI program? Because this could make it looks more uniformly.

As for the future, I hope there could be a better interface to communicate between FASTBuild, Worker and the GUI. I'd like to know your thoughts on this.

**Comment by ClxS** [comment]
Looks fantastic, and it's something I know our team has been wanting for a while!

**Comment by ffulin** [comment]
Nice one. Your UI looks pretty slick :)

**Stand alone vs Visual Studio Plugin**
I'm not sure if you know, but the FASTBuild Monitor actually supports being run as a stand alone exe as well as a VS plugin.

**Name and Icon**
I think it would be good to uniquify the name a bit more (such as "X for FASTBuild" or "FASTBuild X"), so that it's clear it's something *for* FASTBuild, rather than part of FASTBuild itself. I think if you did that, there shouldn't be a problem sharing the icon.  In the end it's all about context, to be sure users (who might not be the ones to configure things) are clear on what is part of FASTBuild and what is not.

**Comms Protocol**
I originally thought something like this would use a loopback network connection, or perhaps a named pipe (or even shared memory), but I actually like the monitor file approach, since it completely isolates the processes, it's very simple, and it allows post-build consumption as well for potentially other use-cases.

**Bundle fbuildworker.exe**
This is fine. As above, just make sure the distinction is clear to avoid any chance of confusion.

**More**
To give some more context on what I hope for FASTBuild in the future:
I would like FASTBuild to have a UI like this, for all platforms. My experience with cross-platform UI's with C# has not been good (bad performance, bloat etc), so I would probably want to avoid that. Similarly, even the best cross-platform UI frameworks (like Qt) tend to be hugely bloated and also come with distribution/licensing complexities.  Because I like to do things the hard way, I think would write the UI natively as I've done for the worker already (at least for Windows and OSX - I might keep linux UI free due to the additional levels of hassle involved there).

In addition to this, I hope to have improved integration into Visual Studio at some point - the "makefile project" system is very limited and makes it hard to improve the experience and propertly fix some things that need work arounds (like solution vs project build). With this in mind, I was looking into integrating the Monitor for FASTBuild, but I ran into problems due to the use of xaml (which can no longer be compiled without msbuild :( )

**Comment by hillin** [comment]
### Standalone vs Visual Studio Plugin
Yes I'm aware that FASTBuild Monitor has a standalone mode, but it's actually an exe that references the VSIX project. You still need VS SDK to build it, and maybe you'll also need to install VS to run the standalone program (just a guess, not tested). Actually I see no reason to couple the monitor with VS, an IncrediBuild-style monitor is as good and more flexible. For instance, our artists (esp. tech artists) now use FASTBuild to distributively compile shaders, but it doesn't make any sense if you ask them to watch the progress in Visual Studio.

### Name and Icon
I've changed the name to **FASTBuild Dashboard**, or **FBD** for short. For now I'm using a orangish variant of FASTBuild's icon, I'll try to design a fancier one as soon as I have time.

### Comms Protocol
Again, the log file approach is great. It would be even better if a certain number of logs of previous builds are renamed and kept, so we can allow users to review history builds. We can also have some minor improvements, like outputting the build stage (obj, exe etc.) of jobs, markup local race jobs and so forth. Maybe we can open another issue for this specifically.

### On Integrating a GUI into FASTBuild
FBD has been improved a lot since I opened this issue. I've rewritten the monitor renderer part, now it's extremely fast, even when displaying a heavy build with more than a thousand of jobs such as building Unreal Engine. Maybe it's not a great idea to use C# to make cross-platform GUI (the accuse of bloat is true), but even with overhead-heavy technologies like WPF, it's still capable of making high-performance GUI programs. Actually it might be even faster than those GUI programs hand-written and tuned with raw Win32 APIs, thanks to the modern render technologies with graphics hardware acceleration involved. 

My suggestion to integrating a GUI into FASTBuild itself is, don't do that. Leave it to third-party programs (like FASTBuild Monitor or FBD, or even an official one made by yourself) and keep FASTBuild a pure console/service program. It's always better to have native GUI programs for each platforms than having a cross-platform one, because in the GUI territory, cross-platform almost always means bad experience. As for the integration to Visual Studio, again, a plugged-in GUI is not a must, IncrediBuild has already proven that.

**Comment by ffulin** [comment]
> need VS SDK to build it, and maybe you'll also need to install VS to run the standalone program 

I never checked to see if it needed the vssdk installed to compile the stand alone exe, nor whether it needed VS installed to run, so that's an interesting point. Certainly we don't want something that depends on VS being installed (to compile OR to run). I was just thinking that in a way it was nice to support embedding as well as stand-alone.

You might be right though - maybe the VS plugin isn't worth the effort at all. The ecosystem is a huge pain, and while it's gotten better, it needs constand maintenance for new versions of VS. (The main reason I was thinking about that is because there are things unrelated to visualization that could only be fixed with a VS plugin)

> My suggestion on integrating a GUI into FASTBuild itself is, don't do that.

The fbuild.exe will always be a command line only tool. By integrating, I just meant that it would be nice to get a fbuildgui.exe in the same zip package as the fbuild.exe and fbuildworker.exe. That day is a long way away though, if ever :)

> it's still capable of making high-performance GUI programs.

On this point, I wasn't talking so much about runtime performance, which I think can be made performant enough. I was more talking about the amount of code dependencies to add to FASTBuild itself if it was included as part of the source distribution. FASTbuild has almost no 3rd party code (just the CRT and lz4) at the moment. Adding a ui framework requires getting the right version of it or bundling it in the FASTBuild source distribution (which depending on licensing isn't even possible)

>  It would be even better if a certain number of logs of previous builds are renamed and kept,

This seems doable. We could do something like keeping a rotating list of n files, with the tool that consumes them using the file date-stamps to infer the order of recentness (to avoid filling up the user's tmp dir).

**Comment by Domain** [comment]
We need a VS plugin so that we can double click on the error message to jump to the source code.

**Comment by hillin** [comment]
@Domain actually it's not difficult for a program to implement this outside of Visual Studio through the [EnvDTE](https://msdn.microsoft.com/en-us/library/envdte.aspx) lib. It's exactly I'm working on (will be included in the next release).

**Comment by jspelletier** [comment]
Hello,

I think visualizers should stay out of the actual fastbuild code base but you could list the known ones on the fastbuild web site page and on the github project web pages. I think that would be enough.

BTW, I've tried this new ui and it's already great.

JS

**Comment by hillin** [comment]
@Domain with the [latest release](https://github.com/hillin/FASTBuild-Dashboard/releases/tag/0.93.3) you can navigate to error source with Visual Studio, Visual Studio Code or Notepad++. Try it out!

**Comment by Domain** [comment]
@hillin How? I double click on the error item, but nothing happen. I have VS2013 and VS2017 installed.  And the external source editor is set to Visual Studio. I always open multiple VS at the same time for multiple solutions. Which one will be used to display the error? I hope I can click a button in VS to start the build, and display all information inside VS, just like Incredibuild. A standalone app is OK, I just don't know which VS instance will be display the error.

**Comment by hillin** [comment]
@Domain hover on an error item and press on any error message in the tooltip. For now it will pick the first Visual Studio instance found to show the file, which as a drawback if you can't stand, there is always [FASTBuild Monitor](https://github.com/yass007/FASTBuildMonitor) as a better choice. 

Detecting which Visual Studio started the build is possible, I'm figuring it out.

**Comment by Domain** [comment]
@hillin I have clicked everywhere in the tooltip, but nothing happen. The error message is in Chinese, it's that matter?

**Comment by hillin** [comment]
@Domain I don't think error message language could be a problem.

As you can see in the picture below, click on the error message shown on the tooltip (if there is one). There is currently a bug that the Visual Studio window won't pop up if the file is already open.

![navigation](https://user-images.githubusercontent.com/13517745/29869318-156238c4-8db5-11e7-9cd9-2262bb654bd6.png)

**Comment by Domain** [comment]
@hillin 
![fastbuild](https://user-images.githubusercontent.com/903197/29869728-c349d2a2-8db6-11e7-80f4-7ec739cbb9fb.png)

**Comment by hillin** [comment]
@Domain oh it seems your compiler outputs an additional space before the colon of error messages. I'll tune the regex to fix this.

**Comment by hillin** [comment]
@ffulin 
Here is a list of features I wish to add in FASTBuild, so FBD can work better with them:

- [ ] Keep a rotating list of log files
- [ ] Output the main process ID if process wrapping is involved (so we can figure out the parent process who initiated the build)
- [ ] Output the building stages (lib, obj, exe etc.) in `START_JOB` events
- [ ] Output a flag if a job is a local race in `START_JOB` events

Should I open another issue to hold these feature requests?

**Comment by Domain** [comment]
@hillin I set external source editor to visual studio, and VS2017 is running. I click on the error message, it says: Failed to open source file. Please go to the Settings page and check if the selected source editor is correctly configured. I change the setting to default, and click again, VS2013 is opened. And I click another error, that dialog is shown again.
Can you scroll the editor to the line where error happen?

**Comment by hillin** [comment]
@Domain The line in which the error message is emitted will be scrolled to, if you choose Visual Studio, VS Code or Notepad++ as the external source editor (if they are working correctly). I haven't made many tests, but I guess something might went wrong with the code dealing with EnvDTE. Could you please try to debug it? And you can fire an issue on [FBD's issues page](https://github.com/hillin/FASTBuild-Dashboard/issues) so we don't spam here :)

**Comment by ffulin** [comment]
I've added a link to FASTBuild Dashboard and FASTBuild Monitor to the 3rd Party downloads (https://github.com/fastbuild/fastbuild/commit/f697a35298b615fc9edd1773c3f371e24c89a498). That'll go live when the next version is released (v0.94)

I think we should close out this issue, raising new issues or pull requests for any -monitor improvements, and reporting issues/adding pull requests for FASTBuild Dashboard on its GitHub: https://github.com/hillin/FASTBuild-Dashboard

**Comment by hillin** [comment]
@ffulin Thanks! With this verdict, I'm closing this issue now.
