### ISSUE TITLE
How to add a custom build step

### ISSUE THREAD

**Issue by fmj02** [fastbuild/fastbuild#276]
I would like to use Exec or Copy after the build finishes but I'm not exactly sure where should I put it. Should I use it as a separate alias and use this alias when executing fbuild with .PreBuildDependencies? Thanks in advance and best regards.

```
ForEach( .Config in .Configs )
{
	Using( .Config )
		
	// Objects
	ObjectList( '$ProjectName$-Lib-$Platform$-$Config$' )
	{
		...
	}
		
	Executable( '$ProjectName$-Exe-$Platform$-$Config$' )
	{
		...
	}
	Alias( '$ProjectName$-$Platform$-$Config$' ) { .Targets = '$ProjectName$-Exe-$Platform$-$Config$' }
}
```

So instead of executing `fbuild -cache SomeProject-Release` I would have to use something like `fbuild -cache SomeProject-Copy-Release`?

I solved it by adding it as a target but not sure if there's a better way.

`Alias( '$ProjectName$-$Platform$-$Config$' ) { .Targets = {'$ProjectName$-Exe-$Platform$-$Config$', 'PostBuildStep-$Platform$-$Config$'} }`

ExecOutput could be optional as well, + output from the Exec could be displayed in Visual Studio output.

**Comment by ffulin** [comment]
The general pattern you want is to make the Copy or post-build Exec part of the normal dependency chain. Something like this:
```C++
ForEach( .Config in .Configs )
{
	Using( .Config )
		
	ObjectList( '$ProjectName$-Lib-$Platform$-$Config$' )
	{
		...
	}
		
	Executable( '$ProjectName$-Exe-$Platform$-$Config$' )
	{
		...
	}

        Copy( '$ProjectName$-Copy-$Platform$-$Config$' )
        {
            .Source = '$ProjectName$-Exe-$Platform$-$Config$'
            .Dest   = 'Output/'
        }

	Alias( '$ProjectName$-$Platform$-$Config$' ) { .Targets = '$ProjectName$-Copy-$Platform$-$Config$' }
}
```
That will take care of the Copy depending on the Exe linking, so the copy will happen after the Link.
You can similarly use an Exec step instead of a Copy:
```C++
        Exec( '$ProjectName$-PostBuild-$Platform$-$Config$' )
        {
            .ExecInput = '$ProjectName$-Exe-$Platform$-$Config$'
            .ExecOutput = 'Output/PostBuild.log' // an output is needed
        }
	Alias( '$ProjectName$-$Platform$-$Config$' ) { .Targets = '$ProjectName$-Copy-$Platform$-$Config$' }
```
If your post-build doesn't generate an output file (if it operates in-place for example), you can use the .ExecUseStdOutAsOutput = true option to satisfy FASTBuild's need for an output file.

Alternatively, you can also use the .LinkerStampExe and .LinkerStampExe options on Executable (or DLL) to perform a post-link step. This is ideal for code signing or other operations that you want done in-place only when a re-link occurs.

All of these take care of the dependencies on the exe itself. The only case where you'd need to add .PreBuildDependencies to Exec() or Copy() is if they also depend on something other than the executable.

I hope that helps - if not, let me know.

**Comment by fmj02** [comment]
Thanks so much! :)
