### ISSUE TITLE
-j3000 takes forever

### ISSUE THREAD

**Issue by trufae** [fastbuild/fastbuild#28]
Trying to compile a hello world with 3000 threads takes forever to finish. It works "fine" for 1000, so i guess that's an issue spawning more threads than the ones needed to build the solution.

**Comment by ffulin** [comment]
You generally want one thread per CPU core (or per CPU thread for hyperthreaded systems). This is the default behaviour of FASTBuild. **You generally don't need to use the -jX option at all.**

As soon as you spawn more threads than you have physical hardware to back, you will see a performance degradation. Spawning hundreds or thousands of threads is going to perform terribly.

FASTBuild doesn't put a limit on the value you pass, and lets you set this to very bad values - it trusts you know what you are doing :)

The -jX option is provided for two use-cases:
a) You want to artificially reduce the compilation performance because you want to run as a background task on a shared resource
b) Some hypothetical situation where FASTBuild doesn't detect the number of CPU cores appropriately because of some future hardware change I can't anticipate

Why are you trying to spawn so many threads?

**Comment by trufae** [comment]
I was testing some limits. Im aware of how the -j thing works. And this is
not happening for 2000 threads. 3000 was the minimum number of threads that
was exposing this issue. If theres only one task, using 10000 tasks to
solve it should be fine too. Fastbuild ahould be smart enough to not run
more tasks than the ones needed. This is a classic race condition issue
when building with make. I wanted to be sure that fb was doing it right,
which is not

**Comment by ffulin** [comment]
The -j option controls the creation of the thread pool used to consume jobs.  Those threads consume jobs as the traversal of the dependency graph discovers work. In this way, the number of tasks which will need to be processed during the build is not known ahead of time, and in any case is unrelated to the number of workers you want in the worker thread pool.  Even if we did know upfront, and there were somehow 1000 files to compile, we'd still only want to create one thread per logical CPU core, so the two things are ultimately not related.

Do you mean that the -j option should be clamped?  I could put a clamp of course, but what would I clamp it to?  Any number I chose would be completely arbitrary and would be second guessing the user.  What is a sensible clamp limit?

Or to put it another way, when you run with -j1000, how many threads do you expect to be created in the thread pool?

**Comment by trufae** [comment]
The thing is, why it hangs, if it is not able to create so much threads it
should not hang.

**Comment by ffulin** [comment]
I have submitted a change to the Perforce mainline. FASTBuild will now reject -j[x] values >64. This will be in the v0.84 release. I will keep this issue open until that version is released.

**Comment by ffulin** [comment]
v0.84 has now been released.  Closing this issue.
