### ISSUE TITLE
Question:  Executable .Libraries using target names

### ISSUE THREAD

**Issue by g3cko** [fastbuild/fastbuild#284]
I just ran into an issue that was pretty hard to track down, I didn't see any relevant output with -verbose, and it kind of feels like a bug.   It appears that the Executable listing out Libraries somehow defines targets, and when the bff for the actual lib was hit later on - I would get get an "Target '...' already defined" error 

The relevant parts (as best I can tell).

Code directory structure like my other posts, where each directory level has a bff that includes sub-directories 

```
root    
    samples  
         testexe
   toolslibs
        somelib    
   default.bff
```
so when I run, 

```
fbuild -config default.bff ...
```
the rest of the files get included into each other.  With this structure though, fbuild parses the samples before toolslibs, so when samples uses a target from toolslibs, it seems to define that target which causes errors later when the toolslibs bff is parsed. 

```
ForEach(.Plat in .SupportedPlatforms ) 
... 
    ForEach(.Config in .SupportedConfigs )

        Executable( 'engine-testexe-$Platform$-$Target$' )

            .Libraries = {
                        'engine-toolslibs-somelib-$Platform$-$Target$',

```
   
I didn't see anything in the verbose output to suggest this though.   Should this work?  Am I overlooking something simpler? 

Thanks!

**Comment by ffulin** [comment]
FASTBuild doesn't automatically include any bff files - it purely includes them in the order you specify. Any target that is used by a subsequent target must be defined first.

The thing that might be tripping you up is that if you reference something that has not been yet defined, FASTBuild will assume you are referring to a file on disk (since it has no way to know better) and will implicitly define the target at that point (as a FileNode). If you then define it later, you will get the error about multiply defined targets (your declaration conflicting with the previous implicitly declared FileNode)

You can see a good example of this behaviour explained in this open issue: https://github.com/fastbuild/fastbuild/issues/21 
As with that issue, this behaviour is by design, but would be a lot more obvious if the error mentioned the place that was originally creating the implicit declaration.

**Comment by ffulin** [comment]
Did you end up resolving this issue?

**Comment by g3cko** [comment]
Thanks @ffulin  for checking back, I had some time off and was away for a bit.  

The explanation that it assumes a file on disk makes sense for what I was seeing.
