### ISSUE TITLE
fastbuild doesn't detect changes in header file(MacOS)

### ISSUE THREAD

**Issue by ganibc** [fastbuild/fastbuild#301]
I tried a simple testcase on MacOS (Sierra)

fbuild.bff
```
.Compiler = '/usr/bin/c++'
.Linker = '/usr/bin/c++'

ObjectList( 'Test' )
{
    .BaseIncludePaths = '.'
    .CompilerInputPath = '.'
    .CompilerOutputPath = 'obj/'
    .CompilerOptions = '%1 -c -o %2'
}

Executable( 'TestLink' )
{
    .Libraries = 'Test'
    .LinkerOptions = '%1 -o %2'
    .LinkerOutput = 'run'
}

Alias( 'all' ) { .Targets = 'TestLink'}
```
a.h
```
struct Foo
{
    int a;
};
```
main.cpp
```
#include "a.h"

int main()
{
    Foo test;
    test.a = 10;
    return 0;
}
```
I ran FBuild and it compiles.

Then I changed the a.h and ran FBuild again.
It just output
```
FBuild: OK: all
Time: 0.002s
```
It doesn't detect the changes in the a.h file, even it's included by main.cpp.
Is this a bug or I'm missing something?

**Comment by ffulin** [comment]
Hello

When you specify the compiler as the "c++" symbolic link, FASTBuild doesn't recognize the compiler, and as such doesn't know how to extract the dependency information. If you switch the compiler to the explicit "clang" or "gcc" compiler, that should work for you as expected.

This is far from ideal of course. The long term plan to fix this is:
a) add an option to Compiler() that exposes the compiler type explicitly, with "auto" being the default.
b) making it an explicit error during bff parsing when "auto" fails to work out what the compiler is
This would of course have made your issue an explicit error, but would also allow you the option of setting the .CompilerType rather than changing the path (though both would be fine).

The first step to fixing this is in the pending pull request https://github.com/fastbuild/fastbuild/pull/260

**Comment by ganibc** [comment]
Thanks. Like you said, now it works.
I think it will be helpful if this information is written somewhere in documentation page.

**Comment by ffulin** [comment]
I will leave this issue open to track the desire to make this behavior more obvious as noted above.

**Comment by ffulin** [comment]
The .CompilerFamily functionality I linked above has now been integrated (https://github.com/fastbuild/fastbuild/pull/260) along with some enhancements (https://github.com/fastbuild/fastbuild/commit/c3f60a2792adf51777fb0845424d5835ac4b2c56). This will be in the next release (v0.95).

The end result is that, with your original setup:
 * You would receive an error indicating that the compiler could not be auto-detected
 *  You could use the new .CompilerFamily to explicitly indicate the compiler type.

I'll leave this issue open until v0.95 is released.

**Comment by ffulin** [comment]
v0.95 has now been released and includes the fix mentioned above for this bug. Thanks again for reporting this issue!
