### ISSUE TITLE
"Database has been moved" is fatal despite -clean

### ISSUE THREAD

**Issue by ClxS** [fastbuild/fastbuild#325]
On one our build machines, we just use the same source directory mapped to different paths for each build task. After upgrading to the latest FBuild from a very old version, we ran into this last night:
```
FastBuild Cmd: ..\Extras\FastBuild\FBuild.exe -clean -monitor -summary -dist -cacheread -ide -config ../../Engine/Intermediate/Build/fbuild.bff
Database has been moved (originally at 'Z:\PROJECTTASK\UE4\Engine\Intermediate\Build\fbuild.fdb', now at 'Z:\PROJECTNAME\UE4\Engine\Intermediate\Build\fbuild.fdb').
FASTBuild Status: (FBResult=False) 
FASTBuild Status: (bUsedXGE=True) - (bAllowFASTBuild=True)
ERROR: UBT ERROR: Failed to produce item: Z:\PROJECTNAME\UE4\Engine\Intermediate\Build\Win64\ShaderCompileWorker\Development\ShaderCompileWorker-Core.lib
Total build time: 2.22 seconds ( executor: 0.00 seconds)
```

It looks like the cause of this is because ReadHeaderAndUsedFiles returns false when the file has moved, this is flagged as a LOAD_ERROR, which makes NodeGraph::Initialise return nullptr. This causes the program to exit.

As the contents of the DB are presumably ignored when the -clean flag is specified, would it be possible to skip the attempt to read the previous DB in the first place and construct a fresh DB when the clean flag is present.

**Comment by ffulin** [comment]
The DB file (.fdb) is used for 3 things:
a) cache of the parsed bff files
b) dependency info for incremental builds
c) timing info from previous builds to improve build ordering in subsequent builds

Even when specifying -clean, all of those things are still useful. Even dependency information for targets you are not building is desireable to retain. For example if you do this:
> fbuild Game-x86 -clean
> fbuild Game-x64
You would not expect the second build to be clean.

With all that in mind, and given that moving the fdb is usually an error that would result in otherwise hard to diagnose errors, I think the current behavior is still the right thing overall.

I can see how those things probably aren't very important in your use case though.  Is it possible for your build system/script/setup to manually delete the .fdb file when your remapping occurs?

**Comment by ClxS** [comment]
Yep we're currently setup the build script to delete those files before each build. I wasn't aware parts of the FDB data would get used still on clean builds, in that case I'll close this issue. :)
