### ISSUE TITLE
Distributed compiling 

### ISSUE THREAD

**Issue by g3cko** [fastbuild/fastbuild#333]
I wanted to ask some general questions about distributed building and the direction for this.  

It appears /ZW prevents distribution due to the way includes are determined from the preprocessed files.   Is that correct?  I'm curious if you have you considered more brute force sandboxing (like SN-DBS) all the inputs (full include directories) to work around this?   

/ZW by itself is not _super_ important to have distributed compiling for, but it would be nice since that speeds up one of our platforms.  My other thought, "it feels*" like distributed is bottle necked by my local cpu as I'm not getting any further benefit adding more agents.   Going from 2 or 3 agents to 10, doesn't seem to give me any noticeable difference compiling 1000's of files.  

This could potentially speed things up overall, but I'm sure has trade offs depending on project/code structure.  Any thoughts? Or comments on direction? 

*I just got fbuild building locally w/VS2015 so I can do some actual profiling, but cpu is steady 100% while network and disk usage appear to be ok.

**Comment by ffulin** [comment]
/ZW doesn't distribute because the preprocessor doesn't provide output that can actually be compiled. 
 It can however be cached, so you might consider using the cache as a way to speed up your /ZW builds.

I did consider using using a sandbox approach like some other build systems, but decided not to do that because that approach is incredibly complicated and has a host of its own problems.  Things like interactions with anti-virus can result in issues like rebuilds being triggered by updates to config files of your AV if they are not carefully filtered from the captured dependencies. Additionally, this approach would require at a unique implementation per platform.

You are right that distributed compilation is often bound by the local machine by the preprocessing.  Given that you are already using a fairly recent VS (older versions had quite slow preprocessors), the best thing you can do for your compile times is use the Unity functionality of FASTBuild.  It is not uncommon for this to result in 10x speed gains just on the local machine. These then translate very well the distributed compilation and caching, since every aspect of the local bottleneck is improved: redundant preprocessing, disk IO and network comms.

**Comment by g3cko** [comment]
Thanks for clarifying for /ZW and sharing your thoughts on the sandboxing.  I'm a little confused how AV could trigger rebuilds, although I've not spend a lot of time thinking about this.  

I haven't yet looked into unity w/fastbuild so I'll definitely investigate that further before anything else.  

Thanks -

**Comment by ffulin** [comment]
> I'm a little confused how AV could trigger rebuilds,

The example I had heard was on-access anti-virus programs intercepting file opens by the compiler, and then lazily opening unrelated files, with the result being Visual Studio's dependency tracker thinking your code files depend on the anti-virus configuration. From that point, an anti-virus config change or update can result in seemingly random rebuilds.  Here's an example of someone reporting this issue a while back: https://connect.microsoft.com/VisualStudio/feedback/details/649139/vs2010-does-complete-rebuild-based-on-completely-unrelated-file

I think the issue lies with the AV software, but still it's one of the sorts of complexities that make it an unattractive option (on top of the implementation difficulty)

Hopefully you'll see some great wins from trying Unity. You can usually start with one of your core libraries to get a feel for how it might scale across the rest of your code. Note too that Unity often results in link-time improvements due to the reduced amount of duplicated code and debug info fed into the link stage.

**Comment by g3cko** [comment]
Oh wow - that's a new one.. good ol' AV hah.  I can see how this can add a new layer of complexity though 

It does look like the unity builds are going to worthwhile moving forward.  Porting my smaller test app - I am getting improvements now using the cache and unity.   Looks like about 2-3x so far but this is a subset of the codebase.  Haven't looked at the actual link times so much yet, this was just overall high level timing compiling and linking 5 or 6 configs for my test app. 

Thanks for the continued support on this

**Comment by ffulin** [comment]
> Looks like about 2-3x so far

Nice.  I'd love to hear what your final result is when you are finished (curiosity/more data points :) )

I'm going to close this issue as resolved for now, but we can re-open it (or raise a new ticket) if you want more info or investigation into anything in particular.
