### ISSUE TITLE
Allow to set multiple active projects

### ISSUE THREAD

**Issue by Dandielo** [fastbuild/fastbuild#337]
After playing around a bit with a premake5 generation module for FastBuild I've hit a small issue with building projects using the 'F5' key, and I've tried the solution described on this page http://www.fastbuild.org/docs/functions/vssolution.html in the Advanced section. I've created an 'All' project that was calling a build for all projects in the fastbuild solution. In my case it's two main executables (a simple game and a Qt app) along a bunch of Test executables. It's fine and dandy, unless I  change a file that requires a rebuild on half of these executables because of the described workaround works. (Well we make full solution build)  

**Note: I don't generate dependencies for VisualStudio projects, so only the current startup project will be checked for changes. So my findings described below might be not valid for a solution with VisualStudio project dependencies. Additionally, I use vs2017, so the below 'solution' might now work older versions.**

However I've been curious why would this work so weird and I've been manually setting my executables as 'Active' projects to see how it turns out. And it worked flawless, now if I hit the magic 'F5' key on any projects that was set as 'Active' it does ONLY run a fbuild command for the given target. 

I've check my settings under '**Options**' > '**Projects and Solutions**' > '**Build and Run**' which I've set like this: 
![image](https://user-images.githubusercontent.com/1361333/32995765-63417fba-cd79-11e7-9d73-72d17e51c237.png)

I've unchecked the '**Only build startup projects and dependencies on Run**' and in that case I've got an error while VisualStudio was checking all my projects "_Another instance of FASTBuild is already running in 'C:\Users\dandielo\Documents\moon-engine\src'_". I'm almost sure this was the problem which resulted with only one project being able to set as 'Active' in a FastBuild generated solution.

Here by I'm asking if it would be possible to change the implementation and allow more than one Active project to be set. Maybe with an explanation how to make it working, just like with the '**All**' workaround. 

The line of code I'm referring to: 
https://github.com/fastbuild/fastbuild/blob/28eb2aba32b083abd3479f05ac6d2fd26cccc67f/Code/Tools/FBuild/FBuildCore/Helpers/SLNGenerator.cpp#L331

**Edit:** Well I got one thing wrong, I've didn't count in a "Solution Build" task in this issue, because it will fail anyway no a full solution build anyway, anyway would still insist on adding this possibility, but maybe behind a boolean value which would force the **-wait** argument behavior with a detailed description so people know what they are going to pay for? 
Just to make clear for readers, the **-wait** command line argument forces all additional calls to fbuild  wait for the current one to finish.

**Comment by Dandielo** [comment]
Well I got one thing wrong, I've didn't count in a "Solution Build" task in this issue, because it will fail anyway no a full solution build anyway, anyway would still insist on adding this possibility, but maybe behind a bool value with a description so there will be no confusion why a Solution build is failing.

**Comment by ffulin** [comment]
We are unfortunately quite limited in what we can do with Visual Studio's "makefile" projects - it's a matter of choseing the least-worst solution in cases where the project contains mutliple executables.

What I've tried to do is allow for something that:
a) Builds everything if you do a solution build
b) Ensures the current exectuable is built
c) Doesn't try to invoke multiple instances of FASTBuild at the same time

This is the best setup I have found that works for both solution builds and individual project builds:
a) Chosing one exe/project as the "master" project (or have an "All" if you prefer)
b) Make that master project the "SolutionBuild" project
c) Make that master or all target depend on all the other Exes in the FASTBuild config (so that building the solution builds all exes)
d) Use the SolutionDependencies to make all the "other" exes depend on the "master" or "all" project (this is necessary so the project will get built if not up-to-date when you press F5 to start debugging)

In this way, the -wait is not necessary - Visual Studio will invoke FASTBuild twice for everything but the primary executable, but not at the same time (due to the SolutionDependencies). Multiple solution build projects are also not required.

It seems that setup should cover your case as well.

Of course all of this is far from ideal. As far as I can tell, improving this would require writing a Visual Studio plugin - that way we could always invoke FASTBuild when needed, for precisely the one target you want to run (or the "solution" when you do a solution build) instead of effectively always doing a solution build.

**Comment by ffulin** [comment]
Change https://github.com/fastbuild/fastbuild/commit/bdcfdfaadeed75a956431fdc8e0b1cd7c928f6d7 added the ability for a solution to have multiple projects set as "Active". This will be part of the next release (v0.96). I'll leave this issue open until then.

(Note that this doesn't solve all the problems with Visual Studio integration touched on with this issue, but it does provide some additional flexibility which can be useful for solving those issues in some cases).

**Comment by ffulin** [comment]
A version containing a change for this issue has now been released (v0.96).
