### ISSUE TITLE
WindRiver Support

### ISSUE THREAD

**Issue by ExtremeGTX** [fastbuild/fastbuild#341]
Hello,
I'm trying to replace make with FastBuild, we are using windRiver dcc.exe (c/c++) compiler.
for now i can compile and link, but there are two problems:
1. FastBuild can't detect changes in headers (.h) files
2. final executable generated (.elf) but progress didn't reach 100%

So, can i fix this from `fbuild.bff` ? or must adding support to fastbuild source ?

Thanks :)

**Comment by ffulin** [comment]
**Compiler Support**

FASTBuild v0.94 detects the compiler by filename, and silently works without tracking dependencies. In the next release (v0.95) this has been changed so that it a) tells you when this happens, and b) allows you to set the CompilerFamily to something compatible.

I'm not familiar with WindRiver, but the info i found on the internet makes makes it look like dcc.exe is similar to gcc, so you could set the CompilerFamily in v0.95 (when it is released) and dependency tracking should work. As a work-around/test you could rename the executable to gcc.exe to see if there are any other issues.

If dcc.exe does behave like gcc, (or one of the other supported compilers), we could add auto-detection support very easily into a future version.

If dcc.exe has any other quirks that might need special handling, some code modifications might be needed. Most importantly, it supports generating pre-processed output (via -E) so that's promising.

**Linking Issue**

Can you provide some more information about the linking problem you have?  Do I understand that FASTBuild invokes your linker, but it never finishes? If so, the best place to start would be to work out what are differences in the command line or environment variables between your makefile and the bff to see what might be different.

**Comment by ExtremeGTX** [comment]
ok, i will try gcc workaround today and post the results.

**Linking issue**
No, the linker invoked and finish and the elf is generated successfully but progress reach about 91% then FastBuild print OK and time.

maybe i will post screenshot and part of the config when i go to my office.

**Comment by ffulin** [comment]
> progress reach about 91% then FastBuild print OK and time.

Oh I understand.  The progress estimate is designed for use on an interactive command line, so once the build completes, we delete the last progress line and don't print another estimate just to show 100% (the FBuild: OK is the thing that signifies completion).  If you are recording the output of the build to a log file, you might want to run with -noprogress.

**Comment by ExtremeGTX** [comment]
i tried to rename it to gcc.exe and it Works!
I will get dev branch and add dcc.exe to gcc family and test it.

**Comment by ExtremeGTX** [comment]
@ffulin should i add dcc to gcc list
```cpp
        if ( compiler.EndsWithI( "gcc.exe" ) ||
             compiler.EndsWithI( "gcc" ) ||
             compiler.EndsWithI( "g++.exe" ) ||
             compiler.EndsWithI( "g++" ) ||
             compiler.EndsWithI( "dcc.exe" ) ||
             compiler.EndsWithI( "dcc" ) )
```

or you will just add to docs, that user should set `CompilerFamily='gcc'`  for all gcc based compilers ?

**Comment by ffulin** [comment]
If dcc is gcc based or gcc compatible (as it seems to be) I think we should extend the detection so it automatically works as you've done.

**Comment by ffulin** [comment]
I went ahead and added the check for dcc/dcc.exe so that the WindRiver compiler is auto-detected and supported (https://github.com/fastbuild/fastbuild/commit/0521c392bdad25c755777fa52ba5cc75db522c70). This will be in the next release (v0.95). I'll leave this issue open until that version is released.

**Comment by ffulin** [comment]
v0.95 has now been release including the change to auto-detect the WindRiver compiler.
