### ISSUE TITLE
concatenation of TEXT("XXX") error

### ISSUE THREAD

**Issue by changshuang** [fastbuild/fastbuild#347]
This is the issuse link:
https://github.com/liamkf/Unreal_FASTBuild/issues/21

Hope some one can help me, many thanks!

**Comment by ffulin** [comment]
For completeness, here is a fairly minimal repro distilled from the other ticket:
```C++
#define TEXT(quote) L##quote
void OtherFunc( const wchar_t * c );
void Func()
{
    OtherFunc( TEXT("\x5927\x9003\x6740\x6362\x88c5\x76f8\x5173")TEXT("BP\x7ed3\x6784\x6570\x636e"));
}
```
Pre-process:
```C++
cl.exe c:\test\text.cpp /E > c:\test\text.pp.cpp
```
Compile pre-processed output:
```C++
cl.exe c:\test\text.pp.cpp
```

**Comment by changshuang** [comment]
But i can not understand why vs2015 can compile ok? Doesn't it use preprocessor? I don't think so. Or this is the problem of just using preprocessor without other functions of vs2015?

**Comment by ffulin** [comment]
When compiling from Visual Studio, the compiler is called in such a way that preprocessing and compilation are done in one invocation.  FASTBuild splits this, to do each part separately, calling the compiler twice. In VS2015, when doing the second pass the tokens are not correctly parsed and compilation fails.  The two different methods of compilation should be equivalent, but they aren't - that's the bug.

(Note that I repro'd the bug with VS2015 Update 3. It might be fixed in VS2015 Update 5. Perhaps worth checking as well if you have not already?)

**Comment by changshuang** [comment]
VS2015 has update 5? I couldn't find the link of download. The top version i can find is update 3.

**Comment by ffulin** [comment]
Ah yes, my mistake - Update 3 does seem to be the latest for VS2015.

**Comment by changshuang** [comment]
It means i have to use 2017 or insert space to solve this problem?

**Comment by ffulin** [comment]
2017 doesn't have the bug so that will fix the problem. Inserting a space should function as a work-around if you can't update to 2017.

An alternative work-around is to disable distributed compilation and caching (.AllowDistribution/.AllowCaching) for the affected libraries. If it's a lot of code that's obviously a real shame, as it will slow down compile times, but if it's only impacting a subset of your code, maybe this is a good option.

**Comment by changshuang** [comment]
It seams that i have to modify the ue4 to support 2017.

Many thanks.
