### ISSUE TITLE
Updated benchmark screenshots on the website

### ISSUE THREAD

**Issue by claimred** [fastbuild/fastbuild#349]
Hi there! Great project you have here.

I wonder if there are up-to-date benchmarks somewhere to be found? Fastbuild vs incredibuild using vs2015/17 for example. Tried building my big C++ project using msfastbuild using vs2015 with no significant performance boost. Maybe I am doing something wrong.  :\

**Comment by ffulin** [comment]
The screenshots are indeed a little out-of-date :), but they are still broadly representative of performance. If anything, various things are much faster in FASTBuild than when those benchmarks were created, and also newer versions of the VS compiler play to FASTBuild's strengths with improved pre-processor speed.

For your project specifically, we can dig into whether there are some gains to be made.

Are you using any of the advanced FASTBuild features, like Unity, Caching or Distributed compilation? My impression is that msfastbuild doesn't give you any of those things out of the box. While some projects (those with lots of DLLs for example) can benefit just from the switch to FASTBuild, many projects don't see any benefits until you start using the more advanced features.

Perhaps you can tell me a bit more about your setup and if you've tried any of those features I can give some more specific advice?

My guess is that caching and distribution would likely be easy to setup (since you can mostly just activate them globally), but Unity (which is the single best way to speed up compiles) might require more effort with msfastbuild (it might not give you the level of control needed to set it up appropriately, or at all). 

Here's a starting point for caching (http://fastbuild.org/docs/features/caching.html) and distribution (http://fastbuild.org/docs/features/distribution.html).

**Comment by claimred** [comment]
Thanks for the answer!

To be completely honest I just tried using msfastbuild straight out of the box without any advanced setup.

> My impression is that msfastbuild doesn't give you any of those things out of the box. 
> but Unity (which is the single best way to speed up compiles) might require more effort

Right. Thank you, will try to put more effort with your neat .bff files and see where it takes me.

**Comment by ffulin** [comment]
I haven't looked at the implementation of msfastbuild, but I wonder if it would be possible to have an option for it auto-generate the Unity files. The general idea would be that for any library, all the files sharing the same compilation settings can be bundled into a Unity() such that each library has one or more Unity() objects.

**Comment by ffulin** [comment]
With v0.99, the website has been updated and the old benchmarks have been removed in favor of a more general indication of improvements that can be expected when using FASTBuild. Naturally, results will vary from codebase to codebase. I may re-add more explicit benchmarks for specific use-cases later.
