### ISSUE TITLE
disable compress lead to crash

### ISSUE THREAD

**Issue by changshuang** [fastbuild/fastbuild#353]
When i disable the compress of DoBuildWithPreProcessor function, compile with '-dist' crash.
Here is my modify:
```
Compressor c;
c.Compress(job->GetData(), job->GetDataSize());
size_t compressedSize = c.GetResultSize();
job->OwnData(c.ReleaseResult(), compressedSize, true);
```
to
`job->OwnData(job->GetData(), job->GetDataSize());`

Is there some place depend on compress ?

**Comment by changshuang** [comment]
![image](https://user-images.githubusercontent.com/8707792/34201275-efaa9750-e5ae-11e7-98c9-8ca6bac9ad79.png)
Compiling unreal4 crash.

As you see, it seems that if don't use compress， the destruct of job will do not detect the end of m_Data.

**Comment by changshuang** [comment]
In our distributed network，there are machines with 56-core. When building with fastbuild, the memory is overhead. The compress take double memory. So i want to disable it to have a try.

**Comment by changshuang** [comment]
Can you figure out which places depend on compress? I  have a try to find it, but failed. Remote jobs read the IsDataCompressed when being deserialized.

**Comment by ffulin** [comment]
Do you mean the memory usage on the fbuildworker.exe (and not the fbuild.exe) is a problem? (I'm assuming that's the case, since the local fbuild.exe has a 1GiB memory cap for distributed jobs.)

Turning off compression for data sent to the worker will actually increase overall memory usage during compilation on the worker given how things are implemented right now.

Right now the worker keeps the buffer it receives in memory for the lifetime of the compilation job. If this is compressed (and it usually is) then before compiling, it will temporarily allocate a new buffer to decompress into, write that data to disk and free this temporary buffer. 

If you change the fbuild.exe to send an uncompressed buffer, it will no longer create this temporary allocation, but it now will keep the uncompressed buffer for the duration of the compilation (and it's usually more than 2x the size of the compressed buffer).

The good news is that we actually don't need to keep the source buffer (compressed or not) after we've written to disk, so we can actually greatly reduce the overall memory footprint without disabling compression.

If you change the end of ObjectNode::WriteTmpFile to to look like this:
```C++
    // On remote workers, free compressed buffer as we don't need it anymore
    // This reduces memory consumed on the remote worker.
    if ( job->IsLocal() == false )
    {
        job->OwnData( nullptr, 0, false ); // Free compressed buffer
    }
    return true;
```
that will avoid keeping the source buffer for the lifetime of the compilation. This means each thread within FASTBuild would return to almost zero memory usage before calling the compiler.

As this is in the FBuildWorker, you will need to re-deploy a new worker exe for this to take effect.

I tried this change locally and it seems to work nicely, so I'll probably and add this to the next version :)

If you still want to experiment with disabling compression (knowing that you will increase the overall memory usage with the current behavior), you would need to change the code you mentioned in ObjectNode::DoBuildWithPreprocessor in such a way that it writes a Compressed buffer with the compression format set to zero. This will then be seamlessly handled on the remote side (you can see an example of this near the comment "compression failed, so just copy the old data" inside Compressor.cpp)

Noe that disabling compression will also reduce the amount of jobs the local machine can prepare for distributed compilation (as there is a local memory cap of 1GiB) and the local machine will be able to fit less jobs waiting for distribution into that memory. This could degrade distributed build performance.

Finally, it should be noted that there might be other opportunities to make improvements to the way compression/decompression is handled to reduce the memory footprint or eliminate temporary spikes (for example looking into the "streaming" API of LZ4). I didn't personally see memory constrained compiles like you are seeing, so all effort around this was on the CPU side so far.

**Comment by changshuang** [comment]
```
    // On remote workers, free compressed buffer as we don't need it anymore
    // This reduces memory consumed on the remote worker.
    if ( job->IsLocal() == false )
    {
        job->OwnData( nullptr, 0, false ); // Free compressed buffer
    }
    return true;
```
I have ever think about this way. You may consider one condition when the remote job fails, it must be completely transform back to client. If we clear it's data on remote machine, the client will receive a bad job.

In addition, i have figure it out what lead to the crash of disable compress. I will create a pull to you.

**Comment by changshuang** [comment]
Sorry, my mistake. Client does not care about the integrity of remote job. I will use it. Thank you!

**Comment by ffulin** [comment]
I have added the code snippet above into the dev branch (https://github.com/fastbuild/fastbuild/commit/6d58ccc35700e909fdf430faa407d66776215aa5). This will be in the next release (v0.95)

**Comment by missmah** [comment]
@ffulin Is there a way to increase the 1G local memory limit for distributed jobs? Our machines have 64-128GB of RAM, and with 72 threads, can likely benefit from having more available memory for distribution :-)

**Comment by ffulin** [comment]
@missmah The value isn't exposed right now, though it would be easy enough to do so via the Settings() function. If you want to experiment, the limit is enforced in ObjectNode.cpp:
```C++
    JobQueue::Get().GetDistributableJobsMemUsage() < ( 1024 * MEGABYTE )
```
If you do try to increase it, I'd love to hear about your results.

**Comment by ffulin** [comment]
@missmah I've exposed a new .DistributableJobMemoryLimitMiB property in Settings(). Additionally, I've increased the default limit to 2GiB for the x64 version of FASTBuild (remains at 1GiB for the x86 version).

https://github.com/fastbuild/fastbuild/commit/53560f6ca39a88e2ad79b121cf551589a5fcd142

This will be part of the next release (v0.95)
