### ISSUE TITLE
question about FindNeedyClients

### ISSUE THREAD

**Issue by changshuang** [fastbuild/fastbuild#357]
`++availableJobs; // over request to parallelize building/network transfers`

If we set the cpu's number of worker with all of the machine. E.g 8-core machine, we set using 8(100%).The code above will lead to overload.

**Comment by ffulin** [comment]
This code you mention intentionally requests one more job than the number of CPUs we have. in order to hide network latency and keep the worker CPUs busy (that is what the comment is about). The extra job will not be started on the remote machine, so we will still only use at most 8 threads at a time in your example.

Are you seeing a case where somehow more than one extra job is being requested?

**Comment by changshuang** [comment]
Sorry, it seems that i have misunderstand the comment's meaning.Thanks!
