### ISSUE TITLE
 Suggestion about FastBuild

### ISSUE THREAD

**Issue by changshuang** [fastbuild/fastbuild#359]
Hello, i have used fastbuild for a time. I have some suggestion about it. Hope fastbuild becaming better!

1. IO：Now i found the biggest bottleneck is io. FastBuild take too much time to read, write and transform data. It also leads to high memory using. If we can use some cloud technology like incredibuild's virtual file system, we can reduce a lot of time.
2. Distribute Strategy：Now fastbuild use server to request job. If there is some low performance machine in distrubte network, these low performance machine can request and get big job.But the high performance machine get small job. This will make the total time limited by the low performance machine.So if we add a center server to collect and dispatch jobs, we will reduce a lot time.
3. Combine Compiling：Now fastbuild force to split compiling to two step: preprocess and compile. I have a try to disable spliting when no distributeavailabe usage. This brings a 20% reduction in compile time. But we notice that fastbuild only cache the non-preprocessing data.If we combine the two steps, cache will die.
4. Distribute Preprocessing：Now fastbuild cannot distribute preprocessing, so it force to split compiling to two steps. If we can also distribute preprocessing, we can reduce a lot of time.
5. Cache preprocesing：As descripiton above, now fastbuild only cache non-processing data. If it can support to cache prerprocessing or whole compiling data,  we can bring a reduction in compile time.
6. Race：Now fastbuild will discard the completed by remote machine when local has started a compile of the same job. If fastbuild can cancel local job instead of discarding remote job, it will recude some time. Like unreal, the last compiled files also very big, fastbuild will discard the remote machine's job for the big file.Then local machine takes the same long time to compile the file again.

**Comment by changshuang** [comment]
Now i understand @ffulin more. Split of compiling to two steps is to solve the includes. If we combine two steps, we will need to transform the files included. That will increase the cost of io. So now the problem is focus on io.

**Comment by AlanIWBFT** [comment]
I have to say a VFS is too huge for a relatively small project like fbuild to implement, especially when you have to implement it three times (Win, Linux and OSX) and potentially with some cost (you need to buy a license to let the NT kernel load your fs filter driver, otherwise you have to enable kernel test mode all the time).
Another thing is I suggest that you can read other issues first then bring up your ideas since most of them has been discussed exhaustively. Some has been proven **impossible** without a big overhaul of the whole system (1, 3, 4).
Also, fbuild borrowed lots of idea from **distcc**. If you look into it you will understand many design decisions of fbuild better.

**Comment by ffulin** [comment]
Hi @changshuang. Thanks for your detailed ideas and thoughts. Several of your points are related, to so I'll bundle some of the answers together below. Let me know if I missed anything.

**Preprocessor vs Virtualized File System**
I chose to build FASTBuild around use of the preprocessor because (as noted by @AlanIWBFT) virtualizing the filesystem isn't really practical, especially when considering implementing it across 3 platforms. Dependency gathering, caching and distributed compilation have all been built on top of this core design choice. It's unlikely this will change.

**Distribute/Cache preprocessing**
In order to distribute or cache preprocessing, without the use of a virtualized filesystem, we essentially have to re-implement the preprocessor. If I was going to re-implement the preprocessor, I would start by doing that entirely on the client side. I think I could implement a faster preprocessor as well as allowing eliminating redundant preprocessing between objects. That might be fast enough so as to eliminate the need to distribute it. In any case, writing a replacement preprocessor is not a small undertaking, so this is not something I expect to do soon.

**IO Bottleneck**
I assume you are talking about the local (client) machine. With the MSVC compiler at least, all preprocessing is done entirely in-memory (nothing is written to disk for distributed jobs). FASTBuild writes the remotely received results to disk., but that's unavoidable of course. The remaining IO is done by the toolchains (like the linker), so that's also unavoidable. Having said all this, in my experience, the local machine tends to be CPU bound so I'm a little surprised to hear you say it's IO bound in your case. Perhaps you have a machine with a *lot* of CPU cores?  I'm a little confused abour your comment that being IO bound results in high memory usage. Can you elaborate on that?

**Worker Management Strategy**
I chose to make FASTBuild worker management completely decentralized (as opposed to having a coordinator like Incredibuild) because having a coordinator is annoying to setup, and not really necessary in my opinion. Generally speaking, it's expected that you don't put "bad" machines in your worker pool (note that you don't need to run the FBuildWorker to use the distribution, only to participate in the pool. So "bad" machines can still use distributed compilation without being workers). Right now the client side doesn't prefer any given worker for distribution (it doesn't pick faster or dedicated machines first for example). This is something that could potentially be improved, along with other aspects of job management. I think any such improvements can be done without introducing a coordinator.

**Race**
I just finished implementing full remote race support (https://github.com/fastbuild/fastbuild/commit/da72ebaf27eadfaba31d634d14cbe47b7698b89b). With this change, if the remote job finished after we've started the local race, we can abort the local job and accept the remote one. This means the race will now always take the optimal result. This can save the entire cost of an object file in the worst case (if it was just about to finish remotely when we started the local race). This can be pretty significant for large object files or Unity files. This change should be in the next release (v0.95).

**Comment by changshuang** [comment]
Thanks very much for @AlanIWBFT's suggestion. I have to apologize for my poor English. English is not my first language, so sometimes i may miss some things even if i have read all the issues. I apologize for it to @AlanIWBFT and @ffulin again.

Hi @ffulin : 
### Worker Management Strategy
I just want to take advantage of idle machines. In my company, there is a lot of idle machines with bad performance because of devices's upgrade.So i want to dispatch some small jobs to these machines to reduce some time.
In one situation: We have 10 jobs to compile, and there are 20 available cores in distribute network. If we can dispatch the jobs to the high performance cores of the 20 cores, we can reduce some time.
I have implement a simple management strategy in client.That bring us some improvement in compile time.
This's just my own opinion
###IO Bottleneck
First i apologize for my confused comment again. I mean: io refers to all data's read, write and transmission on disk, memory and network, not just on disk.
As your guess, in my network there are several machines with a lot of CPU indeed(56-core per machine).On these machine we get io and memory bound.
In addition, we have a lot of machines in distribute network, so the client will deal with a lot of sending and receiving work at the same time.
But from your and @AlanIWBFT's comment, i can understand the difficulty to implement and this is contrary to fastbuild's original design.

**Comment by ffulin** [comment]
I'm interested in hearing more about your scheduling changes to see if there is something that could be applied to the default behaviour of FASTBuild.

**Comment by ffulin** [comment]
@changshuang I'm going to close this issue now as there doesn't seem to be anything specifically actionable here. If you did end up improving scheduling, I'd love to hear about it and see if any improvements can be generically applied to FASTBuild.
