### ISSUE TITLE
PCHTest-Deoptimization does not pass when PCHUser.cpp is RW

### ISSUE THREAD

**Issue by belkiss** [fastbuild/fastbuild#360]
Hello,

Just retrieved the latest dev branch, and got a failure of the PCHTest-Deoptimization unit test:

```
8> Obj: C:\RD\FastBuild\tmp\Test\PrecompiledHeaders\Deoptimization\PrecompiledHeader.pch
1> Obj: **Deoptimized** C:\RD\FastBuild\Code\Tools\tmp\Test\PrecompiledHeaders\Deoptimization\PCHUser.obj
1> WARNING: C:\RD\FastBuild\Code\Tools\tmp\Test\PrecompiledHeaders\Deoptimization\PCHUser.obj
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.
cl : Command line warning D9024 : unrecognized source file type 'UNUSED', object file assumed
1> PROBLEM: C:\RD\FastBuild\Code\Tools\tmp\Test\PrecompiledHeaders\Deoptimization\PCHUser.obj
Microsoft (R) Incremental Linker Version 14.00.24215.1
Copyright (C) Microsoft Corporation.  All rights reserved.
/out:UNUSED.exe
UNUSED
LINK : fatal error LNK1181: cannot open input file 'UNUSED.obj'
1> Failed to build Object (error 0x2) 'C:\RD\FastBuild\Code\Tools\tmp\Test\PrecompiledHeaders\Deoptimization\PCHUser.obj'
```

Because I use git and not perforce, the file PCHUser.cpp is RW, hence becomes deoptimized, and uses the CompilerOptionsDeoptimized set here:

https://github.com/fastbuild/fastbuild/blob/07254dcf79492ce92ae0faf1d0f959923743219c/Code/Tools/FBuild/FBuildTest/Data/TestPrecompiledHeaders/Deoptimization/fbuild.bff#L52

I can confirm that the test passes after making the file ReadOnly.

**Comment by ffulin** [comment]
Thanks for reporting this. The test was actually completley broken in that it wasn't actually testing the thing it was supposed to test!  The test is supposed to check that a writable precompiledheader is not deoptimized, even when deoptimization is enabled.

In any case, I've fixed it so that it works properly: https://github.com/fastbuild/fastbuild/commit/2a1c5452307b67f9de68f55e0f9399bf14127bf4

I'll leave this issue open until the next version is released (v0.95).

**Comment by belkiss** [comment]
Thanks for the fix :)

**Comment by ffulin** [comment]
v0.95 has now been release including this fix.
