### ISSUE TITLE
Distribution Not Working with Xbox One/UE4.

### ISSUE THREAD

**Issue by deadwizad** [fastbuild/fastbuild#363]
Afternoon, another UE4 related question/issue.

I'm using liamkf/Unreal_FASTBuild implementation with some minor modifications.
I find that build isn't distributing when compiling the xbox one. 
However its working when compiling windows.

Any ideas how i can track down why?

Thanks in advance.

**Comment by liamkf** [comment]
Hi there! 

The problem stems from the fact that UE4 specifies /ZW globally for Xbox One builds. It's annoying as it certainly doesn't need it for every module... but from what I can recall if you disable the global flag you'll then have to change a few dozen files in the engine for the places where /ZW is actually required. I ended up not using it at the time for Xbox as a local build with full PCHs ended up building in roughly the same time after accounting for less PCH usage and the increased link time. It's possible VS2017 and its improved preprocessor will change the balance though. Good luck! :)

**Comment by deadwizad** [comment]
Liamkf! Excellent information. VS2017 is a broken for xbox one in the ue4 implementation. I'm currently waiting for GDNP access so i can get on the forums and fixup the compile errors.
The link time is about 10 minutes on Vs2015. On every game it seems. I'm hoping the same, that 2017 is better because its quite terrible.

Thanks.

**Comment by ffulin** [comment]
/ZW is sadly incompatible with distributed compilation (from memory the preprocessed output can't be successfully compiled) The solution as noted is to restrict /ZW to only those files that need it.  From memory, this also reduces the size of object files by ~10% and, depending upon what your compilation is bound on, can give an improvement to compile/link times in and of itself.

Last time I worked with XboxOne (3 years ago), I remember that using /Z7 debug format caused crazy slow link times only for XboxOne - i.e. 10 minutes instead of one minute. It sounds like that might be what you are seeing?

If you combine limiting /ZW to only select files and stick with /Zi debug info, you won't be able to use the cache, but you will be able to use distributed compilation and you should see "normal" link times.

(PS - If /Z7 is still the cause of the crazy slow link times, maybe it's worth reporting that to MS if that can be fixed?)

**Comment by ffulin** [comment]
Did you end up with a solution for this issue?

**Comment by ffulin** [comment]
Closing old issue due to lack of response. We can reopen if this is still an issue you'd like to pursue.
