### ISSUE TITLE
Build not pulling from Cache when compiling.

### ISSUE THREAD

**Issue by deadwizad** [fastbuild/fastbuild#364]
Context, 

I have two identically setup machines( for the most part ). Both have the same repository downloaded and the same setup of visual studio. 

I compile the game with distribution and caching enable.
I use the same machine and force a recompile, the machine pulls from the cache build time is less than 10% of the original build. #WIN 

I then move the second machine, which has access to the cache and was part of the original distributed compile. I compile the exact same configuration.
No caching is used and the build compiles as if nothing was cached.

I've tried with both machines with -r -rw -w cache options with the other machine using the corresponding option.

Now the only difference in the machines. Is that one is and AMD Ryzen 7 1700X and the other is an Intel i7 7800X.

Is the CPU difference the spanner in the works?
Should this even be a problem? 
Is there a bug in the system? 

Cheers
Sean

**Comment by ffulin** [comment]
The CPU vendor doesn't impact the ability to cache between machines. (If it did, there would be a serious bug in the compiler - it would have to be generating different output from the same source)

If one machine is able to build and then retrieve its own objects from the cache, then it seems like there is no issue with your compilation settings or permission control of the cache. Further, assuming *each* machine is able to read and write its own objects to the cache, but they just can't see each others, that implies that something is different between your two machines. 

The most common reasons for caching not working between machines are as follows:
 - not compiling in the same directory (object files embed full paths so full paths must match)
 - not using the exact same code (slightly different SDK installation is a common example)
 - not using the same version of the compiler (different update for example)

(I recommend checking your compilers into source control, but if you can't do that, then you'll have to ensure you install the exact same versions)

Assuming it's not the obvious path mismatch case, we can work out what doesn't match as follows:
 1) on machine a) build a single object file with caching enabled and -verbose output enable
```C++
fbuild C:\p4\depot\tmp\x64-Profile\FBuildApp\Unity1.obj -clean -cachewrite -verbose
```
 in the output you will see something like this:
```C++
1> Cache hash: 5 ms - 1406 kb '30F41BC82C860E2B_AD4198E2_68D446D99AD5D726-0000000000000000.8'
1> Cache store: 15 ms '30F41BC82C860E2B_AD4198E2_68D446D99AD5D726-0000000000000000.8'
1> -Build: 597 ms       C:\p4\depot\tmp\x64-Profile\FBuildApp\Unity1.obj
```
2) on machine b) run the same command, but with -cacheread:
```C++
fbuild C:\p4\depot\tmp\x64-Profile\FBuildApp\Unity1.obj -clean -cacheread -verbose
```
When it's working, it would output something like this:
```C++
2> Cache hash: 5 ms - 1406 kb '30F41BC82C860E2B_AD4198E2_68D446D99AD5D726-0000000000000000.8'
2> Cache hit: 5 ms '30F41BC82C860E2B_AD4198E2_68D446D99AD5D726-0000000000000000.8'
2> Obj: C:\p4\depot\tmp\x64-Profile\FBuildApp\Unity1.obj <CACHE>
```
Note how the cache key matches in my example.

When it's not working, it will be because the cache key doesn't match. The five components of the cache key, or order, are:
 - hash of preprocessed source code
 - hash of compiler options
 - hash of compiler
 - hash of precompiled header for object file (or 0 for pch itself or if not using pch)
 - cache version

Whichever one of those is mismatched will point to the problem and give us next steps.

**Comment by SteelLegacyGames** [comment]
Thanks for the detailed reply.

I'll get testing all of this and let you know what i find.

**Comment by ffulin** [comment]
Closing old issue due to lack of response. We can reopen if this is still an issue you'd like to pursue.
