### ISSUE TITLE
work directory needed and skip $ key word

### ISSUE THREAD

**Issue by changshuang** [fastbuild/fastbuild#367]
1.Some reponsefile use relative path, then if fastbuild spawn compile process with empty work directory. The compiling will failed because of no file found. So we need to add work directory as a property to each node.
2.clang use -rpath=${orgin} to redirect path. But fastbuild will parse $ as a substitute of other property, this operation will spilt clang‘s compile options and lead to compile failed. So fastbuild need to skip the key word of some compile tool.

**Comment by ffulin** [comment]
You can escape the $ character in any property if you want it to be treated literally instead of as the start of a variable. This behavior is described here: http://fastbuild.org/docs/syntaxguide.html#escaping

Note that while FASTBuild itself can use response files in certain cases, manually created response files are essentially not supported. At least the following problems will be encountered if you create manual response files:
 - changes to the dependency file will not trigger a rebuild
 - changes to files references by the response file will not trigger a rebuild
 - caching will not function properly
 - distributed compilation will not work at all

FASTBuild currently requires that all command line arguments be passed directly via .CompilerOptions.

Manually created response files could be supported in the future, but it would require significant work to address all the scenarios described above.

**Comment by ffulin** [comment]
@changshuang Do you need any more information? Can we consider this issue resolved?

**Comment by ffulin** [comment]
Closing old issue due to lack of response. We can reopen if this is still an issue you'd like to pursue.
