### ISSUE TITLE
showinclude is not reliable for caching

### ISSUE THREAD

**Issue by mhandb** [fastbuild/fastbuild#38]
Showinclude write a human readable output, you should not parse it.
You can use tracker.exe instead.
It is used by MSBUILD to identify the input and output files of a process.
It will allow you to identify every files used in a build step and to know what is generated by this build step.
tracker.exe works with every kind of process: cl, lib, link, mt, midl... any.exe.

**Comment by ffulin** [comment]
Hello :)

/showIncludes is only used in very specific circumstances - to track includes for compilation when using the MS compiler (cl.exe) and when the cache and distributed compilation is not used.  Typically parsing of the preprocessed output is used (#line directives) as this overlaps other work done to support distributed compilation and caching.

Intercepting file access could be an interesting way to support generic tools, and this is potentially something that can be added to FASTBuild.

If this was done in the future, it would likely be implemented within FASTBuild itself.  Tracker.exe can't really be used because:
* **It's part of MSBuild and not always available** - FASTBuild needs to continue to operate on a clean Windows install. (tracker is distributed with some other things, but we still can't be sure it's available on the machine)
* **It's Windows only** - Dependency tracking on OS X and Linux needs to work.
* **It emits files unrelated to the actual compilation** - If you examine a tlog file generated by tracker.exe you will often see various files unrelated to the compilation.  In some cases, things like antivirus signature files will appear. It might be possible to filter this out, but filtering the output of tracker.exe rather than during process invocation loses some of the context which would be useful.
* **Additional process overhead** - Calling another executable introduces additional overhead. It's not huge in more recent versions of Windows, but it's still a cost. Tracking directly from within FASTBuild would avoid this cost.

**Comment by ffulin** [comment]
In what specific situation do you feel /showIncludes is not reliable as used by FASTBuild?

(Ignoring the fact that, somewhat ironically, there is a bug in the parsing when the locale is non-english which will be addressed by https://github.com/fastbuild/fastbuild/pull/37)

**Comment by mhandb** [comment]
As I ran into the #37 issue, I just wanted to notice that showIncludes is meant to be read by humans, for instance to check the include files order. Not to be used in a build processed. It also disables other cl options like /MP but It seems you do not need it in this specific case.
I did not know the FastBuild behavior you discribed.
I think the fix for #37 is fine.

**Comment by ffulin** [comment]
Thanks for the clarification.

You're right that multithreading is managed by FASTBuild itself, so /MP is not used.

I'm going to close this issue, since there is already an issue tracking the bug you had: that one will be resolved when the fix is integrated:
Issue: https://github.com/fastbuild/fastbuild/issues/33
Fix: https://github.com/fastbuild/fastbuild/pull/37
