### ISSUE TITLE
LZ4.bff differs between 0.95 source zip, master, and dev branches...

### ISSUE THREAD

**Issue by belkiss** [fastbuild/fastbuild#381]
Which one wins? :)

Some other files differ from the source zip downloadable from http://fastbuild.org/downloads/v0.95/FASTBuild-Src-v0.95.zip

Thanks!

**Comment by ffulin** [comment]
Thanks for letting me know. I've sorted out the issues:
 - The 'master' branch now matches the v0.95 release tag in Perforce (the LZ4CompilerOptions were not correctly integrated into Github). I regenerated the v0.95 GitHub 'master' release, so it now matches the fastbuild.org source zip download for v0.95. This should correctly represent the config used to build the binaries released for v0.95.
 - The Perforce head now matches the 'dev' branch (gen_default_aliases.bff was not correctly integrated into the Perforce mainline previously)

**Comment by belkiss** [comment]
Thanks!
Also noticed that:
* the same file also misses the change introduced by e0a30747ab2c57b751ac6664983a49ba51025ea6
* the file .gitattributes misses the changes from dda20b3f0213f357c67042cfa9da55c052b1d7a6
* the file .gitignore misses changes from cd1860a5490ae1845f029b8e7cc4e956d95325d3

**Comment by ffulin** [comment]
e0a3074 was not correctly integrated into the Perforce mainline before v0.95 was cut, so I deliberately left it out of 'master'. This way the Perforce v0.95 version and the Github 'master' @ v0.95 both match and are in the state the code was when the v0.95 binaries were built. In response to your issue, I integrated the fix in the Perforce mainline, so that it matches Github 'dev'/ When v0.96 will be release this change will make it's way into 'master'.

I'll take a look at the .git metadata issues you mentioned.

**Comment by belkiss** [comment]
Alright thank you for the precisions :)
