### ISSUE TITLE
[ELF][dcc] Source paths are pointing to .fbuild.tmp

### ISSUE THREAD

**Issue by ExtremeGTX** [fastbuild/fastbuild#391]
Hello @ffulin
The new version is awesome 👍, but i found a new issue ☹.
The debugging tools are reading the generated ELF file to discover debugging symbols and the path of source files.
The problem is source file paths are pointing to `%temp%\.fbuild.tmp\Core_X\....` instead of `MyProject\src\bsw\spi\spi.c`

I have tried to make fbuild treat the compiler as `custom` by setting `.CompilerFamily` and that seems fixed the issue, but raises another one which is fbuild is not aware of **files dependencies** 

BTW, FASTBuild save us about 50% of time on full Compilation of 548 files and 100% of time required to check depends on incremental build 👍👍

**Comment by ffulin** [comment]
When a file is compiled on the remote machine, it will have the remote machine's path embedded. This is not something FASTBuild controls, but something the compiler does. Most debuggers/IDEs are smart enough to find the source file locally, but it might be necessary to configure additional search paths for your debugger or IDE.

Note that this situation is the same as if you were to debug an executable built on another machine through any other build system if the path on that other machine doesn't match yours.

> I have tried to make fbuild treat the compiler as custom...

Setting the compiler to "custom" will disable distributed compilation, which is why it avoids the path problem you mentioned. As you noted, FASTBuild doesn't understanding the full dependencies for "custom" compilers, only the primary input file. (More details can be found here: http://fastbuild.org/docs/functions/compiler.html)

> BTW, FASTBuild save us about 50% of time...

That's great to hear! I'm guessing these gains are from distributed compilation? Are you using Unity as well?

**Comment by ExtremeGTX** [comment]
Sorry, i didn't mention the details
The Compilation Environment as the following:
- Compiler: dcc.exe (WindRiver)
- CompilerFamily: gcc
- OS: Windows 7 64-bit
- Compilation done locally (i.e. Single Machine) with 8 Cores CPU.

So, no distributed Compilation here.
As i enabled Verbose output, I found that the compilation done on two steps:

1. Pass input file to Preprocessor:
`<Compiler> <CompilerOptions> <Source File> -E`

2. Then pass the preprocessed file to The Compiler
`<Compiler> <CompilerOptions>` **`<Processed File>`**

So, Can i override the second step to use the **`SourceFile`** instead of **`Processed File`** ?

> That's great to hear! I'm guessing these gains are from distributed compilation? Are you using Unity as well?
No, The compilation run on local machine with 8-Core CPU.
548 C and Assembly files .

**Comment by ffulin** [comment]
> Can i override the second step to use the SourceFile instead of Processed File ?

You could do this, but that has two major drawbacks:
 - we'll be doing preprocessing twice, making the build slower
 - distributed compilation won't be possible (since it uses the preprocessed output remotely)

In addition to this, your compiler not respecting the #line directives is a bug in my opinion. While FASTBuild does have workarounds for bugs in other compilers, I consider that to be a last resort. I think it would be worth seeing if:
  - dcc has an option to make this behaviour the same as other gcc based/compatible compilers

OR
  - Your compiler vendor can fix this bug

> No, The compilation run on local machine with 8-Core CPU.

If you want compilation to be even faster, I recommend trying out Unity(). It's not uncommon for this to give a 5-10x compilation speedup!  (It also usually results in faster link times too)

**Comment by ffulin** [comment]
@ExtremeGTX Did you end up with a resolution for this issue?

**Comment by ExtremeGTX** [comment]
Actually I postponed this issue for a while due to my tight schedule,
But,
I checked what you said and found that in the pre-processed file there are a lot of 
`#line linenum path_to_original_source_file`
so maybe the problem with IDE itself (it is winIDEA btw)
I will dig more deep into this, because it is currently the only issue blocking me from integrating FASTBuild with our project.

**Comment by ffulin** [comment]
@ExtremeGTX Did you end up making any progress on this in the end?

**Comment by ffulin** [comment]
I'm going to close this issue as there is nothing actionable on my end. Let me know if you want to investigate anything further, or if there is anything to be done on the FASTBuild side and we can re-open or create a new issue as needed.
