### ISSUE TITLE
OSX - Linking Dll error

### ISSUE THREAD

**Issue by kylawl** [fastbuild/fastbuild#42]
Attempting to add a Dll to the .Libraries on and Executable fails. It seems as though the Node is an Exe rather than a Dll. I assume this means the dynlib just isn't supported yet?

FASTBuild Error #1005 - Executable() - Unsupported node type in 'Libraries'. (Node: '/Users/kylerocha/dev/Bump/Project/master_rengine/bin/OSX-Debug/dll/rEngineDLL.dll', Type: 'Exe')
	Executable( '$ProjectName$-Exe-$Platform$-$Config$' )
	^
	\--here

**Comment by ffulin** [comment]
DLLs (shared libs) are supported on all platforms.  DLL() is mostly just an alias for Executable(), provided to assist readability.  The ultimate deciding factor on whether you are linking a DLL is the command line args.

On OS X and Linux, FASTBuild checks for:
* -shared
* -dynamiclib
If neither of these are seen, it assumes you are linking an executable, rather than a dll/shared library.

So I can think of two reasons this might not be working for you:
a) You are missing one of these arguments in your .LinkerOptions
b) You are using an alternative argument to the linker that FASTBuild isn't detecting, but should be (i.e. there is a bug)

If it's (b), it will be a trivial fix.

Let me know in either case! :)

**Comment by kylawl** [comment]
Ya I just came across that -shared/-dynamiclib switch parsing. You're right, we were using /DLL for windows still so fbuild wasn't picking it up.  So this isn't actually a bug.

It's a bit misleading the way the DLL function doesn't actually do anything. Maybe it should error with a specific message about being a DLL but does not have the appropriate flag set, rather than a generic message about mismatching node types?

Thanks!

**Comment by ffulin** [comment]
> It's a bit misleading the way the DLL function doesn't actually do anything.

It actually does slightly alter the linking behaviour on Windows (linking objects instead of libs into the DLL by default), but other than that they are the same.

 > Maybe it should error with a specific message about being a DLL but does not have the appropriate flag set

Indeed this is something I had planned for the Windows DLL case. There is already a task in the backlog to do just that.  I've extended the task to also include the OSX and Linux equivalents. That might save someone some time in the future which would be nice.

**Comment by nil-ableton** [comment]
@ffulin I encountered this issue, and found the reason thanks to this entry. I first attempted to set the LinkerOptions as follows:

```
.LinkerOptions = '"%1" -o "%2"'
...

DLL('DllX')
{
    Using(.DebugTargetConfig)
    .LinkerOutput = 'output/target/Debug/DllX.dylib'
    .LinkerOptions + '-shared'
    .Libraries = {'DllX.objects'}
}
```

In that situation FBuild still complained that whichever executable is depending on DllX is depending on an executable.

The error only disappeared when I assigned to LinkerOptions instead:
```
DLL('DllX')
{
    Using(.DebugTargetConfig)
    .LinkerOutput = 'output/target/Debug/DllX.dylib'
    .LinkerOptions = '"%1" -o "%2" -shared'
    .Libraries = {'DllX.objects'}
}
```

**Comment by ffulin** [comment]
hi there

It seems the problem with your non-working config is that you are missing a
space when appending the option:

.LinkerOptions + '-shared'

You need:

.LinkerOptions + ' -shared'

I hope that helps :)

Cheers!

- Franta

**Comment by nil-ableton** [comment]
Thanks! Exactly, I forgot the prepend space. Sorry about the mail noise (I have removed the message on the issue to not confuse people)

Cheers,
Nicolas
________________________________
