### ISSUE TITLE
No workers found in networked location when tokens exist

### ISSUE THREAD

**Issue by StephenPSS** [fastbuild/fastbuild#443]
Running a test that successfully completes on the local machine fails to detect workers when run with the "-dist" argument. The status of the network is this:

- All workers have the same "FASTBUILD_BROKERAGE_PATH" (\\gandalf\FASTBuild) Environment variable set via group policy: this leads to a networked location publicly available to the "Everyone" user group (any user in Windows). This location can be viewed from any machine via windows explorer.

- Workers are populating their tokens in a subdirectory "main/16", these tokens have the same name as their computer of origin and have no text.

- Other machines running FBuildWorker have 6 idle cores each set to "Work for Others When Idle".

- Windows Firewall is off for all computers.

- When run in an Administrator command prompt from the location of the FBuild.exe and the .bff file, the output is the following:
`D:\depot\ThirdParty\FASTBuild>fbuild -clean -dist
No workers found in '\\gandalf\FASTBuild\main\16\'
No workers available - Distributed compilation disabled
1> Running Test: D:\depot\UnitTestResults.txt
FBuild: OK: all
Time: 11.764s`

- The worker's operating systems are Windows 10 Pro, and the remote server our Environment variable leads to is running Server 2012 R2.

- The bff file that successfully runes its test locally is as follows:
`.TestOutput = 'D:\depot\UnitTestResults.txt'
.TestExecutable = 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe'
Test('OneRingAnalysisTest')
{
 .TestArguments = 'D:\depot\Encoder\Binaries\x64\Release\unitTests.dll /Tests:OneRingAnalysisTest /Platform:x64 /InIsolation'
}
Alias('all'){.Targets = {'OneRingAnalysisTest'}};, 'ViewCellPriority'}}
`

Cheers!

**Comment by ffulin** [comment]
Thanks for the detailed info about your problem.

If there are tokens in the network drive for the available workers and you see this:
```C++
No workers found in '\\gandalf\FASTBuild\main\16\'
```
That means FASTBuild can't access that directory. The only thing that stands out is your mention of running from an Administrator command prompt. Perhaps there is some permissions issue. Are you able to perform a directory listing of that location from the elevated command prompt?

If you can't do a directory listing, then it seems there is a permissions issue. If you can, then I'm not sure what the problem is, but the next step would be debugging FASTBuild. You can do that by:
 - using Process Monitor to monitor the file access (https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) and look for problems with access
 - downloading the latest source package, which includes pdbs (http://fastbuild.org/downloads/v0.95/FASTBuild-Src-v0.95.zip) and step through WorkerBrokerage::FindWorkers
 - building it locally from that same source package or the Git repo (more work but better debugging experience) and step through WorkerBrokerage::FindWorkers

**Comment by ffulin** [comment]
One other thing to note: FASTBuild support distributed compilation, but Test() is not distributable.

**Comment by StephenPSS** [comment]
We've tried a few things, and the most consistently successful was just running from an administrator windows account instead of just an elevated command prompt. I would suggest trying this to anyone with the same problem.

Thanks for the help!
