### ISSUE TITLE
MSVC Deterministic Executable

### ISSUE THREAD

**Issue by gkoreman** [fastbuild/fastbuild#466]
This is not a FASTBuild specific issue, but I thought I'd ask here as I imagine many of you have run into the same problem.

MSVC creates non-deterministic executable binaries. The linker will insert a guid and some datestamps. This causes issues with hashing a toolchain, which of course wreaks havoc on caching.

What do other people do about this? Does anyone use something like this: https://github.com/smarttechnologies/peparser

I was thinking of adding PeParser in the Executable LinkerStampExe. PeParser looks like it is geared toward doing the compare itself, however it looks like there may be functionality to modify/strip this info as well.

Franta, feel free to close/remove this issue if you feel this isn't an appropriate place for this discussion.

**Comment by l0calh05t** [comment]
Or [ducible](https://github.com/jasonwhite/ducible) could be used to make the .exe / .pdb reproducible

**Comment by ffulin** [comment]
For the most part, I've given up on determinism with respect to the MS compiler. It's a real shame, as it would (on very rare occasion) be very handy to know two exectuables were identical.

I have seen people mention that some tools exist in the wild to "fixup" executables in order to make them more deterministic, or to diff them ignoring timestamps etc, but I haven't used them personally.

One thing I do though, is make sure none of the projects I work with include __TIME__ or __DATE__ macros, as this prevents caching. (I always do timestamp injection post-link so that it's only changed if linking is actually performed anyway).

**Comment by gkoreman** [comment]
Thank you both for the insight.
