### ISSUE TITLE
FASTBuild writes unbounded in disk usage?

### ISSUE THREAD

**Issue by bburgin** [fastbuild/fastbuild#503]
How do users typically manage the growing size of the FASTBuild cache, both locally and on workers?
Would a FASTBUILD_CACHE_LIMIT variable help?
Thanks

**Comment by bburgin** [comment]
A coworker mentioned this to me:
http://www.fastbuild.org/docs/options.html#cachetrim
So this feature is already available. And the cache seems to only be for the local FBuild.exe, not remote workers.

Are there other files that the local FBuild and remote workers write? Say to the tmp folder?
Do these grow unbounded? I want to ensure I have covered all the cases. Thanks.

**Comment by ffulin** [comment]
**-cachetrim**

FASTBuild's cache can indded be managed using the -cachetrim command. Alternatively, you can freely delete files from the cache using your own script if that is more convenient for you.

Note that the cache is intended to be for sharing object files between machines, so it should generally point to a location on the network. Having a cache on the local disk is mostly only useful right now to work around bff edits causing rebuilds (which is close to being fixed).

**> And the cache seems to only be for the local FBuild.exe, not remote workers.**

Yes. Only the local fbuild.exe interacts with the cache, even when storing an object built by a remote machine. If a remote worker builds something we want to store in the cache, it is first returned to the local machine which manages the storing.

**Are there other files that the local FBuild and remote workers write?**

FASTBuild uses the TEMP folder as follows:

* Intermediate files are written to disk between compiler passes, in various sub-directories of (%TEMP%\.fbuild.tmp) This is deleted afterwards. This happens both locally and remotely. Abnormal termination of builds could result in some of these files not being cleaned up, but I have not seen this be a problem in practice.

* Remote machines cache the distributable toolchains (compilers and related dlls) under various sub-directories of (%TEMP%/worker/). These persist between builds and between restarts of the fbuildworker.exe. This is by design (to avoid unnecessary network traffic). There is no cleanup mechanism for this, so it can grow unbounded, but under normal circumstances, this is not an issue. This could become a problem if you are compiling and distributing your own compiler (such that it goes through many revisions).

I hope that helps.

**Comment by bburgin** [comment]
Thanks for the details. Very helpful. I am closing this issue. Cheers.
