### ISSUE TITLE
it seems no necessary for ASSERT( ( (size_t)data % 4 ) == 0 )

### ISSUE THREAD

**Issue by tming** [fastbuild/fastbuild#542]
the folowing assert seems no necessary (in file Tools/FBuild/FBuildCore/Helpers/Compressor.cpp)

bool Compressor::Compress( const void * data, size_t dataSize )
{
...
ASSERT( ( (size_t)data % 4 ) == 0 ); // input must be 4 byte aligned
...
}

bool Compressor::Decompress( const void * data )
{
...
ASSERT( ( (size_t)data % 4 ) == 0 ); // input must be 4 byte aligned
...
}

**Comment by ffulin** [comment]
These asserts were left over from when FASTBuild was using a custom data compressor (as opposed to lx4 which it uses now). I have removed the asserts (https://github.com/fastbuild/fastbuild/commit/db65ade28ce1b78c4caf650dee143c6cbbf133a1).

Note that in final Release builds all asserts are stripped, so should have been harmless.

Were you seeing any problems caused by these asserts, or did you just notice that they were not needed?

**Comment by tming** [comment]
It will fail with this when i run fast build with debug version, and the compressed data is not satisfied with this assert.
