### ISSUE TITLE
How to prevent from rebuilding everything?

### ISSUE THREAD

**Issue by psallandre** [fastbuild/fastbuild#55]
Hi,
I have a main fbuild.bff that includes other ones:
#include "lib1.bff"
#include "lib2.bff"
...
#include "exe.bff"
All is good but there are linker errors, so I modify linker options in "exe.bff" but it tells me "BFF file 'exe.bff' has changed (reparsing will occur)" and rebuilds everything including all libs.
I use '-cache' on the commandline but it doesn't seem to have any impact.
Thx

**Comment by ffulin** [comment]
Hello

Modifying any .bff currently causes a full rebuild. The expectation is that once your bff is setup, it rarely needs to change. However, as you've found, when setting up for the first time this can be annoying.

In the long term, I plan to change this behaviour, so only affected items will rebuild when a bff is modified. This requires some non-trivial re-factoring which is already underway, but won't be complete for some time.

In the short term, as you've tried, the -cache option can be used to try to reduce the rebuild time to lessen the impact of this problem. The main reason this wouldn't work for you is if you are using an incompatible compiler or compiler option. Please take a look at the caching restrictions documented here: http://www.fastbuild.org/docs/features/caching.html

If you still can't get caching working, let me know.

**Comment by psallandre** [comment]
Thanks for the explanation. I'm looking forward for this functionality! 

As a starting point, maybe a "per file" modify check would be a good improvement. In my example above, a change in "exe.bff" would only trigger "exe.bff" to be rebuilt as it is the last included bff file. "lib_n.bff" would trigger "lib_n+1.bff" and all following bff files.

Anyway, I'm beginning to experiment with caching and distributing. I tried with fastbuild itself. I just modified the fuild.bff to compile with VS2015 under Windows 10 ( cf my fork to see the modifications). The only files that are cached are the LZ4 files, all others are marked uncacheable in the report. Is this the expected behavior with MSVC?
Thx

**Comment by ffulin** [comment]
It's very common that configuration be split across many files.  To reliably know which file affects which target is unfortunately the same as determining which bit of the file relates to which target, so what you propose sadly requires the same solution that's already being worked on.

For the caching:
FASTBuild supports generating Unity files to accelerate compilation.
FASTBuild also supports isolating locally modified files out of the Unity to improve iteration times. It does this by checking the read-only status. The idea is that if you use something like Perforce for source control, your files are usually read-only, and are writeable only when you "open for edit" those files and start modifying them.
Locally modified files (isolated from Unity) are not cached, since the normal scenario of caching between users doesn't make sense for local modifications.
The config to compile FASTBuild uses both of these features, and the mainline development happens in Perforce.

If you just unzipped the source (or got it from github) then all your files will be writable and therefore isolated from Unity and therefore uncacheable.

So you have two options:
a) Make all your files read-only
b) Disable the Isolation feature for writeable files (comment out ".UnityInputIsolateWritableFiles = true" in the main fbuild.bff).  It only really makes sense when using Perforce source control.

**Comment by psallandre** [comment]
I commented out ".UnityInputIsolateWritableFiles = true" and it cached as expected.
I think I had not realized how powerfull Fastbuild was, thanks for that!
