### ISSUE TITLE
VS Intellisense with clang

### ISSUE THREAD

**Issue by cyberkm** [fastbuild/fastbuild#557]
I am using clang while using MSVC to write code. And the built-in intellisense is checking my code using MS compiler, which of course complains on clang specific lines (ex: all kind of atomic operations)
I was wondering if its possible to somehow set generated MSVS projects to use clang intellisence?
In theory it should be possible as MSVS supports clang toolset.

**Comment by ffulin** [comment]
VS uses a completely different compiler front end for Intellisense (the EDG compiler), not whetever is used to actually compile. Any msvc or clang specific behavior is emulated by this front end, which is presumably one of the reasons it's inconsistent even in "real" VS projects. I'm not sure to what extent the back-end is used for Intellisense, but that seems to always use MSVC, even when you are using Clang.

Source: https://developercommunity.visualstudio.com/content/problem/46231/intellisense-problems-with-linux-x64-mode.html

This page talks about how EDG for intellisense runs in "clang compatibility mode" and that prior to VS2019, this emulates Clang 3.6 (at least for linux-x64). It's possible updating to the latest VS2019 IDE might improve the experience.

Failing that, the only control FASTBuild has over the behavior of Intellisense is via the settings it puts into the project (for defines, includes and other things). It's possible that to make this work correctly something needs to be improved here, such as:
a) Addina a __clang__ include in your bff (i.e. make this implicit define explicit so that it will get populated into the Intellisense info by FASTBuild)
b) Some "AdditionalOptions". FASTBuild knows to put certain args in here (like /std:c++17) which impact the compiler behavior. Perhaps there are some additional things needed for Clang.

If you can provide some specific examples, I'd certainly be interested in seeing if they can be improved.

**Comment by ffulin** [comment]
@cyberkm - Do you have any more info, or a repro case that can be used to further investigate this issue?

**Comment by cyberkm** [comment]
Hey, sorry for long time to respond,
I explicitly added __clang__define to the compiler flags, it didn't help
here is an example of what i see
![image](https://user-images.githubusercontent.com/297410/66143564-08063300-e610-11e9-8229-d0cf0b19212d.png)

**Comment by ffulin** [comment]
I looked into this and it seems the same problem exists even if you create a new Visual Studio solution using the wizard in VS (i.e. a "normal" non-FASTBuild project)

That makes it seem to me like this is a limitation of the Intellisense engine. With that in mind, I don't think there is anything that can be done on the FASTBuild side.

**Comment by ffulin** [comment]
Given that this issue exists even when FASTBuild is not involved (i.e. a project created "normally" in Visual Studio exhibits the same problems) I don't think there is anything actionable here. With that in mind, I'm going to close this issue.

If this is fixed in Visual Studio in the future and additionally requires code changes to FASTBuild, we can reopen this issue or create a new one.
