### ISSUE TITLE
error C3360: 'ATL4': cannot create IAttributeHandler

### ISSUE THREAD

**Issue by jaycex** [fastbuild/fastbuild#609]
fastbuild fails to build at remote agent when _ATL_ATTRIBUTES defined, but can build successfully at local machine.
this is a simple demo, you may need append "-dist -forceremote" to fbuild to reproduce the problem:
foo.cpp
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <atlbase.h>

int APIENTRY _tWinMain(HINSTANCE hInstance,
                     HINSTANCE hPrevInstance,
                     LPTSTR    lpCmdLine,
                     int       nCmdShow)
{

	return 0;
}

fbuild.bff
.VSBasePath = 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\'
.VCBasePath = 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\'
.WindowsSDKBasePath = 'C:\Program Files (x86)\Windows Kits\8.1\'

Settings
{
	.Environment = 
	{
		"INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include;;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc\include;;C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt;;;C:\Program Files (x86)\Windows Kits\8.1\Include\um;C:\Program Files (x86)\Windows Kits\8.1\Include\shared;C:\Program Files (x86)\Windows Kits\8.1\Include\winrt;;",
		"LIB=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib;;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc\lib;;C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x86;;;C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86;;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\Lib\um\x86",
		"LIBPATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc\lib;;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib;",
		"PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;"
		"SystemRoot=C:\Windows"
	}
}

Compiler('msvc')
{
	.Root = '$VSBasePath$/VC/bin'
	.Executable = '$Root$/cl.exe'
	.ExtraFiles =
	{
		'$Root$/c1.dll'
		'$Root$/c1xx.dll'
		'$Root$/c2.dll'
		'$Root$/1033/clui.dll'
		'$Root$/mspdbsrv.exe'
		'$Root$/mspdbcore.dll'
		'$Root$/mspft140.dll'
		'$Root$/msobj140.dll'
		'$Root$/mspdb140.dll'
		'$VSBasePath$/VC/redist/x86/Microsoft.VC140.CRT/msvcp140.dll'
		'$VSBasePath$/VC/redist/x86/Microsoft.VC140.CRT/vccorlib140.dll'
	}
}

ObjectList('compile')
{
	.Compiler = 'msvc'
	.CompilerOutputPath = "Debug\"
	.CompilerInputFiles = { 'foo.cpp' }
	.CompilerOptions = '"%1" /Fo"%2" /c /Zi /nologo /W3 /WX- /Od /Oy- /D WIN32 /D _DEBUG /D _WINDOWS /D _ATL_ATTRIBUTES /D _UNICODE /D UNICODE /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fd"Debug\vc140.pdb" /Gd /analyze- /errorReport:queue /FS'
}

Alias ('all')
{
	.Targets = { 'compile' }
}

**Comment by ffulin** [comment]
I was able to reproduce the problem. It seems to be caused by a missing dll used only for ATL compilation. You'll need to add the following to .ExtraFiles:
```
'$Root$/atlprov.dll'
```
It's unfortunate that cl.exe failed in such a non-obvious way.

I've updated the Compiler() documentation in case this might save someone some time in the future (https://github.com/fastbuild/fastbuild/commit/d073cdd26b9acb7dee40486af56c3d6468404d8c)

Additionally, I ran into two other problems with your configuration.

**Missing runtime DLL**
```
'$VSBasePath$/VC/redist/x86/Microsoft.VC140.CRT/vcruntime140.dll'
```
Without this, the compiler will fail on the remote machine with STATUS_DLL_NOT_FOUND if it doesn't happen to have the VS2015 CRT already installed. You may have had the CRT installed on your remote machine, thus avoiding this error, but you'll want to add this for robustness.

**Missing TMP variable**
cl.exe requires TMP environment variable to be defined. I'm not sure why you didn't encounter an error, but without this I get a "failed to get command line into debug records" error trying to compile locally. If you want to suppress the environment for all your other stuff, you can re-add TMP as follows:
```
#import TEMP
.Environment =
{
    "TMP=$TEMP$"
    ...
```

**Comment by jaycex** [comment]
Add '$Root$/atlprov.dll' to .ExtraFiles do solve the problem, @ffulin Thank you very much! I ran into this problem for several weeks.
About the other two problems:
1. My remote agents have runtime dll installed, so i didn't encounter this. I will add this to my configuration.
2. I did remove TMP and TEMP in .Environment, because they are specific to my machine, like "C:\Users\jaycex\AppData\Local", sorry for that.

ps: I use msfastbuild to generate the configuration file, so i don't know the details of it. Thank you again for your help.
