### ISSUE TITLE
Fastbuild Window - How to add the items to add to the link command line

### ISSUE THREAD

**Issue by Tan2NT** [fastbuild/fastbuild#614]
Hello,

I have a project with the structure as below:
MyProject
   - Lib A
      - Dependency: Lib B
Lib A is compiled succeed but when linking, the error occurs because it could not find the function from lib B: error LNK2019: unresolved external symbol _SDL_putenv referenced in function "public:.......

Could you please tell me know how can I config inside BFF file a dependence lib to the link command line same as on the Visual Studio?

`<ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='win32_debug_dll|Win32'">
    <Lib>
            <AdditionalDependencies>B.lib;%(AdditionalDependencies)</AdditionalDependencies>
    </Lib>
</ItemDefinitionGroup>`

Thank you for your time and attention.

**Comment by ffulin** [comment]
You need to specify the dependencies for the link steps (your Exectuable() orDLL()), something like the following:
```C++
Executable( 'MyExe' )
{
    // Specify other libs (that you declared earlier with ObjectList or Library)
    .Libraries = {
                   'Core-Lib'
                   'MyOtherLib-Lib'
                 }

    // Specify 3rd party or system libs you have set /LIBPATHs for
    +.LinkerOptions + 'kernel32.dll'
```
A couple of things that might help you understand how this should work:
 - A complete "Hello World" example for Windows: http://fastbuild.org/docs/examples/helloworld_windows.html
 - The FASTBuild source code (an example of multiple platforms, configs, libs and exes) (http://fastbuild.org/docs/download.html)
 - Looking in the "Command Line" project properties in Visual Studio (under "Linker" and "C/C++" to see what the final settings are that Visual Studio creates)

There is no "Additional Dependencies" automatic variable equivalent, but you can use the bff syntax to build such a variable if you prefer to "inherit" the dependencies hierarchically instead of listing them all explicitily at link-time.

**Comment by Tan2NT** [comment]
Hi,
I was used ".LibrarianAdditionalInputs" to add B.lib with the path to B.lib, and it's working perfectly.
Thanks for your support.

**Comment by ffulin** [comment]
.LibrarianAdditionalInputs is a way to merge .lib files together, and is quite different from the AdditionalDependencies mechanism of Visual Studio, which is a way to accumulate dependencies that are finally passed on the linker command line.

You may find that using .LibrarianAdditionalInputs this way works ok, but be aware that this might cause problems ranging from link time performance issues to problems with duplicate symbols. It will also subtly change the way symbol resolution works which could cause other problems.

**Comment by Tan2NT** [comment]
"but be aware that this might cause problems ranging from link time performance issues to problems with duplicate symbols"
I will be checking your note. 
Thanks for your help.
