### ISSUE TITLE
Possible use of SRWLock instead of CRITICAL_SECTION

### ISSUE THREAD

**Issue by ben-craig** [fastbuild/fastbuild#619]
FastBUILD has a mutex class.  On Windows, this mutex class is backed by CRITICAL_SECTION.

Starting with Windows Vista, there is a more efficient way to do inprocess mutual exlusion, SRW Locks in exclusive mode.

If we don't need to support XP, we can migrate to SRW Locks as the backing primitive for our mutex.

So do we need to support WinXP as a host?  This would have to effect on whether we can target built binaries to work on WinXP.

**Comment by ffulin** [comment]
Windows 7 is the oldest supported version as a host OS. FASTBuild already uses functions that require that OS or later (such as GetNumaNodeProcessorMaskEx). The supported host OS doesn't really meaningfully impact the supported target OS. The limiting factor is usually is the compiler and SDK. A 64bit Windows 10 box, using VS2017 and the Windows 10 SDK can still build executables that will run on Windows XP for what it's worth.

SRW locks cannot be used as a wholesale replacement for CRITICAL_SECTION in the Mutex class because they don't provide support for recursive acquisition. Certainly most uses of FASTBuild's Mutex do not rely on that capability, but we'd have to check each use and replace them one at a time. It would probably make more sense to create a new class, and use that in places where locking is on the critical path (the primary case I can think of is inside the SmallBlockAllocator).

**Comment by ffulin** [comment]
I did a test replacing the CRITICAL_SEECTION with an SRWLock in the SmallBlockAllocator and saw no appreciable changes in performance, either when the locks are contested or uncontested. For now, it seems there is no specific situation which would benefit from this change, so I'm going to close the issue. We can re-open/re-evaluate in the future if this changes.
