### ISSUE TITLE
Different preprocessed key when cachewrite distributed

### ISSUE THREAD

**Issue by EtienneDS** [fastbuild/fastbuild#651]
Hey @ffulin, 

I rarely ask questions of this way as it seems to be more of a individual thing rather than a bug, as I searched for a long time various posts and other issues but found nothing really talking about the issue I'm having.

It is to do with the cacheName given to the cache folders, more specifically the beginning, the prepocessedKey part. It seems when I am in cacheread(distributed and local-only) and when I am in cachewrite(local-only), a certain preprocessed key is calculated for a file, but when I am in cachewrite(distributed) another key is calculated for the same file. All my attempts in my cachereads(distributed) are missing since it can't find the files by the name it "should" have (while reading in distributed a cache which was written in local-only works fine). 

Could you please enlighten me on how the preprocessed key is calculated? Logically, I would've thought it is calculated by the local workstation, in order to save the correct paths (and not the temporary ones in the remote pc/server), but in that case I cannot understand what would vary between distributed and local preprocessedKey hash calculation as the files should be the same.

Please feel free to ask more information on my part if it could give you more context.

Thanks,
Étienne

**Comment by EtienneDS** [comment]
Alright so I've found why the error was happening. Seems when I'm in cachewrite mode (no cacheread), line 1169 or ObjectNode.cpp directly exits without passing by calculating the cachename. So instead of calculating the preprocessedKey on the source file, it calculated the key on the compressed file, thus obtaining a different hash. 

To fix it, I just put the loop under the call to GetCacheName() at line 1176. This way, it calculated the cacheName at the start at keeps it, thus exiting the GetCacheName() at the start on the second time, already having a cacheName.

This may have been a bug in the program from the start, as it may have been triggered by the fact I have played a bit with the compression algorithms (added lzma2 and zstd, who have a higher compression ratio and thus loads less the network when distributing and caching).

Thought giving an update even if I fixed it for myself so it could probably help others with a similar problem.

**Comment by ffulin** [comment]
There is a bug in v0.98 which caused an incorrect cache key to be generated when results were returned from a remote worker, preventing a cache hit on subsequent builds. This has been fixed in the dev branch (https://github.com/fastbuild/fastbuild/commit/466a542c3be2e42ae2063234d9787f356002b9f8#diff-2072e4a7195fdc451940c02b783f62e9) and will be in the next release (v0.99)

I will leave this issue open until the next version is released.

**Comment by ffulin** [comment]
FASTBuild v0.99 has now been released which includes a fix for this issue.

**Comment by EtienneDS** [comment]
Hey @ffulin ,

Just looked at the fix you brought in to fix the bug with the cachewrite and distributed builds. Is there a reason you added GetCacheName() before every call to RetrieveFromCache instead of going in RetrieveFromCache and lowering the exit condition (if cacheread == false) to under the call to GetCacheName?

Although a small difference, it seems to be adding more lines of code and introducing more bugs if one wants to add another RetrieveFromCache and forgets to add GetCacheName in front... By letting the RetrieveFromCache function deal with the GetCacheName itself, it seems to facilitate this whole part (even more considering RetrieveFromCache already has a GetCacheName call at its very start).

Thanks in advance for the insight.

**Comment by ffulin** [comment]
I wrote it this way because code we call later on (to attempt to write to the cache for example) relies on GetCacheName having been called, whether RetrieveFromCache is called or not. Even if the Retrieve call is removed, we still need to GetCacheName in those places.

It could be structured the way you suggest, and in some ways that would be better, but in others (with respect to the above) I think it would be worse.

If anything, I think perhaps removing the GetCacheName call inside RetrieveFromCache and having RetrieveFromCache assert that the cache name is valid might be the best option. Having said all this, I don't think it's worth losing any sleep over it in its current form.
