### ISSUE TITLE
Building only if code has more recent timestamp on disk?

### ISSUE THREAD

**Issue by incursionrob** [fastbuild/fastbuild#654]
Hey @ffulin,
Is there a specific reason why do you check if a file has changed by checking if the timestamp (last edit time) is newer (e.g. GetStamp() > m_stamp), instead of GetStamp() != m_stamp? This results in not building code, if for example you revert a file with SCC that changes the timestamp back to the previous version's timestamp (in the past). I just want to make sure there is no code that relies on this, before I change it locally.

Thanks!

**Comment by ffulin** [comment]
FASTBuild associates a timestamp with each "node" in the dependency graph. FASTBuild compares those timestamps in two situations:

a) For a given node, if the stamp on disk doesn't match the stamp in the database (implying that the file was modified outside of the build process), the output is considered to need rebuilding.

b) For a node A that depends on node B, node A is considered to need rebuilding if node B is newer. i.e. if you change a file, anything that depends on it must rebuilt. Since a node can depend on many nodes, this is a many to one relationship, thus node A can never have a timestamp equal to everything it depends on.

A side effect of b is that any stamps that go "backwards" will not trigger rebuilds. This issue is covered by https://github.com/fastbuild/fastbuild/issues/407.

I plan to change the dependency graph implementation to support this use-case, but it will be more involved than simply changing the comparison. (Each dependency will need to record that timestamp at which it was last considered valid)

**Comment by incursionrob** [comment]
Thank you for the quick reply, I will try get some time to dive deep. I do have an easy work around the issue for now as FastBuild is well worth the effort for us. Thanks again.
