### ISSUE TITLE
Offer binary releases over HTTPS, preferably with checksums

### ISSUE THREAD

**Issue by nre-ableton** [fastbuild/fastbuild#655]
It would be nice when downloading FASTBuild if it were available over HTTPS with some type hash checksum files, so users can be sure that the downloaded software is secure and exactly what they are expecting it to be.

I guess as a quick-and-dirty solution, releases could be published both to http://fastbuild.org and to GitHub releases.

**Comment by ffulin** [comment]
I've been planning on switching fastbuild.org to https for some time now, but simply haven't gotten around to it yet. Providing secure hashes on top of that seems unnecessary (since an intercept of the download could just as easily intercept the page containing the hashes if using https.

I'll leave this issue open to track the https upgrade. In the interim, in case it's helpful, here are some hashes for the latest version (v0.99):
```
                MD5                             SHA-1
-------------------------------------------------------------------------
ed8171c6d2be31df1fd8ff5ccd18c61f 79af7195b19db8611ce6d7ed8fff249e5b40cae1 fastbuild-linux-x64-v0.99.zip
552d06c129c2cfccce0205dc5dd27f85 1bfab980322562d8cdddc6655eab638dfd434f39 fastbuild-windows-x64-v0.99.zip
9092e9d324a28acbef0f9c893e6b80d3 c4a2602a1662bf952bc3096d42d4510583e778b4 fastbuild-osx-x64-v0.99.zip
9eea0993113435ce41607751086c2518 600bcfb961fa950e3bc886a45089d53640f8e436 fastbuild-src-v0.99.zip
```

**Comment by ffulin** [comment]
fastbuild.org is now served over https :)
