### ISSUE TITLE
File timestamps are wrong. Libraries are frequently rebuilding when they should be clean.

### ISSUE THREAD

**Issue by ChrisRedacted** [fastbuild/fastbuild#656]
After a recent Windows 10 update, a subset of our programmers are now having problems with the executable thinking that it is always dirty and always needs to be rebuilt, because *some* of the .lib file written timestamps are constantly newer on disk than the timestamps stored in the fastbuild database.

To figure out what was writing to the file, I actually used the windows sysinternals Process Monitor to see what was writing to the file. The only processes touching the lib file at all were fbuild.exe (queries), link.exe (presumably to write the file), and then "system". Here's what it looks like:

![image](https://user-images.githubusercontent.com/21223712/68166431-f4f4c480-ff27-11e9-9b9a-c098eff6d80e.png)

I do not get this problem on my own machine. When I look at the timestamps on my own machine, it appears that the file modification time roughly lines up with the end of the link.exe portion of the build process, before fbuild.exe queries the file for the file last written time. Side note: I guess lib.exe internally fires up link.exe?

On my coworker's machine, when fbuild runs again, the last written timestamp of the file stored on disk is listed as occurring during the "System" portion of the file writing process...just a fraction of a second after the last written timestamp was stored in the FDB. Thus, it sees fbuild as being out of date, and that the .lib file needs to be rebuilt. If you look at the verbose output, you see something that looks roughly like this:

1>  Need to build 'D:\my.lib' (externally modified - stamp = 132171125152727103, disk = 132171125162237082)

I had a theory that the Process that spawns the librarian in:

/*virtual*/ Node::BuildResult LibraryNode::DoBuild(Job * job)

would not be guaranteed to be fully done writing out to the file until the destructor of the librarian Process ran, which would run after:

    // record time stamp for next time
    m_Stamp = FileIO::GetFileLastWriteTime( m_Name );

But even scoping that Process to guarantee that its destructor runs before the GetFileLastWriteTime did not seem to fix the problem for people.

This problem is occurring on version 0.98 of fastbuild. We are compiling using VS2015 compilers/librarian/linker. 

Any ideas?

**Comment by ffulin** [comment]
I'm using Windows 10 (1903) across various PCs, as are many other people I work with. I've not had anyone report anything like what you're seeing. I've mostly been using VS2017. I don't know what would explain this behavior or the difference in behavior between machines. The only stab-in-the-dark ideas I have are:

**a) security software** - FASTBuild already contains some work arounds for poorly written security software on Windows. If you are running anything, you could try disabling this on the problematic machine temporarily to rule it out. I've been stung many times by weird security software over the years.

**b) Windows subsystem for Linux** - I haven't seen any problems with timestamps, but I have seen a build environment completely messed up by WSL marking individual files as case-sensitive, causing all manner of build problems.

Failing that, I guess I'd try to narrow down differences between machines (or commonalities for those it's not working on), e.g. exact Windows 10 version, hardware/driver versions, other software installed etc.

If you find any leads, let me know and I'll let you know if it sparks any ideas.

**Comment by ChrisRedacted** [comment]
We are all running the same security software, as far as we can tell. And nobody is using Windows subsystem for Linux. There doesn't seem to be a rhyme or reason as to who can build and who cannot.

I tried dropping in calls to WorkAroundForWindowsFilePermissionProblem() before trying to get the file timestamp. It looks like you do that in a few other places. But that doesn't trigger anything. Even with debug output, I can see that the output file is being opened for read immediately. It never fails to open the file for read, even once. Even on machines that are super delayed on the "last write timestamp".

Putting a Thread.Sleep(2000) made a few libs get correct timestamps. Then I tried putting a Thread.Sleep(10000) in there, and then all the libs were saving out correct timestamps and not rebuilding. But then the linking of the exe still had a problem on one of the machines. Of course, that makes sense, because I only put the sleep in the LibraryNode::DoBuild() function.

Obviously, this is a terrible solution, but I'm at a bit of a loss at this point.

Theoretically, I could also try looking for timestamps that are not precisely correct, but within some tolerance, but that feels hacky.

Could we use a "Time Created" file timestamp and store that in the database instead? We could use SetFileTime() to specify the creation time of the file. And just stop using Last Written time, which looks like it's vulnerable to OS/Drivers/Security software. What do you think?

**Comment by ChrisRedacted** [comment]
Thinking about that more, that seems not entirely reliable. If some other process would come along and modify the file, then the creation timestamp would not change, but it's still dirty and needs to be rebuilt. Yuck.

**Comment by ffulin** [comment]
It's difficult for me to suggest a fix or work around right now because I don't really understand what the cause of the problem is or exactly what's going on. I don't have any additional suggestions above trying to figure out what's different between the working and non-working machines to try to figure this out.

I do think we need to continue to use the modification time (as opposed to things like the creation time) because that's what is modified when software we do not control is used to edit files.

With respect to the WorkAroundForWindowsFilePermissionProblem, that's for a very specific case which I don't think applies here. For completeness, the situation I (reliably) saw was:
 - FASTBuild writes a file, preparing it for use by another process (like the compiler)
 - Poorly written antivirus/security software sees the file change and opens it for scanning (without using OpLocks and seemingly locked exclusively)
 - FASTBuild invokes the compiler which fails to open the file because it's in use
The work around allowed FASTBuild to absorb the failure and hide it from the toolchain/compiler.

**Comment by bburgin** [comment]
If you want to know what driver (within the System process) is causing the file write, xperf should be able to show file i/o stacks:
https://randomascii.wordpress.com/2012/11/21/the-lost-xperf-documentationdisk-usage/

**Comment by ChrisRedacted** [comment]
So I verified that antivirus/security stuff is not causing the problem.

But I did manage to come up with a solution that appears to work: forcing the affected files to flush to disk before getting the last modified timestamp for those files.

I created a new function right beside FileIO::WorkAroundForWindowsFilePermissionProblem:

    /*static*/ bool FileIO::EnsureFileFinishedWriting( const AString & name )
    {
        // Sometimes, files are doing asynchronous IO, and the file is not finished
        // writing to disk when we grab the last written time of the file. This was
        // happening with building LIB files and EXE files. As a result, the last
        // written time of the file on disk was always newer than the last written 
        // file timestamp that was stored in the FDB. Thus, Libraries and Executables
        // were constantly considering themselves dirty, and needing to rebuild.
        HANDLE hFile = CreateFile( name.Get(), GENERIC_WRITE, FILE_SHARE_WRITE, nullptr,
            OPEN_EXISTING, 0, nullptr );
        if ( hFile == INVALID_HANDLE_VALUE )
        {
            return false;
        }

        FlushFileBuffers( hFile );
        CloseHandle( hFile );
        return true;
    }

And then I inserted calls to this function at the end of the DoBuild() functions for LibraryNode and LinkerNode, right before we record the last write time. Perhaps there's a more elegant way to do this, but this did seem to resolve the issue for everybody.

**Comment by ffulin** [comment]
To recap things, to be sure I understand, we have the following:

On some machines we have normal/expected behavior:
 - lib.exe (or link.exe) writes the output file
 - FASTBuild opens the file and gets a modification time

On other machines we have unexpected behavior:
 - lib.exe (or link.exe) writes the output file
 - FASTBuild opens the file and gets a modification time
 - something else (via the "system" process) performs some operation on the file that alters the modification time

If that's right, and we don't know what this "system" process is, then it's hard to know if the work-around you proposed is acceptable, or whether it's even an actual robust work-around, because we still don't truly understand what's going on.

I think @bburgin's suggestion to use xperf to try to figure out what is doing the additional file operations is a good one. Bruce Dawson's blog has several great posts on how to use xperf and he has made some great tools to make it easy to use.

**Comment by ChrisRedacted** [comment]
Your recap is correct. Except for the last bullet point, which is what I thought was happening, but which wasn't what it looked like when I took @bburgin's suggestion.

After quite a bit of digging with such tools, it appeared that the behavior of "lib.exe" in how it was dealing with the file system was simply slightly different between our two different computers. There was no rogue "system" process that was doing things differently between our two computers.

I even had him upgrade to the latest possible version of VS2015, but that also did not fix the problem. It is odd that lib.exe was acting differently on the two machines. I couldn't find any reason why it should. Eventually, I had to just give up and check in my "fix", and move on to other things that needed to get done.

**Comment by ChrisRedacted** [comment]
I always intended to go back and spend more time on it, but just never got around to it. Here's an example of how things were different. I think this was the first difference.

![image](https://user-images.githubusercontent.com/21223712/71299539-67dcc200-2353-11ea-8fbc-d46b786d5bd3.png)

And things just tended to diverge from there.

**Comment by ffulin** [comment]
Going through old issues to try and clean up the backlog.

I wonder if either of these things are in play:
**a) file system** 
FAT vs NTFS for example. This could potentially explain granularity of time stamps.

**b) incremental linking**
This could explain differences in link.exe stacks seen in ETW (since that is a sampling profiler, it'll be imprecise anyway)
It could also explain differences in file access patterns.

Also, I wonder if this is still an issue for you if you are using a newer compiler version?

**Comment by ChrisRedacted** [comment]
Hi! I strongly do not believe that it was file system stuff. We all use the same file system. I also don't believe it was incremental linking, since we were all doing the same stuff, but by now, this was quite some time ago, and I may have forgotten things we tried. We really tried to make sure that it was an apples-to-apples comparison. 

Ever since I put in my fix (that I proposed here), nobody at our studio ever reported the problem again. Things have certainly changed since I reported this. Do we still need the fix? I honestly don't know. Since things are working and my fix doesn't seem to cause any harm, I'm inclined to leave it in as is for now, rather than risk taking it out just to see if it'll cause other people to suddenly have compile issues. I never actually had the problem on my own computer.

**Comment by ffulin** [comment]
Thanks for the reply. I don't have any more ideas, and without a repro and without understanding the root cause there's probably not much more that can be done (at least for now). I completely understand you probably don't want to rock the boat on your side.

With that in mind, I'm going to close this issue for now. We can always re-open, or create a new issue if needed.
