### ISSUE TITLE
[Question] Exclude project from Configuration

### ISSUE THREAD

**Issue by AntoineConffx** [fastbuild/fastbuild#659]
I've been setting up Fastbuild with our framework which is using Visual studio on Windows and we have different configurations building different sets of projects within the same solution.
I'm wondering if it's possible to exclude specific projects from specific configurations ?
I've been basing off my bff files on the Fastbuild source code and bff files that are found there but I can't seem to find any example showcasing how to exclude from a specific target / alias.

Thank you !

**Comment by lucianm** [comment]
I'm using something like this for generating 2 Visual Studio solutions from the same target tree, just because on our build server, I cannot feed the "big" one of the two, due to lack of proper support for several external type project types present in it. Therefore, I'm generating a smaller one which still contains a wrapper project around the root FASTBuild target. I can imagine, something similar can be achieved even for FASTBuild targts themselves. For this, I used `#define`-ed and then `#undef`-ined a variable **GENERATE_FOR_IDE** like in the following example:


```
// SERVER BUILD solution
VSSolution( 'FASTBuild_All-sln' )
{
	.SolutionOutput	= 'FASTBuild_All/hIC_FASTBuild_All.sln'
	#include "FASTBuild_All\CommonSolutionContents.bff"
}

// COMPLETE solution
VSSolution( 'FASTBuild_All_IDE-sln' )
{
	#define GENERATE_FOR_IDE
	.SolutionOutput	= 'FASTBuild_All/hIC_FASTBuild_All_IDE.sln'
	#include "FASTBuild_All\CommonSolutionContents.bff"
	#undef GENERATE_FOR_IDE
}
```

and then, in `CommonSolutionContents.bff` I'm distinguishing by that variable in populating the solution, like in the following fragment:

```
		#if !GENERATE_FOR_IDE
		.Projects = {
			'FASTBuild_BuildAll-vsproj'
		}
		#endif
		#if GENERATE_FOR_IDE
		.Projects = {
			'FASTBuild_BuildAll_generated-vsproj'
			'FASTBuild_UpdateAll-vsproj'
			'FASTBuild_BuildAll-Types-NoTests-vsproj'
			'FASTBuild_BuildAll-Utils-NoTests-vsproj'
			'FASTBuild_BuildAll-Core-NoTests-vsproj'
                 }
```

I hope this gives you an idea of what can be achieved.

**Comment by AntoineConffx** [comment]
@lucianm 
Thanks for helping out.  
So I came up with a similar solution where I just use Booleans to drive Targets and Dependencies, mainly controlling the list of Libraries. This enables targeting configurations with specific variants of each executable but will still build all the projects for all targets. 
It's not ideal but kinda works for now.  

Solution looks like this:
```
If( .IsVK ) {
    ^Dependencies   + 'RendererVulkan-$Platform$-$BuildConfigName$'
                    + 'SpirvTools-$Platform$-$BuildConfigName$'
    ^ExtraLinker    + ' /LIBPATH:"^$(VULKAN_SDK)\Lib\"'
                    + ' vulkan-1.lib'
} 

If ( .IsDX12 )
{
    ^Dependencies + 'RendererDX12-$Platform$-$BuildConfigName$'
    ^ExtraLinker  + ' "$_BFF_DIR_$../../Common_3/ThirdParty/OpenSource/winpixeventruntime/bin/WinPixEventRuntime.lib"'
}
```

**Comment by AntoineConffx** [comment]
Will close this.
