### ISSUE TITLE
Error "Node is not an ObjectNode" when compiling auto-generated CPP file

### ISSUE THREAD

**Issue by john-blackburn** [fastbuild/fastbuild#661]
I am trying to build the "calculator" example that comes with Qt. (on my computer this example is at C:\Qt\Qt5.3.1\Examples\Qt-5.3\widgets\widgets\calculator). To do this I need run MOC on the .H files and compile the resulting moc_*.cpp files along with the original CPP files. Here is my full fbuild.bff:

```
.msvcPath='C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\amd64'

Settings
{
   .AllowDBMigration_Experimental=true
}

Compiler("moc")
{
   .Executable="C:\Qt\Qt5.3.1\5.3\msvc2013_64\bin\moc.exe"
   .CompilerFamily="custom"
}

.Compiler ='$msvcPath$\cl.exe'
.CompilerOptions='-nologo -c -Fo"%2" "%1"'
                + ' -Zm200 -Zc:wchar_t -FS -Zi -MDd -GR -W3 -w34100 -w34189 -EHsc'
                + ' -DUNICODE -DWIN32 -DWIN64 -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_OPENGL_ES_2 '
                + ' -DQT_OPENGL_ES_2_ANGLE -I"C:\Qt\Qt5.3.1\5.3\msvc2013_64\include"'
                + ' -I"C:\Qt\Qt5.3.1\5.3\msvc2013_64\include\QtWidgets"'
                + ' -I"C:\Qt\Qt5.3.1\5.3\msvc2013_64\include\QtGui"'
                + ' -I"C:\Qt\Qt5.3.1\5.3\msvc2013_64\include\QtANGLE"' 
                + ' -I"C:\Qt\Qt5.3.1\5.3\msvc2013_64\include\QtCore" -I"."' 
                + ' -I"C:\Qt\Qt5.3.1\5.3\msvc2013_64\mkspecs\win32-msvc2013"'

.Linker='$msvcPath$\link.exe'
.LinkerOptions='/NOLOGO /OUT:"%2" "%1" /DYNAMICBASE /NXCOMPAT /DEBUG /SUBSYSTEM:WINDOWS'
              + ' qtmaind.lib Qt5Cored.lib Qt5Guid.lib Qt5Networkd.lib Qt5Widgetsd.lib Qt5Svgd.lib /LIBPATH:C:\Qt\Qt5.3.1\5.3\msvc2013_64\lib'
                
ObjectList('moc_cpp')
{
   .Compiler='moc'
   .CompilerOptions = ' %1 -o %2'
                    + ' -DUNICODE -DWIN32 -DWIN64 -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB'
                    + ' -DQT_OPENGL_ES_2 -DQT_OPENGL_ES_2_ANGLE -D_MSC_VER=1800 -D_WIN32 -D_WIN64'
                    + ' -IC:/Qt/Qt5.3.1/5.3/msvc2013_64/mkspecs/win32-msvc2013'
                    + ' -IC:/Qt/Qt5.3.1/Examples/Qt-5.3/widgets/widgets/calculator'
                    + ' -IC:/Qt/Qt5.3.1/5.3/msvc2013_64/include -IC:/Qt/Qt5.3.1/5.3/msvc2013_64/include/QtWidgets'
                    + ' -IC:/Qt/Qt5.3.1/5.3/msvc2013_64/include/QtGui -IC:/Qt/Qt5.3.1/5.3/msvc2013_64/include/QtANGLE'
                    + ' -IC:/Qt/Qt5.3.1/5.3/msvc2013_64/include/QtCore -I.'
    .CompilerInputFiles = {'button.h','calculator.h'}
    .CompilerOutputPath='out'
    .CompilerOutputExtension = '.cpp'
    .CompilerOutputPrefix = 'moc_'
}

ObjectList('obj')
{
   .CompilerOptions + ' -Fdout\obj.pdb'
   .CompilerInputFiles={'button.cpp','calculator.cpp','main.cpp','out/moc_button.cpp','out/moc_calculator.cpp'}
   .CompilerOutputPath='out'
   .PreBuildDependencies = 'moc_cpp'
}

Executable('exe')
{
     .LinkerOutput='out\calculator.exe'
     .Libraries={'obj'}
}
```
FASTBuild fails with this error:

`Node 'C:\Qt\Qt5.3.1\Examples\Qt-5.3\widgets\widgets\calculator\out\moc_button.cpp' is not an ObjectNode (type: File)`

However, if I write `ObjectList('obj')` like this:
```
ObjectList('obj')
{
   .CompilerOptions + ' -Fdout\obj.pdb'
   .CompilerInputFiles={'button.cpp','calculator.cpp','main.cpp'}
   .CompilerInputPath = 'out'
   .CompilerOutputPath='out'
   .PreBuildDependencies = 'moc_cpp'
}
```
it works!

So it seems FASTBuild is unhappy with `moc_button.cpp` being both an output and an input. The problem goes away if I don't explicitly mention this file in `CompilerInputFiles` but it would be nice to be able to use `CompilerInputFiles`. (and it's slightly worrying!)

**Comment by ffulin** [comment]
ObjectList creates the outputs "dynamically", to allow things to be discovered at built-time. Even when you specify the list of files explicitly (as you've done on the moc generation case) the output targets are not defined during bff parsing.

The second ObjectList you have specified lists the genersted moc files explicitly, so FASTBuild assumes you are referring to existing files and are defined as "File" nodes at bff parse time. These "File" nodes then conflict with the "Object" nodes resulting in the error you are seeing.

To chain together the dynamic output of one ObjectList to the input of another ObjectList currently requires that the second ObjectLIst discover the inputs dynamically - i.e. use .CompilerInputPath instead of listing the files explicitly.

One of the tests for FASTBuild might serve as a useful example of this: https://github.com/fastbuild/fastbuild/blob/7d0d0d5cae4e82597c27d17e5cee3cdee98898d3/Code/Tools/FBuild/FBuildTest/Data/TestObjectList/ObjectListChaining/fbuild.bff  (Just note that some of the other stuff in the test won't be needed for your use-case and is just there to simplify the test)

It should be possible to improve this case in the future by making ObjectList able to directly take another ObjectList as input by name. This would avoid any chance of mismatches/path errors and would also remove the need for the .PreBuildDependencies that has to be set to guarantee the correct order of output discovery for the second ObjectList.

I hope this makes sense - let me know if I can clarify anything.

**Comment by john-blackburn** [comment]
Thank you for getting back to me so soon. It's good to know this is expected behaviour. I will use .CompilerInputPath in this case.

**Comment by john-blackburn** [comment]
I'd like to reopen this as an issue because I notice FASTBuild can get into a broken state when you are have object lists being consumed by other object lists and you make edits and run FASTBuild repeatedly. You can get "Node is not an ObjectNode" even with correct code because FASTBuild gets confused and the FDB file is corrupted. The only solution is to delete the FDB file.

It's hard to reproduce the bug, but if you start with the example you linked above, 

https://github.com/fastbuild/fastbuild/blob/7d0d0d5cae4e82597c27d17e5cee3cdee98898d3/Code/Tools/FBuild/FBuildTest/Data/TestObjectList/ObjectListChaining/fbuild.bff

run it, make changes, run it again etc, you may see the error. Even if the final state of the BFF is as in your link, FASTBuild may still give the error (ie it fails with correct code). Deleting the FDB and running again fixes the error.

**Comment by john-blackburn** [comment]
OK I've now found a test example which shows the bug. Attached is an fbuild.bff file for the Qt calculator example. If you copy this into the Qt calculator folder  (on my computer it's at C:\Qt\Qt5.3.1\Examples\Qt-5.3\widgets\widgets\calculator) you should be able to build the calculator using 
```
fbuild exe
```
(you will need to adjust `.mscvPath` and `.qtPath` at the top)

However, if you make any changes to the 'moc_cpp' ObjectList (eg add -DFOO to .CompilerOptions) and rerun
```
fbuild exe
```
you will get the error
```
Node 'C:\Qt\Qt5.3.1\Examples\Qt-5.3\widgets\widgets\calculator\moc\moc_button.cpp' is not an ObjectNode (type: File)
```
If you delete the fbuild.windows.fdb file and again run
```
fbuild exe
```
it builds OK.

So it seems any time you make changes to the input ObjectList, you need to delete the FDB. I am using v0.98.

**Comment by ffulin** [comment]
I see you're using: ```.AllowDBMigration_Experimental=true```

This feature has a bug in v0.98 that can cause the DB to get into a bad state, causing incorrect node types in some situations for subsequent builds. This bug was the last remaining problem which kept that feature in the "experimental" state. It's incredibly likely you are hitting this bug.

To verify you could:
a) Disable this option
OR
b) Upgrade to v0.99 where this bug has been fixed. (In v0.99 DB migration is also no longer experimental and is on by default)

For reference, the [changelog ](http://fastbuild.org/docs/changelog.html)for v0.99 lists the fix as follows:
```Fix %s 'is not an ObjectNode (type: File)' error when migrating DB after bff edit```

**Comment by john-blackburn** [comment]
I can confirm the bug has disappeared in v0.99. Thank you very much!
