### ISSUE TITLE
How to have unity isolate files matching a pattern?

### ISSUE THREAD

**Issue by billw2012** [fastbuild/fastbuild#668]
My use case is that we have a large number of files that ust boost python, and these files cause the obj files to exceed coff limits (on old compiler so no bigobj). So I need to isolate a large number of files from unity, and luckily we named these files with a prefix. However I can't see how to isolate by prefix.

**Comment by ffulin** [comment]
The isolation feature of the Unity function is really designed for temporarily building some files outside of unity, usually in association with deoptimization. i.e. to iterate on files you are changing, folding them back into "unity" when done.

While you could sort of use isolation for the use-case you mentioned, what you've described seems more like a "permanent" separation to me. With that in mind, it'd be better to "exclude" those files rather than "isolate" them. There are more options available for path/pattern exclusions.  So you can do something like the following:

```C++
// Define a unity for your library, ignoring anything with your prefix
Unity( 'Unity' )
{
    .UnityInputPath = 'Code/MyLib'
    .UnityInputExcludePattern = '*/boost_*'
    ...
}

// Build a library of both the unity and the "loose" files
Library( "MyLibrary" )
{
    // Build the stand-alone files
    .CompilerInputPath = 'Code/MyLib'
    .CompilerInputPattern = 'boost_*'

    // Build the unity
    .CompilerInputUnity = 'Unity'
    ...
}
```

Does that do what you need?

**Comment by ffulin** [comment]
Seems like this issue is solved, so I'll go ahead and close it. Let me know if you have any further problems and we can proceed as needed (re-opening if necessary etc)
