### ISSUE TITLE
FASTBuild generated VS projects & Google Test Adapter

### ISSUE THREAD

**Issue by claimred** [fastbuild/fastbuild#720]
Is it possible to continue using Google Test Adapter with FASTBuild generated Visual Studio projects? It doesn't seem to be able to discover any GTests in generated solution for some reason. 

Has anyone had any success with it?

**Comment by ffulin** [comment]
One of the projects I'm involved with is using gtest and the test adapter. I vaguely recall that some minor change was needed to the project generation when it was being setup. If I had to guess, it'd likely be the .Output property of the VCXProject() .ProjectConfigs (since that's not otherwise required just to run the test from VS normally)

**Comment by claimred** [comment]
Nice, thank you! .OutputDirectory inside  .ProjectConfig did the trick.

**Comment by ffulin** [comment]
Nice. I'll go ahead and close this issue. We can re-open later if needed.
