### ISSUE TITLE
FASTBuild for offsite / WFH?

### ISSUE THREAD

**Issue by BrodyHiggerson** [fastbuild/fastbuild#723]
Hi,

We're considering using FASTBuild with UE4 (using one of the many integrations out there), but I had some questions in areas with which I hope people here have had experience.

Is FB useful if developers are all working offsite (presume _okay_ internet that can pull down at 10MB/s) at all? We've tried Incredbuild in this scenario, even to the point of having remote workers only able to use the in-office machines as helpers (to avoid cross-WFH slowness) rather than other WFH machines, and it was still much slower than no remote help at all. Is FB somehow leaner in this scenario?

Secondly, what if this were reduced to just the obj cache? We could populate an on-site cache from build machines etc, and have WFH devs pull obj files down to their home PCs. Has anyone tried this? In this scenario, would trying to push files up to the on-site cache from home max out a typical connection / slow down the build / be otherwise not worth it?

Failing all of this, we were thinking about how at least having a local cache on each home PC could help individuals, especially when Unreal decides to dirty itself and wants a full rebuild - hopefully can hit the cache locally pretty well. The above stuff around remote work/access is more of a bonus but advice is appreciated - it would be great if FB could become part of our WFH solution in these trying times :)

Thanks.

**Comment by claimred** [comment]
- I've been using cache locally to efficiently jump from branch to branch, it's alright if you have a fat SSD at hand. The problem with it in our case on one particular codebase, is that calculating cache key i.e. preprocessing is not much easier than compiling the file itself (small files, boost headers).

.LightCache helps immensely though but it crashed from time to time, tried couple of weeks ago. 

- We are using RDP clients, so onsite builds are still distributed like always. Pretty sure -dist won't help us as we have huge object files.

- Speaking of WFH and build times I remember one of Chromium motivations to use Unity being "something has to be done if the project is ever to have active external contributors". With WFH everybody became external contributors. :) We are not a gamedev shop, I don't know if unity builds are applicable in your case.

**Comment by ffulin** [comment]
**General thoughts**

Whether caching or distributed compilation will help ultimately comes down to the properties of your codebase and the connectivity between workers and/or your cache. You'll probably have to do some tests. 

In the past, I've found remote workers did not benefit from the cache or distributed compilation, but they were geographically quite far from the cache/node pool. In the current WFH setup, it's quite possible that most users are geographically still quite close such that with a good enough internet connection, it might be faster in some cases.

Here are some general thoughts:

a) 100mbps internet would likely be a bare minimum to be useful for either distributed caching or compilation. Even for local compilation/caching, a gigabit connection minimum is recommended

b) You'd have to be using Unity to have any chance of coming out ahead (it's already recommended way under normal circumstances)

c) The quality/performance of your VPN will be an additional factor. (you absolutely want to be using one, otherwise you're passing plaintext sourcecode over the internet!)

d) CacheCompression level control is a feature coming in v1.00 (https://github.com/fastbuild/fastbuild/commit/5cd60ce99e1395c93d81ccdedebb7d882b243a02) which might be worth experimenting with. It pretty much allows you to trade compression time for reduced network transfer, which would be particular beneficial if your build system populates the cache for many users (write once, read-many)

e) You can disable caching/distribution on a per-library basis, so if some libraries make sense and some don't you can control this. (see ObjectList() .AllowDistribution and .AllowCaching)

**LightCache**

The LightCache can help all caching scenarios, and this one would be no different. However, this feature is hightly expermental and at the time of writing, contains at least 1 bug which could cause missing rebuilds and 1 crash bug. It's not ready for production yet.

**Local Cache**

If you have a branch switching scenario, or Unreal is unnecessarily dirtying source files, a local cache might be useful. It's really no different to a remote cache: just the path is set locally.

**Comment by diekleinekuh** [comment]
We have the same issue. I just tried distributing with fastbuild but it didn't speed up the build with WFH for me with UE4. 100MBit down/40Mbit up. But incredibuild isn't any better. Both seemed to be limited by upload. Fastbuild was performing slighly slower than a pure local build. Incredibuild made the build much slower.

Setting up a local cache can definitely help though if jumping between branches or you accidently modified an engine header or a rebuild is required because of some HotReload fuckup.

**Comment by ffulin** [comment]
In the same way that v1.00 will expose the compression level used for cache storage (to trade CPU time for network bandwidth), it might be useful to expose the compression level used for distributed compilation transfers to adjust the same sort of tradeoff.

**Comment by ffulin** [comment]
@claimred - I've integrated some fixes (https://github.com/fastbuild/fastbuild/pull/716) which will be in the next release (v1.00). One of those fixes is for a crash that could occur while parsing includes.

**Comment by claimred** [comment]
@ffulin Absolutely great news, thanks! 🕺 I'll try to test our stuff against dev branch, sorry for not reporting the exact crash location though, can't get my hands on it. 

I guess it's time for us to get rid of `#include "$var"` substitutions to be ready for wonderful 1.0.

**Comment by ffulin** [comment]
The next version of FASTBuild (v1.06) will contain some improvements (https://github.com/fastbuild/fastbuild/commit/b963204514b21123a1a159d32711651b8d7c7bbe) to reduce the bandwidth used by distributed compilation. The improvement varies depending on the code architectures and style, but when results are returned, the size of the data is reduces between 40% and 80%. The overall impact on bandwidth usage is between 20 and 40%.

This should help in scenarios where network bandwidth is constrained.

This combined with the previous bug fixes means we can probably close this issue, but I'll leave it open until that version is released.

**Comment by ffulin** [comment]
v1.06 has now been released.
