### ISSUE TITLE
UnityPCH and UnityInputIsolateWritableFiles

### ISSUE THREAD

**Issue by ChrisRedacted** [fastbuild/fastbuild#724]
UnityPCH places an include at the top of a unity file, so it sort of acts as a "forced include". But UnityInputIsolateWritableFiles pulls files out of unities. I assumed that in those cases, we were passing the equivalent of a /FI to the isolated files, or we were creating single file unities, but neither one of those things appears to be the case.

So these two options don't seem to place nicely together? Am I missing something?

**Comment by ffulin** [comment]
When using a pre-compiled header, the first include in the file should (or even must) be for the PCH. For all the files you author, it's expected you have already placed the PCH include first and can compile using the precompiled header successfully.

A Unity cpp file generated by FASTBuild to accelerate compilation of those files must include the PCH first as well, and that's why it's generated with one (specified with the UnityPCH option you mentioned). This makes the PCH include in each cpp file redundant, but that's not a problem as it's trivially skipped by the compiler.

When isolating a file out of Unity, it falls back to compiling that isolated file as if it was never in Unity in the first place, so still requires your include of the PCH to be present.

So these options are indeed designed to work together, and do so quite well in the cases I've seen. How does your setup differ to what I've mentioned above? What aspect of this isn't working as you expect?

**Comment by ChrisRedacted** [comment]
I see. Now I realize I misunderstood what was going on with precompiled headers. 

I thought that UnityPCH was more of a new-and-improved fastbuild-ified implementation of precompiled headers than a system to make unity files work with precompiled headers. What I remember finding during the conversion process from MSBuild to fastbuild many eons ago, was that (thanks to unity files) many things actually appeared to build faster if I only set the .UnityPCH variable and nothing else. In those days, I wasn't using isolate writable files, so it wasn't an issue. So I wound up using UnityPCH as a force include that didn't require a compiler option.

In the one library where precompiled header files did make things faster, I wound up using the /FI compiler option to make it work, instead of .UnityPCH.

Because of all that, force including and precompiling became conflated for me to the point where I started assuming that precompiling essentially implied force including.

You would think that if compilers were going to complain that the precompiled header should be included before every other include, then they would...just do it. Instead of complain about it and not do it.

Anyway, thanks for the answer.

**Comment by ffulin** [comment]
fwiw, most of the code I deal with doesn't use precompiled headers as the Unity gives you the same upside in most cases, without the downsides of PCH maintenance, bloat over time and unnecessary rebuilds. Unity is a kind of self-regulating PCH in a way.

Historically, a big downside of Unity vs PCH was the iteration time on edits, but with isolation of modified files, that isn't a problem either, striking up another plus for Unity over PCH.

Having said this, I do still use PCH occasionally for some libraries where it's been proven to be a speedup though. The main project I work on has one library using PCH with Unity and all other libraries just using Unity.

**Comment by ffulin** [comment]
Based on your most recent reply, I think we're good to close this issue. Let me know if there's anything outstanding and we can re-open or deal with that as appropriate.

**Comment by ChrisRedacted** [comment]
Yeah, feel free to close this.
