### ISSUE TITLE
Building UE 4.24: slower with FASTBuild

### ISSUE THREAD

**Issue by peterwoytiuk** [fastbuild/fastbuild#725]
I'm building Unreal Engine 4.24 using a FASTBuild integration based on the one by [liamkf ](https://github.com/liamkf/Unreal_FASTBuild) updated to support VS 2019.  My main machine is a Xeon W-2195 (36 logical cores) which can build Unreal in ~900 seconds.  I have added a ThreadRipper 2990WX (64 logical cores) and with 100 total cores through FASTBuild it takes ~1200 seconds to build.  Both machines have 64 GB of RAM, NVMe SSDs with plenty of space, and a confirmed working 1 Gbps link.  I have built a version of FBuild.exe with the latest PCH fixes from the master branch which unfortunately didn't make any time difference.  FBuild is being launched from the UBT with these options: '-dist -report -monitor -summary -ide -clean'.  I also tried adding -distverbose as well as watching the progress with [FASTBuild Monitor](https://github.com/yass007/FASTBuildMonitor) and there weren't any obvious problems.  Any advice would be appreciated.

One interesting thing I noticed was that setting the worker machine to have 50% CPU allocation instead of 100% made almost no difference to the compile time.  Even at 50% through FBuildWorker the actual CPU usage through Windows' Task Manager would still regularly hit 100% with nothing else running on the machine, shown below.
![50PercentCPUAllocation-100PercentUsage](https://user-images.githubusercontent.com/56612898/78197795-4489de80-743b-11ea-9c2a-8cc39fd39d08.png)

**Comment by budgidiere** [comment]
Could you please share the changes you made to get It to work with UE4.24

**Comment by budgidiere** [comment]
oh i forgot i have to mention people @peterwoytiuk

**Comment by diekleinekuh** [comment]
I'm also looking into fastbuild at the moment with UE4 4.24. I'm currently testing with seven Ryzen 3700X as helpers. For me building is accelerated but less than expected. Speed is very dependent on network speed too. When I was trying the same from home office with only 100MBit down 40Mbit up distributing the build wasn't any faster (actually slower). But then you should see the network of either side being saturated.

I just used the 0.99 release. My UE4 integration is probably very different. I also started from the one linked above but almost completely rewrote it as it didn't work together with the dependency tracking UE4 does nowadays with this cl-filter.exe and shader compilation wasn't existing.

I have a direct comparison to incredibuild here. The whole editor/game + support utilities take 20m with fastbuild and 10m with incredibuild. For me fastbuild isn't able to feed the workers as quickly as incredibuild. But I will look into it more if I find the time.

**Comment by budgidiere** [comment]
@diekleinekuh Would you share your changes?

**Comment by ffulin** [comment]
FASTBuild uses the preprocessor for distributed compilation, which means it cannot use precompiled headers remotely. This means that some remote resources are essentially needed to break-even before seeing an improvements.

Normally this is ok, but for some particular cases it might require a surprising amount of extra cores just to break even. Specifically, the size of the PCH in relation to the object that uses it is the biggest factor at play.

For an example, take the following files:
 - pch.cpp
 - fileA.cpp
 - fileB.cpp
 - fileC.cpp

If the pch takes 1 second and the files take 10 seconds each, the remote overhead is effectively 10%, which is easily regained by one or two cores with every other core being a speedup.

On the other hand, if the pch takes 10 seconds, and each cpp file takes 1 second, it might never be possible to break even because all the overheads start to add up to more than is being saved by distribution.

I'm not sure what the split looks like for Unreal, or whether it can be controlled to favor the former case by tuning the size of the "unity" files for example but perhaps that might be a way to improve this situation here?

*> One interesting thing I noticed was that setting the worker machine to have 50% CPU allocation instead of 100% made almost no difference to the compile time.*

This is normal for a few reasons:
 - not all CPU cores are equal. Twice as many cores doesn't come anywhere near twice the performance.  CPU internals are often shared (hyperthreading etc), as are caches and bus bandwidth.
 - many compilers use more than one thread

There two things, plus the potentially high memory usage of compiler processes, is why FASTBuild defaults to 50% CPU allocation (it's usually the "real" CPU core count).

*> Even at 50% through FBuildWorker the actual CPU usage through Windows' Task Manager would still regularly hit 100% with nothing else running on the machine, shown below.*

This is quite possibly due to the msvc compiler using multiple threads (I believe upto 4 by default). This can be controlled by /cgthreads.  This, plus the core count allocated to FASTBuild may be worth experimenting with.

Unfortunately, the msvc compiler has no limits on threads created by multiple processes. It would be ideal if that actually load balanced things properly.

**Comment by udevel1** [comment]
> Could you please share the changes you made to get It to work with UE4.24
Upvote on this comment @peterwoytiuk, tell us please how did you make it to work with Epic's link-filter.exe?

**Comment by udevel1** [comment]
Upvote on this comment @peterwoytiuk, tell us please how did you make it to work with Epic's link-filter.exe
> Could you please share the changes you made to get It to work with UE4.24

**Comment by ffulin** [comment]
I don't think there is anything actionable on the FASTBuild side for this issue, so I'm going to close it for now. Please let me know if that's not the case and we can re-open this or create a new issue as needed.
