### ISSUE TITLE
Unity builds and symbols indexing

### ISSUE THREAD

**Issue by claimred** [fastbuild/fastbuild#726]
Do unity builds play well with Post-Mortem debugging techniques such as[ source indexing for symbols](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/source-indexing)? I am not that well-versed in ssindex.cmd, but I get that it modifies .pdb files to be path agnostic i.e. write exact commands for debugger to get correct source file from the VCS & writes corresponding revision info that it gets from the VCS. 

Won't there be a path confusion somewhere in case of unity builds? Unity*.cpp files aren't meant to be under version control if I understand correctly.

**Comment by ffulin** [comment]
The Unity files are indeed not under source control (they are temporary build artifacts). This is fine however, because they don't generate any symbols as they are just wrappers around includes of the actual files. All the symbols are still attributed to the real source files which are under source control.

I have not seen any issues with symbol indexing (or symbol servers) related to use of Unity.

**Comment by ffulin** [comment]
As this question has been answered, I'm going to go ahead and close this issue. Let me know if you need any more info about this.
