### ISSUE TITLE
Variables inside include paths

### ISSUE THREAD

**Issue by Domain** [fastbuild/fastbuild#738]
I just know v1.00 no longer support this feature. But my project use this everywhere. Can you tell me how to revert this change? I must maintain my local version.

**Comment by ffulin** [comment]
I'm sorry for the trouble this change has caused you.

Supporting #includes with embedded variables was not a feature that was removed that can be simply reverted. This change was the result of a complete re-write of the bff parser. The parser became a two-phase parser (like C/C++) in order to fix many long standing behavioral and maintenance issues with the language. The primary change was a significant one (https://github.com/fastbuild/fastbuild/commit/a17139c2b03c10bf26d05dc1754562fc2386fc5f) and several changes are built on top of/require that. Given enough time, you could conceivable try to revert that base change locally, along with dependent changes, but it will be very very difficult.

In the short term, I would recommend staying on v0.99 until you are ready to update your bff files. If v1.00 contains a change that you need, then you could likely backport that to v0.99 with reasonably effort (as long as it's not dependent on the new bff parsing of course).

If there are changes that can be made for the next version that will make it easier for you to update your bff files, by adding new language features or improving existing ones, please let me know. v1.00 contains several language extensions that are designed to do just this and I'll prioritize additional changes that might ease the pain of this transition.

Additionally, if you have some patterns relying on this old #include behavior that you are unsure how to update, please let me know if I will provide any guidance I can to help.

**Comment by Domain** [comment]
OK. I have updated my bff files.
