### ISSUE TITLE
Compiling seems to happen twice

### ISSUE THREAD

**Issue by NicoJanE** [fastbuild/fastbuild#749]
Hallo,

In Using a Windows 10 system and Visual studio 2019 compiler to compile some projects with Fastbuild. After setting up the different project they compile and build correct. But the times are disappointing. So I looked into that and notice that the files get compiled on the local machine but also on the distributed machine  
![image](https://user-images.githubusercontent.com/65861310/82757900-9a4b8900-9de3-11ea-8ee8-fded38319f1c.png)

What I'm doing wrong, any guess?  

Thanks for the past and present effort!

Best regards 
Nico Jan

**Comment by ffulin** [comment]
The first line is the local preprocessing, preparing the code for distribution. The second line is the actual remote compilation. The output is normal and expected.

With the information given, it's difficult to say why your performance might be less that expected, but here are some thinks you can look into:

**a) Unity**

Unity reduces the overhead of compilation of individual files and massively speeds up compilation for local builds, but also greatly reduces the overhead of distributed compilation. I usually recommend this as a first step to improve compile times, as it can improve them by as much as 10x even for local builds.

**b) Machine performance & count**

Distributed compilation adds some overhead to compilation. The total CPU power of your pool must be large enough to make compile times faster overall. The break even point depends on the compiler, code and compilation settings. Sometimes a single machine will is enough to see a benefit, while other times it may take several. Naturally, if the workers are less powerful that the host machine, compilation can suffer.

**c) Precompiled headers with MSVC**

If you use precompiled headers with the MSVC compiler, those are disable for the remote tasks due to limitations around how the MSVC compiler works. With Unity, this is usally a non-issue, but in the worst-case, non unity with very large precompiled headers, it may not be possible to

**d) Network bandwidth**

A 1Gbps network is recommended. Depending on the nature of the code, a 100 Mbps network may be enough to yield improvements, but usually a 1 Gbps network is required. As with most throughput and latency sensitive things, Wi-Fi is a performance killer.

**Comment by ffulin** [comment]
I'm going to close this issue as answered. Please let me know if you have any more questions.
