### ISSUE TITLE
Override compiler flags on per file basis

### ISSUE THREAD

**Issue by emoon** [fastbuild/fastbuild#76]
Hi,

I wonder if it's possible to override settings an a per file basis?

Say that you have something like this

```
.CompilerInputFiles  = { "file0.cpp", "file1.cpp " }
.Section 
{
   // These files needs to have opts disabled.
  .CompilerFlags = "-O0"
  .CompilerInputFiles  = { "file2.cpp", "file3.cpp " }
}
```

Is that possible?

**Comment by ffulin** [comment]
Hello

You can indeed specify per-file compilation flags. There are a couple of ways to do this, depending on what you want as the final output.

If you still want to create a single library, you do this by separating out the unique files into one of more ObjectLists. For examaple:
```C++
.ObjectList( 'Lib-SpecialFiles' )
{
    .CompilerOptions = '-O0'
    .CompilerInputFiles = { 'file0.cpp', 'file1.cpp' }
}
Library( 'Lib' )
{
    .CompilerOptions = '-02'
    .CompilerInputFiles = { 'file2.cpp', 'file3.cpp' }
    LibrarianAdditionalInputs = 'Lib-SpecialFiles'
}
```

If your files follow a nice naming pattern, or are split by directory, you can use the CompilerInputPath or CompilerInputPatterns instead of listing them explicitly.

A common pattern, when only a few files in a library need unique settings, is as follows:
```C++
.SpecialFiles = { 'thing.cpp', 'stuff.cpp' }
.ObjectList( 'Lib-SpecialFiles' )
{
    .CompilerOptions = '-O0'
    .CompilerInputFiles = .SpecialFiles 
}
Library( 'Lib' )
{
    .CompilerOptions = '-02'
    .CompilerInputPath = 'Code/Lib/'
    .CompilerInputExcludedFiles = .SpecialFiles
    LibrarianAdditionalInputs = 'Lib-SpecialFiles'
}
```

You can of course split your library into as many ObjectLists as required.

**Comment by emoon** [comment]
Just what I wanted to know. Thanks!
