### ISSUE TITLE
Failed to build Object. Error: 1 (0x01) Target: ...

### ISSUE THREAD

**Issue by fraespre** [fastbuild/fastbuild#761]
Hi,

I'm using the 1,01 version of FasBuild for Windows.

During the compilation of the Local project, every worker end with error:

`
4> -Build: 0 ms C:\mio\soft\dev\z80\wrks\zxspectrum\batsp1\src\sys\SoundFxSys.c
`
...
`
4> Obj: C:\mio\soft\dev\z80\wrks\zxspectrum\batsp1\bin\SoundFxSys.o
C:\mio\soft\dev\z80\z88dk-2.0\bin\zcc.exe +zx -v -preserve -startup=31 -clib=sdcc_iy -SO3 --opt-code-speed -pragma-include:C:\mio\soft\dev\z80\wrks\zxspectrum\batsp1\src\zpragma.inc -c "C:\mio\soft\dev\z80\wrks\zxspectrum\batsp1\src\sys\SoundFxSys.c" -o "C:\mio\soft\dev\z80\wrks\zxspectrum\batsp1\bin\SoundFxSys.o"
`
...
`
4> PROBLEM: C:\mio\soft\dev\z80\wrks\zxspectrum\batsp1\bin\SoundFxSys.o
z88dk-zpragma < "C:\mio\soft\dev\z80\wrks\zxspectrum\batsp1\src\zpragma.inc" > nul
PROCESSING C:\mio\soft\dev\z80\wrks\zxspectrum\batsp1\src\sys\SoundFxSys.c
zsdcpp -iquote"." -D__Z88DK -D__SPECTRUM -DSPECTRUM -D__SPECTRUM__ -D__Z80 -DZ80 -D__SDCC -D__SDCC_IY -isystem"C:\mio\soft\dev\z80\z88dk-2.0\lib\config\..\..\\include\_DEVELOPMENT\sdcc"  -D__SDCC  "C:\mio\soft\dev\z80\wrks\zxspectrum\batsp1\src\sys\SoundFxSys.c" "C:\Windows\Temp\zcc3ED02.i2"
`
4> **Failed to build Object. Error: 1 (0x01) Target:** 'C:\mio\soft\dev\z80\wrks\zxspectrum\batsp1\bin\SoundFxSys.o'

The command used is "fbuild all -distverbose -verbose"
And if I execute manually the same compilation command launched by the worker, it works succefully.

Well, it's difficult for me to try to fix the problem if the FastBuild tool don't show more details about the error.
What can I do ?

Regards and thanks in advanced,

**Comment by ffulin** [comment]
When a task fails remotely, FASTBuild sends back all the output from the remote process as well as the error code and prints them both. If FASTBuild prints only Error (0x01) with no other information, it means it failed to spawn on the remote host or the process exited with no additional information.

I'm assuming local compilation works, and you only have problems when using -dist?
If so, there are two avenues to investigate:

1. I notice that in your second command line you seem to have some redirections. There seems to be one redirection from a local input file and one pipe to nul. These are unlikely to work correctly remotely. Additionally, it may be indicative of dependency tracking problems even with local builds.  I'd probably need to see your bff files to understand more about what's going on.

2. Compilers that have dependencies on dlls and other local files need to have those specified in the Compiler() to function correctly. Missing dependencies can often result in hard to diagnose early exits on remote hosts.

**Comment by fraespre** [comment]
Sorry @ffulin , I think that I didn't expressed well.
All my problem happens when I launch the Local compilation. I haven't tested the remote compilation.

**Comment by ffulin** [comment]
From the output you have provided, it seems like you might have removed some line breaks from the output, which caused me some confusion. It seems that when FASTBuild invokes this command line:
```
C:\mio\soft\dev\z80\z88dk-2.0\bin\zcc.exe +zx -v -preserve -startup=31 -clib=sdcc_iy -SO3 --opt-code-speed -pragma-include:C:\mio\soft\dev\z80\wrks\zxspectrum\batsp1\src\zpragma.inc -c "C:\mio\soft\dev\z80\wrks\zxspectrum\batsp1\src\sys\SoundFxSys.c" -o "C:\mio\soft\dev\z80\wrks\zxspectrum\batsp1\bin\SoundFxSys.o"
```
The zcc.exe process returns 1 and outputs the following:
```
z88dk-zpragma < "C:\mio\soft\dev\z80\wrks\zxspectrum\batsp1\src\zpragma.inc" > nul PROCESSING C:\mio\soft\dev\z80\wrks\zxspectrum\batsp1\src\sys\SoundFxSys.c zsdcpp -iquote"." -D__Z88DK -D__SPECTRUM -DSPECTRUM -D__SPECTRUM__ -D__Z80 -DZ80 -D__SDCC -D__SDCC_IY -isystem"C:\mio\soft\dev\z80\z88dk-2.0\lib\config\..\..\\include\_DEVELOPMENT\sdcc" -D__SDCC "C:\mio\soft\dev\z80\wrks\zxspectrum\batsp1\src\sys\SoundFxSys.c" "C:\Windows\Temp\zcc3ED02.i2"
```
If the compiler doesn't provide any more information about the problem, it will require some trial an error to figure out.

It seems from the info you've provided that zcc.exe tries to invoke another processes (z88dk-zpragma presumably) and that process fails. My best guess is that something about the environment is missing. Perhaps some environment variables are missing (commonly the PATH is an issue).

Depending on how you have it configured, FASTBuild will supress the env from the compiler. This is usually desirable because it means you can be sure you are not relying on machine specific state in your compilation. (That's commonly the reason it might work when you invoke the command line directly - it then has whatever PATH etc is set on your local machine).

Usually, to debug an issue like this, I start by getting a list of all the env vars present in the shell and temporarily adding them to the FASTBuild .Environment in Settings().  If compilation then succeeds, you can remove env vars until it works. It sounds laborious, but usually only takes half an hour or so).

Perhaps you can give this a try?

Failing that, if you can create a standalone test (one bff and one .c file that repros the problem with a download of zcc.exe) I could take a look for you.

**Comment by fraespre** [comment]
Thanks for your help @ffulin
