### ISSUE TITLE
Bad error message when missing '

### ISSUE THREAD

**Issue by emoon** [fastbuild/fastbuild#77]
With this code (missing ' at the end of something)

```
.Test =
[
    .Foo = 'something
    .Bar = 'other'
]
```

One gets this error

```
fbuild.bff(30,1): FASTBuild Error #1002 - Matching closing token ] not found.
```

Which is a bit misleading as it's a ' that is missing and not a ]

**Comment by ffulin** [comment]
FASTBuild allows whitespace inside strings to include carriage returns. As a byproduct of this, it can be difficult to differentiate between errors in cases like this. 

In your specific example, FASTBuild believes the first string continues to the next line and includes the ".Bar =". The final ' is actually considered to be the start of a new string, which the closing ] is then seen as part of, so to FASTBuild the "outer-most" problem is that the .Test struct is never terminated with a ], which is the error it reports.

It might be possible to report the "inner most" error instead, though I'd need to think about whether there are other situations that are more obvious that would be obfuscated by that.

Another possibility would be to disallow carriage returns inside strings, since that isn't particularly useful for the type of string manipulation normally needed in FASTBuild config files.

**Comment by emoon** [comment]
I see. Another way to allow carriage returns is to have a special character for it like

```
.foo = 'something \
           something more'
```

In some cases it's nice to have things more lined up esp if you for example lots of defines or command line options. One could always do it like this

```
.foo = 'something`
.foo + 'something more'
```

But then I think the first approach is a bit cleaner.

And yes even if missing a ` is a stupid user error it's a bit confusing when it complains about a missing ] even if I see the reason now.

**Comment by emoon** [comment]
Oh nevermind. I see that + on the next line is actually supported so that should be enough.

**Comment by Manuzor** [comment]
You can even do this already:

```
.foo = 'something'
     + 'something more'
```

No need to specify `.foo` again.

**Comment by ffulin** [comment]
The bff parser was significantly re-written in v1.0 (May 2020), but I didn't check this behavior with respect to this issue at that time.

As of v1.02, the snippet provided for this issue now results in:
```C++
C:\test\fbuild.bff(3,12): FASTBuild Error #1002 - Matching closing token ' not found.
    .Foo = 'something
           ^
           \--here```

With that in mind, I think this issue can be considered resolved.
