### ISSUE TITLE
.ExcludePattern behaviour

### ISSUE THREAD

**Issue by claimred** [fastbuild/fastbuild#771]
I found a seemingly weird ExcludePattern use case.
Suppose we have a file `moc_file.cpp`

1) `.ExcludePattern = '*_file.cpp' // moc_file.cpp is excluded`
2) `.ExcludePattern: 'moc_*.cpp' // moc_file.cpp is **not** excluded`
3) `.ExcludePattern: '*moc_*.cpp' // moc_file.cpp **is** excluded`

The thing is that the second argument passed to `PathUtils::IsWildcardMatch` here https://github.com/fastbuild/fastbuild/blob/master/Code/Tools/FBuild/FBuildCore/Graph/DirectoryListNode.cpp#L189 contains full path. Is that a bug?

**Comment by ffulin** [comment]
The pattern is matched against the path. This is intentional, so that you can have exclusions based on sub-directory names as well as file names. For example:
```.UnityInputExcludePattern = '*/SubDir/*.cpp'```

Perhaps in your case you would want something like this:
```.ExcludePattern = '*/moc_*.cpp'```

(Note: Care may need to be taken with the slash if you are on multiple platforms - at a glance it looks like there might be some inconsistent canonicalization of slashes on ExcludePattern on different object types)

**Comment by claimred** [comment]
I see, thanks for the quick answer!

**Comment by ffulin** [comment]
As a follow up to this, I checked the behavior of all the various nodes with respect to the exclusions/filtering params. As I suspected, an number of nodes were not handling slashes in a platform agnostic way. I've fixed that in https://github.com/fastbuild/fastbuild/commit/bd56c970433fb720621a6cfeacd2e5a04fcfb245. This fix will be in the next release (v1.02)
