### ISSUE TITLE
How to set FASTBUILD_BROKERAGE_PATH on Mac?

### ISSUE THREAD

**Issue by nicol233** [fastbuild/fastbuild#773]
I start FBuildWorker , but the  shared folder do not show the worker token
I have used fastbuild well on window, but I'm not familiar with Mac
Can anyone share an example and steps ？Thanks

**Comment by ffulin** [comment]
To use a network cache on OSX (or Linux) requires that you mount the network location (since unlike Windows, a UNC path cannot be accessed directly). You then set the .CachePath location to the local mount, rather than that UNC path.

Optionally, you can also set the .CachePathMountPoint property to the location of the mount, which will enforce that the given path is actually a mount. This is useful to ensure that the .CachePath isn't simply created when missing (as it's valid to have a local cache folder)

**Comment by ffulin** [comment]
I'm going to close this issue as the question has been answered. Let me know if you need any clarification.
