### ISSUE TITLE
Possible improvement: Use /sourceDependencies with latest msvc 16.7 to retrieve dependencies

### ISSUE THREAD

**Issue by belkiss** [fastbuild/fastbuild#777]
Hello!

This cl.exe argument was recently added to vs2019 to extract dependencies info into a .json, and I think it would probably be nice to try and use it instead of parsing the output of /showIncludes

https://devblogs.microsoft.com/cppblog/introducing-source-dependency-reporting-with-msvc-in-visual-studio-2019-version-16-7/

I'll try and investigate if there are any gains to have with it, but wanted to open this in case someone else wants to have a look or have tried and can report :)

Thanks!

**Comment by ffulin** [comment]
I think this could only replace /showIncludes, which is only used in the non-distributed and non-cached case. As far as I know, the cost of parsing the /showIncludes output is very small. Did you see some cases where it was non trivial?

**Comment by ffulin** [comment]
It doesn't seem like there is any particular advantage to use of the new /showDependencies instead of /showIncludes at this time since it's not used in the majority of cases (when distributed compilation or caching is enabled) and when it is used, it's quite fast.

We can re-open this issue or create a new one if a compelling use case is discovered, or if perhaps in the future (modules?) this is needed.

**Comment by ffulin** [comment]
With change https://github.com/fastbuild/fastbuild/commit/baa378f0b44cab2a7ec861ead715196202170b4d FASTBuild is at least compatible with this arg.
