### ISSUE TITLE
Command Line Limit Exceeded

### ISSUE THREAD

**Issue by liudulab** [fastbuild/fastbuild#781]
Note that this issue is similar to #752 but not the same.
Setup:

- on windows 7
- version 1.02
- embedded MCU target 
- cctc as compiler
- cctc as linker
- CompilerFamily is set to custom
- LinkerType doesn't have a cctc option... (I tried msvc and the others, it will show issue 2)

The issue 1:
```
2> FBuild: Error: Command Line Limit Exceeded (len: 123142, limit: 32767) 'output.elf'
FBuild: Error: BUILD FAILED: all
Time: 0.448s
```
This is the Executable step of a Executable node.

I try to set .LinkerForceResponseFile = true , the issue 2
```
2> Exe: output.elf
2> 2> cctc E205: don't know what to do with @..\AppData\Local\Temp\
.fbuild.tmp\0xc412c495\core_2\args.rsp
2> Failed to build Exe. Error: 1 (0x01) Target: 'output.elf'
FBuild: Error: BUILD FAILED: all
Time: 0.612s
```

Thanks for the great tool as always, @ffulin

**Comment by ffulin** [comment]
It seems like your linker either:
a) doesn't support response files at all
OR
b) requires a different syntax for response files

I couldn't find any documentation for this linker so I can't tell which is which.

**a) doesn't support response files at all**

If your linker doesn't support response files at all, the the only option is to reduce the length of the linker command line.

Without seeing your linker command line, some general things you can check yourself:
 - look at path depth to the compiled objects or libraries and see if the path can be shortened
 - if you are linking lots of libraries, look at reducing the number of libraries OR merging some of the libraries before linking
 - if you are linking object files (because you specify them or are using .LinkerLinkObjects), look into linking libraries instead

If you can provide an example of your linker command line (redacted if necessary), I may be able to make some more specific suggestions.

**b) requires a different syntax for response files**

If your linker does support response files, but requires a different syntax (something to replace @filename) then it might be possible to modify FASTBuild to detect your linker and behave as needed. You will need to contact your toolchain vendor, or consult any documentation they have provided to find out if this is the case.

----

NOTE: by using .CompilerFamily and .LinkerType as "custom" FASTBuild will be lacking dependency information which might make it unable to correctly detect when rebuilds are necessary. In addition, a "custom" .CompilerFamily prevents caching and distribution, so you may never be able to achieve the full speed gains FASTBuild can offer.

With the right information about how your compiler and linker behaves, it maybe be possible to fully support them.

**Comment by ffulin** [comment]
I'm closing this issue due to lack of response. We can re-open or create new issues as needed if you'd like to dig into this further.

**Comment by Domain** [comment]
I have the same problem. But in Linux with GCC. Seems gcc doesn't support response file at all. How can I use relative path instead of full path of object files in link command?

**Comment by ffulin** [comment]
If the compiler doesn't support response files, increasing the command line length limit makes sense as a work-around.

In the longer term, I think FASTBuild will move to using relative paths more often, probably starting with an opt-in flag.

**Comment by og4444** [comment]
I have the same problem with Linux GCC, How do you increase the command line length?

**Comment by ffulin** [comment]
It seems FASTBuild will use response files with GCC to fix cmd line length limits, but for historical reasons only on Windows:
That would ideally be fixed in the future with a fairly trivial code change.

In the interim , you can manually tell FASTBuild that response files can be used by setting "AllowResponseFile" on the Compiler() node (documented here https://fastbuild.org/docs/functions/compiler.html)

**Comment by og4444** [comment]
Hi,
Thanks for your reply.
I'm compiling Linux GCC which I don't think support response file.
Do you know how can I increase the limit of command line length as [Domain] commented on Jan 5, 2022?
Thank you,
Ofir

**Comment by ffulin** [comment]
@og4444 

gcc on Linux, at least some version support response files. The version I have (9.4.0) seems to work:
```
$ echo --version >> cmd.rsp
$ gcc @cmd.rsp
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
It's entirely possible FASTBuild doesn't generate response files correctly in some way, or passes them incorrectl. Have you tried using the "AllowResponseFiles" flag as I suggested? What's the result? If there's a problem with that we can fix it.

Also, make sure you are using at least v1.11 - that version had an improvement to the max command line args length limit for Linux.

**Comment by ffulin** [comment]
If there is a bug with response file handling, we should create a new issues as that's unrelated to this already closed issue.

**Comment by og4444** [comment]
Hi,
Thanks for your reply.
When I use response files , i get a problem with the file path all the '\\ are being removed not matter what kind of '\' I used .
This is what i get :

EXEC : 12>Failed to build Object. error : 1 (0x01) Target: 'C:\GitWS\S4_OCB\XXX\generatedFiles\eFW\ECM_Linux\obj\StandbyDefaultActivity.obj'
8>12>PROBLEM: C:\GitWS\S4_OCB\Indigo\generatedFiles\eFW\ECM_Linux\obj\StandbyDefaultActivity.obj
8>arm-fslc-linux-gnueabi-gcc.exe : error : C:GitWSS4_OCBefwSrcECMActivitiesStandbyDefaultActivity.cpp: No such file or directory

The C:GitWSS4_OCBefwSrcECMActivitiesStandbyDefaultActivity.cpp should have been :
C:\GitWS\S4_OCB\efw\Src\ECM\Activities\StandbyDefaultActivity.cpp

any idea why this happen? (without the .AllowResponseFile I dont have this path issue)
Thank you,
Ofir
