### ISSUE TITLE
Bitdefender reports fastbuild.org as unsafe (False Positive)

### ISSUE THREAD

**Issue by kylawl** [fastbuild/fastbuild#81]
Sadly it doesn't provide much information as to why other than "This website contains elements classified as malware"

http://trafficlight.bitdefender.com/info?url=http%3A//fastbuild.org/&language=en_US

**Comment by kylawl** [comment]
It could the the messed up font tag on line 16

**Comment by ffulin** [comment]
Thanks for letting me know.  I've reported this false positive to them via their submission tool (http://www.bitdefender.com/submit/). I received an email saying it should be checked/fixed within 72 hours.

I suspect it's not the specific page, but rather the domain, since their "trafficlight" system gives the same warning for all pages on the website. Maybe it's the executables hosted for download within zip files that they don't like?

virustotal.com shows BitDefender as the only site reporting any problems:
https://www.virustotal.com/en/url/c908c8a31b38575c573cfcd7a6b7cdc7ff7724fbcdf3ef78ba86b83a100116a8/analysis/

**Comment by ffulin** [comment]
The BitDefender trafficlight URL now reports everything is ok (http://trafficlight.bitdefender.com/info?url=http%3A//fastbuild.org/&language=en_US).

I'll keep this ticket open while I monitor things for a few days.

**Comment by ffulin** [comment]
In the end it was BitDefender's heuristic scanner that was incorrectly flagging the Windows x86 executables as suspicious. I submitted the exes to their false-positive reporting page back when you first reported this issue.

They seem to have updated their heuristic scanner and both BitDefender and the VirusTotal aggregator have been reporting fastbuild.org as a clean site for a while now.

**Comment by kylawl** [comment]
Great thanks
