### ISSUE TITLE
macOS: Allow to build FASTBuild for ARM64 on x86_64 (and vice versa)

### ISSUE THREAD

**Issue by awefers** [fastbuild/fastbuild#813]
The build scripts currently limit building of the macOS version of FASTBuild to the current host architecture. The configuration files could be easily adjusted to support building for arm64 on x86_64 and for x86_64 on arm64.

**Comment by awefers** [comment]
(Bonus: Use lipo as additional build step to generate a universal binary).

**Comment by ffulin** [comment]
Assuming the latest XCode and OS X allows cross compilation, it certainly seems we could alter the configs for mac to make things a little more flexible.

I can see 3 possible options:

*1) Keep the configs entirely separate, and continue shipping per-architecture binaries*
This might make it easier for users who build on an older OS where perhaps they cannot build ARM binaries.
This would result in a smaller end-user binary (though the binary is very small and there are other inefficiencies to be solved if we were worried about that).
It would however double the amount of configs.

2) Build separate configs, but merge them into a universal binary
With a specific merging (lipo) invocation target at the end, it avoids some of the problems of option 1)

3) Emit object files with both types of code.
I understand this is possible and might have some (overall) compile time savings. It would make managing the configs easier (since we would just have one set like now). It may even be possible to directly link a universal binary, but I'm not certain. This option would be problematic for users building on old OS X versions most likely.

I think all of these are viable, but I'm probably leaning towards experimenting with option 3.

**Comment by awefers** [comment]
FYI, you have a chicken and egg problem with building the macOS/arm64 version. As of v1.0.4 you can only build the macOS/arm64 version of FASTBuild with arm64 binaries of FASTBuild. So one has to modify build scripts in order to be able to build the macOS/arm64 version with the release binaries for macOS/x86_64 since there are no macOS/arm64 binaries available for download.

**Comment by awefers** [comment]
(also as side note the arm64 builds use the wrong arch in the directory path, for example:  "tmp/x64OSX-Debug/Tools/FBuild/FBuild/FBuild" instead of "tmp/arm64-Debug/Tools/FBuild/FBuild/FBuild").

**Comment by ffulin** [comment]
Note that FASTBuild can already be cross-compiler for arm, but you need to have Clang 12 installed, and modify Clang.bff:
```
#if __OSX__
    #define USING_CLANG_8
    //#define USING_CLANG_12
#endif
```
That should allow you to cross-compile both versions on either platform by compiling the appropriate target.

**Comment by ffulin** [comment]
As of v1.10, FASTBuild on OSX ships as a Univeral Binary with both x86_64 and ARM support.
I forgot to update this ticket at that time, but that change allows compilation of either target on either hots, as well as allowing for generation of the Universal binaries.

Targets use "ARMOSX", "x64OSX" or "OSX" for the platform respectively, for example:
* All-ARMOSX-Release (ARM)
* All-x64OSX-Release (x64)
* All-OSX-Release (Universal)
