### ISSUE TITLE
Xcode Project Generation can create "corrupt" .xcodeproj files

### ISSUE THREAD

**Issue by PixelZealot** [fastbuild/fastbuild#815]
There are a few issues I've encountered that will generate corrupt / unloadable .xcodeproj files:

Code/Tools/FBuild/FBuildCore/Helpers/XCodeProjectGenerator.cpp (Line 349)
`Write( "\t\t1111111111111111%08u /* %s */ = {isa = PBXFileReference;%s lastKnownFileType = %s; name = %s; path = %s; sourceTree = \"<group>\"; };\n",
                    file->m_SortedIndex, shortName, fileEncoding, lastKnownFileType, shortName, file->m_FullPath.Get() );`

Requires both path and name to be in quotes as they can have spaces and/or special characters which breaks the current parsing.

`Write( "\t\t1111111111111111%08u /* %s */ = {isa = PBXFileReference;%s lastKnownFileType = %s; name = \"%s\"; path = \"%s\"; sourceTree = \"<group>\"; };\n",`

The other fix is for XCodeProjectGenerator::ShouldQuoteString (Line 769) where any string that also contains `$` or `/` or `\` should be escaped.

**Comment by ffulin** [comment]
The behavior you describe certainly seems like a bug - quoting and escaping is not considered correctly for those elements, but needs to be conditionally added.

The reason to apply the quotes conditionally is to ensure that we match the bahavior of XCode (it not, XCode will continually save the file, which means subsequent project generation will see it as dirty and have to regenerate it).

The XCodeProjectGenerator has some helper functions (```EscapeArgument``` and ```ShouldQuoteString```) which can be used here along the lines of other properties that are handling things better. Looking at those functions though, I think some changes to their interface could make things a little easier to manage.

**Comment by ffulin** [comment]
I've fixed the quoting and escaping of file paths (https://github.com/fastbuild/fastbuild/commit/4c95991b3678930f107c4530505c2b42cf94e9e0). This fix will be in the next release (v1.06). I'll leave this issue open until that version is released.

It turns out that the rules for quoting and escaping these particular strings are different to other escaping/quoting rules for other string in the same file, so the fix is only applied to filenames specifically. There may be other issues with other parts of the generation

There may still be other issues with generating this file. Please let me know if you see any other problems.

**Comment by PixelZealot** [comment]
Fantastic, thank you!

**Comment by ffulin** [comment]
v1.06 has now been released.
