### ISSUE TITLE
Backward compatible protocol for FastbuildWorker

### ISSUE THREAD

**Issue by aganea** [fastbuild/fastbuild#820]
Hello @ffulin !

We were wondering if, in the future, there could be a way to render the FastbuildWorker backward-compatible, in terms of protocol. In essence, it would be nice to deploy workers on all machines in a studio, but be able to accept requests from *any* version of fbuild.exe.

The setup we have right now is that every game production deploys a certain version X of Fastbuild & Worker. They may, or may not, upgrade it along the way during a production that last 3-4 years let's say. We have a common NAS folder, so we end up with a bunch of folders, one for each protocol version:
![image](https://user-images.githubusercontent.com/37383324/109533194-f4baf980-7a87-11eb-863e-05e9a70fb801.png)

Now this is a bit silly, since I have 400 machines spread out in these folders, but the production on version 19.0 can't reuse the workers on production on version 21.0 for example.

What if the protocol versionning was handled internally in the FastbuildWorker? There are several options: 1. Either say that from now on, we support all previous protocol messages, forever. 2. Have several sub- fbuild-worker.exe instances running on a single machine, and a top fbuild-orchestrator.exe re-direct the requests?

If we were to do it, what option would you suggest?

Additionally, a nice thing along these lines would be an update-by-wire. ie. sending a new fbuild-worker.exe to all machines, as a new version is released (the update could be triggered manually by the user).

**Comment by ffulin** [comment]
Hello :)

I've thought about the problem of how to make the compatibility more flexible over the years. Backwards compatibility is easy, but it's the forwards compatibility that is problematic.

While the worker protocol is independent of the FASTBuild version, and is only incremented when there is a change that requires incompatibility, in practice, changes that are breaking have been frequent despite efforts to avoid them.

The core issue I think is that the protocol version is used as the top level filter to ensure that clients only connect to workers who have the required functionality. If this information was only obtained after connecting, it could result in many useless network connections, and perhaps even the worst-case outcome of being connected entirely to unusable workers.

I think I might have an idea that could greatly improve this going forward.

If the next version of the protocol was split into a version and sub-version, and the version was the top level as it is now, but the sub-version was encoded in the worker token filename (for example `23.windows/v1-<ipaddr>`) then clients would still have the necessary information to filter workers before connecting them, based on the requirements of the given build dynamically.

For example, in the latest version (v1.04) some changes were made to return some new information from the worker to allow the new -profile command line option to work, resulting in the most recent version bump. If instead of bumping the protocol to 24, the version was bumped to v23.2, then new clients could pre-filter the lists based on whether that option was used or not. i.e. connecting to any v23.x version if the -profile option is not used, but only v23.2+ if the option is used.

It might be possible in some cases to drive version requirements based on features used in the bff. For example if only a new version manages some compiler command line correctly, we could use only that version dynamically based on whether that command line was used or not.

I think if done correctly, such a change would allow productions that are not prepared to update FBuild.exe update FBuildWorker.exe more frequently, as well as allowing those productions to used newer workers updated by other productions.

Somewhat ironically, this change would require a protocol version change, but perhaps in the best case it might be the last one.

What do you think?

----

PS - I noticed from your screenshot, that you are using a different versioning scheme from the official FASTBuild. This potentially means you have some incompatibilities on top of the base protocol changes (as seems to be implied by the forks of each version?). It would presumably be necessary to think about how to manage those changes as well, assuming they are still needed. Perhaps you'd need to extend the version string with some additional user-versioning data?

**Comment by aganea** [comment]
Thanks for getting back!

As for the screenshot, we've changed the sub-version scheme, and use a 32-bit hash instead generated from a GUID. We had quite a few contributors to our downstream FASTBuild over the past months, and it became harder to merge all patches (we have over 80 commits over 1.04!!). With this we don't have to think about it, just generate a GUID in your MR, when a change to the protocol is required, and that's it.

As for the discussion, I think the bottom line is that the local FBuild.exe has to know about the APIs calls that are supported by remote workers before connecting to the. I'm not sure but I think Goma does that with a central server that "knows" what the Remote Execution API servers support. Since we don't have that authority, but we have a filename on the NAS with some config information, could we write the supported APIs in that file as well? (the APIs that the worker supports) As for the protocol, in this model, ideally _I'd like the protocol to never change anymore_, it's the APIs that should change! If the protocol changes once a year or two, we're back at starting point, it would be the same issue as before.

But then, you're absolutely right, how do we handle "new" versions? My assumption is that the workers will always be "at head", at the latest avilable version. Perhaps we could simply update all workers remotely, in advance, before upgrading fbuild.exe on production floor. That requires de-coupling the upgrade to FBuild.exe and FBuildWorker.exe, but I think that's fine, we use nuget facades right now anyway. We're moving to having a common NAS folder for all studios, we could very well put the latest FBuildWorker.exe there and let the facade handle the update (or use the FBuildWorker update mechanism). I think that's less of an issue.

**Comment by ffulin** [comment]
**> ideally I'd like the protocol to never change anymore, it's the APIs that should change!**

A future feature might require entirely new interactions (packets) between the client and server. I see that as a protocol change rather than an API change. However, I think as long as there is a mechanism for clients to understand what packets/features/APIs are supported by workers, the distinction is unimportant and the problem will be managed as we both hope.

I think we do also need to consider by which mechanism old functionality can be retired. Anything that only brings a reasonable level of maintenance can be kept indefinitely, but I can certainly see a case where some legacy feature needs to be removed long after it has been superseded if it is problematic to maintain.

**> do you think we could write the supported APIs in that file as well?** 

Right now worker discovery is performed using a single directory listing. This operation is usually over the network and often over a high latency connection (in my case, the NAS is 500 km away :) ).

If before connecting to each worker we have to open and read a file on this remote drive, the latency of worker discovery/connection will be significantly increased. It might be possible to add some caching of this information, but I think it's much better to have the main worker token (the filename) encode the "range" or "set" of supported APIs. For mainline FASTBuild, the sequence of features is completely linear so this is very practical.

For your case (multiple concurrent branches with potentially different features) things are more complex, but I think this could also be encoded in the token filename, as long as there is a reasonable amount of them active at any time (i.e. dozens and not hundreds) and they are periodically collapsed into the "baseline" feature set.

I think a helper class/macro could be implemented in the code that could be used to define network features. The implementation of this could automatically handle registration of the feature so it appears in the worker token, define the relationship with the "baseline" version and handle tracking required features for a given invocation on the client all in one. I have some ideas about how to implement this, but I think it'd need a spike to ensure a good design.

(We could of course write feature availability inside the file for human use no matter what.)

**> My assumption is that the workers will always be "at head", at the latest available version.**

I agree. I think if implemented correctly, there will be no friction to updating workers in terms of compatibility, and several distribution mechanisms are available as you noted. (I still favor submitting the worker exe to source control)

**Comment by aganea** [comment]
It all makes sense, thanks for getting back! :)

**Comment by ffulin** [comment]
I've changed the way command line processing is handled so that most fixes that previously required protocol/worker version changes can now be handled entirely on the client side.

Previously, most args processing was executed on the remote side, so a fix required a new worker version (and protocol bump to ensure safety in the absence of a system like we talked about).

Now, args can be processed on the local side instead. For example: https://github.com/fastbuild/fastbuild/commit/58b9bde1b07e233788b329f41f3e5fd7863b36fb

(To retain backwards compatibility with old clients, some processing is still done in both places)

**Comment by ffulin** [comment]
There have now been several FASTBuild releases that retain protocol compatibility by leveraging that changes noted on this thread. This doesn't completely eliminate the possibility of a needing a breaking change in the future, but it seems the vast majority can be avoided as hoped.

With that in mind, I think this issue can be closed.
