### ISSUE TITLE
(Raw Literal Strings) Unexpected EOF when compiling UE4 4.27 Preview 2

### ISSUE THREAD

**Issue by shukenmg** [fastbuild/fastbuild#856]
I'm getting an Unexpected EOF error when compiling UE4 from source, without using UnityBuild.

The error occurs at EditorAnalyticsSession.cpp L231
`FRegexPattern Pattern(TEXT(R"((^[a-fA-F0-9-]+)_([0-9]+)_([0-9]+)_([0-9]+)_([0-9]+)_([0-9]+)_([0-9]+))"));`

The Raw literal string might be causing the error, because when I change the TEXT to use a regular string, like so:
`FRegexPattern Pattern(TEXT("(^[a-fA-F0-9-]+)_([0-9]+)_([0-9]+)_([0-9]+)_([0-9]+)_([0-9]+)_([0-9]+)"));` the error goes away.

**Comment by ffulin** [comment]
This seems like a compiler bug. The MSVC compiler (which I assume you are using) has had several bugs over recent years with string literal expansion, causing either compiler errors or bad debug info (mismatched line numbers). 

I took a quick look at the microsoft connect for your specific issue, and it seems like it might be this one:
https://developercommunity2.visualstudio.com/t/Visual-C-preprocessor-doesnt-recogniz/407341

Perhaps you can compare the version of your compiler versus the one in the bug and see if that's the issue? If so, it looks like a compiler upgrade will fix the bug.

If the issue is different, new or present in a later version of the compiler, your best bet would be to report it to Microsoft. If you can narrow it down to a small reliable repro case, I've found them to be very receptive to fixing these sorts of bugs.

If a compiler upgrade is not possible for you right now, then possible work arounds include:
a) modifying the source (as you did in your example)
OR
b) disabling caching and distributed compilation for the specific problem file or library (if the bug is relater to the preprocessor, that will avoid FASTBuild using it for that file or library)

**Comment by shukenmg** [comment]
Perfect!

Thank you for all your suggestions, I think me using an older version of MSVC must be the culprit (as I'm using an older version)
I'll update the compiler and test soon, but for now I'll close this issue.

Thank you very much for you detailed help.

**Comment by ffulin** [comment]
I'd certainly be interested to know what your resolution is in the end, and that might be useful to others too. If you gain any more insight, please post here if you are able.

**Comment by shukenmg** [comment]
Oh definitely, it's just that I won't be able to test this for a while, would it be better to keep this issue open?

**Comment by ffulin** [comment]
I think closing it is fine, given that it's very likely not something that can be addressed and also if you may not be able to come back to it for a while. We can always re-open if it turns out there is something that can be done on the FASTBuild side (a work around for example).

**Comment by shukenmg** [comment]
Ok, sounds good, I'll update the issue when I have some new info.
