### ISSUE TITLE
Linker command line is too long

### ISSUE THREAD

**Issue by kylawl** [fastbuild/fastbuild#87]
We have a custom compiler/linker that links in clang which we use to generate reflection info for our engine and games.

The compiler emits a reflection "obj" file for each source file as well as some ancillary generated source.
The "linker" concats all the "obj" files into a big reflection db.

The kicker here is that FBuild doesn't appear to have a path for generating response files for clang and even if it did, we'd still have a bit of trouble with FBuild auto-detecting what to do based on tool file names.

Would it be reasonable to add an optional var to Library/Linker nodes which allows you to force response files?

```
Library('my-lib')
{
.UseResponseFiles = true/false/default
}
```

**Comment by ffulin** [comment]
I assume you are getting this error?
```c++
FBuild: Error: Command Line Limit Exceeded (len: %u, limit: %u) '%s'\n
```

Some background on this functionality:

The logic currently is that response files will be used when:
a) The tool is known to support it (detected by exe name as you noted)
b) The command line exceeds the OS limit (not used always to avoid creating the response file when not needed as this saves a few ms off invocation)

In previous tests, I only managed to get the response file working with the PS4 version of Clang, so it's only enabled for that. If clang does actually support response files, that can be fixed. As you point out, since you are building your own exe, even if this helps others, it doesn't necessarily help you  (if you have a different exe name).

I think we could do something like you suggest, though I'd probably alter the proposal slightly:
a) Namespace it a bit more
b) Make it a forcing function
```C++
Library( 'lib' )
{
    .LibrarianForceUseResponseFiles = true
   ...
```
So that the code behaviour can be like this:
```C++
bool LibraryNode::CanUseResponseFile() const
{
        if ( m_ForceUseResponseFile )
        {
              return true;
        }
	#if defined( __WINDOWS__ )
		// Generally only windows applications support response files (to overcome Windows command line limits)
		return ( GetFlag( LIB_FLAG_LIB ) || GetFlag( LIB_FLAG_AR ) || GetFlag( LIB_FLAG_ORBIS_AR ) || GetFlag( LIB_FLAG_GREENHILLS_AX ) );
	#else
		return false;
	#endif
}
```
The idea being that variables in the bff syntax don't have a "not-set" value that we could use, so we couldn't differentiate false from the default as opposed to being set to false.

An alternate way to manage this is to externalize the definition of the Librarian/Linker tool in the same way we do for Compiler.  This way you could do this:
```C++
Librarian( 'customtool' )
{
    .LibrarianExecutable             = 'codegentool.exe'
    .LibrarianUseResponseFiles = true
```
In retrospect, this probably should have been the design from the start :)

**Comment by kylawl** [comment]
I think I agree that externalizing the librarian/linker to behave in a similar way to the compiler is probably the way to go. your example

I wonder if it would be valuable to be able to override the auto-detection of compiler/linker CLI to use. It would allow for custom tools like ours to specify what kind of tool FBuild thinks we are? Anything could function as front end or replacement to an actual tool at that point (I'll be it'll still need to behave somewhat like a c++ compiler/linker).

```cpp
Librarian( 'customtool' )
{
    .LibrarianExecutable              = 'codegentool.exe'
    .LibrarianToolCLI                   = 'Clang' | 'MSVC' | 'GreenHills' | 'OrbisClang'
    .LibrarianUseResponseFiles  = true
}
```

I wonder if long-term we can generalize the bits that make it necessary to auto-detect the tool by name at all?

**Comment by ffulin** [comment]
Interestingly the "LinkerType" option, was recently added to the Linker (including a default "auto" value which uses the exe name detection). That's pretty much what you've described.

In that case we chose not to externalize it in a new Linker() function in order to be compatible with CMake (it annoyingly invokes several different things via cmake.exe) In retrospect though, I think that was a mistake - we could have handled the cmake case by allowing the same exe to be used in multiple Linker definitions instead.

**Comment by ffulin** [comment]
For reference: https://github.com/fastbuild/fastbuild/pull/60/files

**Comment by kylawl** [comment]
Interesting, well that is exactly what I'm talking about. I can look at pulling that feature into Library then, as well as adding this LibrarianForceUseResponseFiles. Unless you wan to continue down this Linker() path?

**Comment by ffulin** [comment]
Thinking about this a bit more, I'd like to work towards doing this properly by making a new Librarian() and Linker(), but this is going to take some time (particularly so as not to break backwards compatibility ).

With that in mind, do you think for now you could use "Linker" instead of "Library" in your use-case and set the .LinkerType = "orbis-ld" (or indeed "msvc" or "gcc" aught to work too)? That should activate the use of response files without any need to make code changes. Little to nothing else is currently implied by that setting other than response file use (only "orbis-ld" implies some additional slash escaping in the response file).

**Comment by kylawl** [comment]
Yep I can work with that, although I thought that there was more command line parsing going on behind the scenes but if that'll work then we're good.

Thanks

**Comment by kylawl** [comment]
Sorry, did you mean DLL instead of Library?

**Comment by ffulin** [comment]
Sorry for the confusion.  I meant try to use Executable() instead of Library() for the work around, setting the LinkerType on that.

(The confusion on my side is that in the code LinkerNode.cpp is exposed as Executable() and DLL().  You don't want to use DLL as it has some sanity checks of the command line - i.e. whether you are missing /DLL etc)

**Comment by AntoineConffx** [comment]
Hey, sorry for bringing this up again, but I am having the same error message using a custom nintendo clang compiler. Is there any possible workaround ?
I tried setting the LinkerType to orbis-ld but that didn't do much.

**Comment by ffulin** [comment]
"orbis-ld" is not a valid LinkerType, you probably want to try "clang-orbis" (valid types are documented here: http://fastbuild.org/docs/functions/executable.html)  On a related note, it looks as though there is a bug where setting an invalid type will not report an error.

If the above works, then we can probably trivially add detection for the nintendo flavor of linker in this function LinkerNode::DetermineLinkerTypeFlags here https://github.com/fastbuild/fastbuild/blob/dev/Code/Tools/FBuild/FBuildCore/Graph/LinkerNode.cpp.

**Comment by AntoineConffx** [comment]
Awesome, thanks for the quick reply. This fixed it.
I have another question if it's okay to post it here,
Is it possible to use the compiler stage as both compiling and linking ? The compiler I use sets up the linker internally and I can't seem to remove the linker executable in the Executable section.

Thanks again :)

**Comment by ffulin** [comment]
@AntoineConffx I think it would be best to open new issue for any problems you have so that we can avoid noise in this thread.

**Comment by kylawl** [comment]
So I just encountered this again after all this time... I went searching to see what could be done, only to discover that I committed to resolving this 4 years ago! Clearly I forgot, UG!

**Comment by ffulin** [comment]
v1.02 has now been released which includes new functionality to resolve this issue as mentioned above. Should there be any remaining issues, please let me know.
