### ISSUE TITLE
Unable to pass a quoted string to a preprocessor define in a cross-platform manner

### ISSUE THREAD

**Issue by jorgenpt** [fastbuild/fastbuild#873]
Quote handling in `CompilerOptions` is OS dependent, and so I have been unable to find a single syntax that allows me to pass a quoted string in a C++ preprocessor define on both Linux and Windows without resorting to `#if __WINDOWS__`.

I've attached [a minimal sample project](https://github.com/fastbuild/fastbuild/files/7610965/QuotedPreprocessorRepro.zip) (that uses clang from Visual Studio on Windows), but the core of it is that `.CompilerOptions    + ' -DTEST=\"FOO\"'` works for passing to clang on Windows, but not for Clang on Linux, and `.CompilerOptions    + ' -DTEST="FOO"'` is the opposite. Here's the output building a simple `const char* str = TEST;` file with these two approaches on Linux & Windows:

Windows:

```ShellSession
❯ FBuild.exe QuotedDefineWorksOnWindows
5> Obj: C:\Scratch\QuotedPreprocessorRepro\BuildWorksOnWindows\Repro.obj
FBuild: OK: QuotedDefineWorksOnWindows
Time: 0.052s

❯ FBuild.exe QuotedDefineWorksOnLinux     
4> Obj: C:\Scratch\QuotedPreprocessorRepro\BuildWorksOnLinux\Repro.obj
4> WARNING: C:\Scratch\QuotedPreprocessorRepro\BuildWorksOnLinux\Repro.obj
C:\Scratch\QuotedPreprocessorRepro\Repro.c:1:19: error: use of undeclared identifier 'FOO'
const char* str = TEST;
                  ^
<command line>:1:14: note: expanded from here
#define TEST FOO
             ^
1 error generated.
4> Failed to build Object. Error: 1 (0x01) Target: 'C:\Scratch\QuotedPreprocessorRepro\BuildWorksOnLinux\Repro.obj'
FBuild: Error: BUILD FAILED: QuotedDefineWorksOnLinux
Time: 0.117s
```

Linux:

```ShellSession
$ fbuild QuotedDefineWorksOnWindows
4> Obj: /mnt/c/Scratch/QuotedPreprocessorRepro/BuildWorksOnWindows/Repro.o
4> WARNING: /mnt/c/Scratch/QuotedPreprocessorRepro/BuildWorksOnWindows/Repro.o
In file included from <built-in>:341:
<command line>:1:15: warning: missing terminating '"' character [-Winvalid-pp-token]
#define TEST \"FOO\"
              ^
/mnt/c/Scratch/QuotedPreprocessorRepro/Repro.c:1:19: error: expected expression
const char* str = TEST;
                  ^
<command line>:1:14: note: expanded from here
#define TEST \"FOO\"
             ^
1 warning and 1 error generated.
4> Failed to build Object. Error: 1 (0x01) Target: '/mnt/c/Scratch/QuotedPreprocessorRepro/BuildWorksOnWindows/Repro.o'
FBuild: Error: BUILD FAILED: QuotedDefineWorksOnWindows        
Time: 0.252s

$ fbuild QuotedDefineWorksOnLinux
3> Obj: /mnt/c/Scratch/QuotedPreprocessorRepro/BuildWorksOnLinux/Repro.o
FBuild: OK: QuotedDefineWorksOnLinux                           
Time: 0.239s

**Comment by ffulin** [comment]
This is unfortunately a complex problem because the way args are handled at the OS level is entirely different between Windows and other operating systems. Specifically, the core function to spawn a process takes a single string on Windows while on Linux et-al it takes an array of strings. This means on Windows, args with spaces must be quoted, which in turn means args which want to contain quotes must have those quotes escaped.

Right now FASTBuild passes that args (mostly) untouched when it comes to quotes which results in this problem.

We could attempt to either:
a) have FASTBuild remove the \ on Linux et al
OR
b) have FASTBuild add the \ on Windows

but either of those approaches comes with problems caused by ambiguity.
In the case of a) there is a problem if you want to pass literal `\"` on Linux. 
On Windows there is a problem if you wanted to quote in the middle of your arg as follows `-D"BLAH BLAH"`

It's unclear to me if a good solution for this problem exists. For now, I do as you have done, which is to #if in the bff for these cases where defining string literals, which thankfully are rare.

**Comment by ffulin** [comment]
v1.13 has now been released and includes several fixes to command line args handling that means things are now consitent between platforms. Thanks again for reporting the bug.
