### ISSUE TITLE
test suite "TestWarnings" doesn't test that the output for warnings are actually shown

### ISSUE THREAD

**Issue by sylvain-audi** [fastbuild/fastbuild#878]
Hello!

This test suite deactivates the compiler "warning-as-error" feature, and compiles a cpp that contains warnings.
However, the only verification made is that it compiles without error, which always succeeds even if no warning message is shown.

As an example, the test "WarningsAreShown" passes even if we remove the code from FBuildTest/Data/TestWarnings/warnings.cpp

Should we simply check that the output contains any flavor of "warning :"  strings?

**Comment by ffulin** [comment]
**> This test suite deactivates the compiler "warning-as-error" feature, and compiles a cpp that contains warnings.**
This test doesn't de-activate "warnings as errors". It attempts to ensure that even when this feature is not used, warnings are still emitted.

By default, FASTBuild doesn't print any captured output unless a build fails (to de-spam the logs). If warnings as errors are enabled, this special case check can be skipped. If it's not enabled, we need to check the output to see if there are warnings that should be emitted.

**>  always succeeds even if no warning message is shown.**

It does look as though one or more of these tests can be improved. As you say, while they do pass, they don't seem to guarantee that the expected warnings are actually output. We could check the output generated by the test as you suggested, along the lines of:
```C++
TEST_ASSERT( GetRecordedOutput().Find( "some warnings text" ) );
```
The string may need to differ slightly per-compiler, but this looks like an otherwise easy improvement that could be made.

Thank you for reporting this issue.

**Comment by ffulin** [comment]
TestWarnings have been improved to explicitly check the expected warnings/messages are output: https://github.com/fastbuild/fastbuild/actions/runs/7825021549

Issues with how FASTBuild handles warnings in general still remain (as noted here https://github.com/fastbuild/fastbuild/issues/116) but this issue can now be closed.
