### ISSUE TITLE
FBuild did not connect to any workers in Linux after a while.

### ISSUE THREAD

**Issue by Domain** [fastbuild/fastbuild#887]
I am not sure how long it will happen. But after hours, I found that fbuild did not connect to any workers while distributed compiling. All workers are idle, and fbuild report that it found all of them. But none of them receive any jobs. And no any error messages. I have to restart every fbuildworker in worker machine to make it work again.

**Comment by ffulin** [comment]
I have seen some evidence recently that there is a potential deadlock condition when a worker is under heavy network load and is both sending and receiving data simultaneously. It's of course difficult to say, but it may be that you are experiencing this issue.

The next version of FASTBuild which will be released (v1.06) contains some improvements to the -profile feature which might allow us to better understand under which conditions problems like this occur. I hope to dedicate some time to investigating this issue after that release.

**Comment by Domain** [comment]
I have updated to the new version. I compile with -distverbose option. At the beginning, workers work well. I can see the workers are receiving files to compile. But and after a while, I can see many Send Failed (most are Type: 5 Size: 16 Payload: > 500000, with a little Type 2, Size 8). It will disconnect from the worker and reconnect quickly. All workers are idle.

**Comment by Domain** [comment]
[fbuild_profile.zip](https://github.com/fastbuild/fastbuild/files/8619022/fbuild_profile.zip)
Here is the profile file.

**Comment by ffulin** [comment]
There have been a few releases since this issue was reported, including a few fixes/improvements that could be a factor (at least one protocol bug fix and various lock contention reductions in the worker).

Does this issue still occur with more recent versions (v1.10 being the latest at time of writing)?

**Comment by Domain** [comment]
No, even worse. I can see only very little files are distributed to workers. We have nearly 10000 source files, but only less than 100 files are distributed to other workers.

**Comment by Domain** [comment]
> v1.06 added some additional information to -distverbose and -profile that may provide some additional insight. I see you were using those previously, but do you see anything interesting with those in the newer version?

I tried with  -distverbose and -profile, and saw all workers were connected. And I saw a few "Got Result" messages at the beginning. But no more messages after that. No error, just normal local build log. Nothing changed even with -forceremote.

**Comment by ffulin** [comment]
Are you able to provide a -profile json and -distverbose log from v1.10 of it not working? That might give us a starting point to understand what's going on.

**Comment by Domain** [comment]
[build.zip](https://github.com/fastbuild/fastbuild/files/11903090/build.zip)
Here are logs.

**Comment by Domain** [comment]
![fbuild](https://github.com/fastbuild/fastbuild/assets/903197/8a181bfa-8842-4092-901d-deb062cabb7f)
Only a few files are distributed at the beginning.

**Comment by Domain** [comment]
Any idea what's going on here? I am stuck on this issue for a long time.

**Comment by ffulin** [comment]
Thanks for the new logs and profile capture. I took a look, and it doesn't seem that there are any obvious network connectivity problems. If all jobs are distributed when you use -forceremote, then it's unclear why distribution would stop working after the first batch of jobs.

I'm guessing there must be a bug, either in the Client (causing it to hand out no more jobs) or the Workers (causing them to request no more jobs). I'd love to figure out what's going on.

It seems like some additional logging with -distverbose and additional profiling info in -profile might be able to help diagnose what's going on, but since we don't know what's wrong it'd be a case or speculatively adding things in the hope it uncovers something.

A couple of alternative ways we can try to proceed:
* **Try with one worker**. It'd be interesting to know if limiting yourself to one worker changes the behavior. This could tell us (or eliminate) causes related to multithreading around the client and server management.
* **Try a debug build** - If you're in a position to build FASTBuild from source, building a Debug build would activate various assertions that might catch problems that would cause workers to get into a bad state.

**Comment by Domain** [comment]
OK, I figure out the problem finally. This relate to #884. My hostname is a number, so the fbuildworker will get a wrong IP address. I modify the code to resolve this issue, but then fbuild will get a wrong remote IP to connect! Finally, I have to revert my changed and set the hostname to my ip address. All work fine now.
