### ISSUE TITLE
Allow port used for distributed compilation to be specified

### ISSUE THREAD

**Issue by eclazi** [fastbuild/fastbuild#910]
Specify port via command line argument to fbuild.exe and fbuildworker.exe. Idea is to allow multiple versions of  fbuildworker.exe to run with different ports to allow a single build agent to work with multiple versions of fbuild clients.

**Comment by ffulin** [comment]
Setting the port is a reasonable feature request and we'd likely wan to couple it with an environment variable such as FASTBUILD_WORKER_PORT (similar to [FASTBUILD_BROKERAGE_PATH](https://fastbuild.org/docs/environmentvariables.html#FASTBUILD_BROKERAGE_PATH) and perhaps an option in the Settings (so it can be configured on the Client side in the bff as well))

In terms of using this for running multiple workers/compatibility as you mention, there are a few additional considerations.

**Since v1.05, workers are forwards/backwards compatible**

In v1.05 changes were made to the distributed compilation protocol to allow clients and workers to be forwards/backwards compatible, specifically:
a) almost all command line manipulation was moved the client side, so worker changes are often no longer required
b) clients know know what the version of a worker is in cases where remote changes must be made, and can avoid giving them jobs that require a newer version of the worker
For example v1.06 added both bug fixes and optimizations that work seamlessly with any mix of v1.05 and v1.06 clients and workers (the bug fix was client side and the optimization will be gracefully disabled if the worker cannot support it)

It should be incredibly rare going forward that a worker would not be fully backwards compatible.

Of course if you have custom local changes that are incompatible and you can't or don't want to manage that, you may still want or need to split the worker pool.

**There is a process single prcoess mutex**

There is a global system mutex that prevents two FBuildWorkers running at the same time. If you want to run two workers on the same agent, this would need to be modified to include the port in the mutex id.

**Resource Contention**

If using workers in "When Idle" mode, it'd be possible for two workers to consider the machine idle and accept jobs in a way that will cause resource contention. Everything will work, but may be sub-optimal depending on timing of job acceptance.

**Comment by eclazi** [comment]
Thats great. Thanks!
