### ISSUE TITLE
Viewing compiler warnings

### ISSUE THREAD

**Issue by kylawl** [fastbuild/fastbuild#92]
I can't seem to figure out how to get fast build to not eat compiler warnings. You get to see them if there is an error but not after a successful compile.

Am I missing something?

**Comment by ffulin** [comment]
Hello. This issue has been fixed in the dev branch and integrated into the next version, so warnings will appear as expected with the next release (v0.90).  I'll leave this issue open until that version is released.

Until then, the only semi-work around is to use /WX (treat warnings as errors) to make all warnings cause the build to fail.

**Comment by kylawl** [comment]
Ah, that's great.

Thanks

**Comment by ffulin** [comment]
v0.90 has now been released which includes a fix for this issue.  Thanks again for reporting the problem!
