### ISSUE TITLE
.CompilerInputFiles with the same file name,but not the sub folder name,with occur this error

### ISSUE THREAD

**Issue by leinlin** [fastbuild/fastbuild#920]
Conflicting objects found for: E:\SelfWork\protobuf-net-gc-optimization\Build\build\obj\il2cppOutputProject\x86\Debug\gc.obj
 Source A  : E:\SelfWork\protobuf-net-gc-optimization\Build\Il2CppOutputProject\IL2CPP\external\mono\mono\metadata\gc.c
 ObjectList: action_0
AND
 Source B  : E:\SelfWork\protobuf-net-gc-optimization\Build\Il2CppOutputProject\IL2CPP\external\bdwgc\extra\gc.c
 ObjectList: action_0
FBuild: Error: BUILD FAILED: all
Time: 0.006s

**Comment by ffulin** [comment]
Your issue seems to duplicate: https://github.com/fastbuild/fastbuild/issues/898

.CompilerInputFilesRoot can be used to set a base path so that libraries with non-unique filenames will be placed in relative sub-directories instead of all being emitted to the same location.

You set it to the base path of your source files. In your example it might be something like:
```.CompilerInputFilesRoot = E:\SelfWork\protobuf-net-gc-optimization\Build\Il2CppOutputProject\IL2CPP```

If you are using a 3rd party tool to generate your bff files, a modification to that system will be needed to generate bff files with this parameter.

**Comment by ffulin** [comment]
Closing duplicate. Let me know if you think this is a different issue and we can reopen if needed.
