### ISSUE TITLE
Possible mistake in IsWarningsAsErrorsMSVC() method

### ISSUE THREAD

**Issue by poljak181** [fastbuild/fastbuild#941]
Hi!
Please, check the file:
`Code/Tools/FBuild/FBuildCore/Graph/ObjectNode.h `
Seems, that there is mistake in method:
`bool IsWarningsAsErrorsMSVC() const         { return ( ( m_Flags & FLAG_QT_RCC ) != 0 ); }`
I guess, this code should be like this:
`bool IsWarningsAsErrorsMSVC() const         { return ( ( m_Flags & FLAG_WARNINGS_AS_ERRORS_MSVC ) != 0 ); }`

**Comment by ffulin** [comment]
That does look wrong - thanks for reporting it.

Looking at the code that uses it briefly, it seems this function is only used to avoid explicitly checking if the output contains warnings which need reporting, which can be skipped if "warnings as errors" is enabled (since compilation will fail).  i.e. it looks like things are functioning correctly, albeit inefficiently.

**Comment by ffulin** [comment]
This function has been fixed and the (minor) optimization restored: https://github.com/fastbuild/fastbuild/commit/2b8b4c0c48140df74ac8521ac2b18690b087836a. This change will be in the next release (v1.09). I will leave this issue open until that version is released.

Thanks again for reporting the problem.

**Comment by ffulin** [comment]
v1.09 has been released and includes the fix for this issue. Thanks again for reporting it!
