### ISSUE TITLE
Typo in ObjectNode::DetermineFlags method while checking FLAG_WARNINGS_AS_ERRORS_CLANGGCC option

### ISSUE THREAD

**Issue by poljak181** [fastbuild/fastbuild#943]
Hi, ffulin!
I checked gcc/clang compiler option that called: "Turn warnings into errors."
It starts with a capital letter: -Werror
So this place
```
            else if ( token.BeginsWith( "-werror" ) )
            {
                flags.Set( CompilerFlags::FLAG_WARNINGS_AS_ERRORS_CLANGGCC );
            }
```
should be (as I think) replaced by
```
            else if ( token.BeginsWith( "-Werror" ) )        // <= capital letter here!
            {
                flags.Set( CompilerFlags::FLAG_WARNINGS_AS_ERRORS_CLANGGCC );
            }
```

**Comment by ffulin** [comment]
This does seem to be wrong. Thanks for reporting it.

**Comment by ffulin** [comment]
I looked into this issue and incorrect casing inhibits a small optimization in output processing.

I have submitted a fix (https://github.com/fastbuild/fastbuild/commit/8e70b076cbbae910c42d016c6309b5c5ff901232) which will be part of the next release (v1.09). (The fix is exactly as you suggested)

I'll leave this issue open until that version is released.

Thanks again for reporting this issue.

**Comment by ffulin** [comment]
v1.09 has been released and includes the fix for this issue. Thanks again for reporting it!
