### ISSUE TITLE
Is It Possible To Build Static And Dynamic Libraries Simultaneously?

### ISSUE THREAD

**Issue by sergegers** [fastbuild/fastbuild#945]
I need two variants of the same library dynamic and static (for tests). The most obvious way is make a shared object list and build libraries with Library() and Dll() functions. I'm calling the Library function with empty input files and object list as:
`Library
{
 .CompilerInputPath              = .CurrentPath

.CompilerInputExcludePath   = .CurrentPath

 .CompilerInputObjectLists   = .OL
}
`
 But I receive an error message: Conflicting objects found for .cpp file from Library target and .obj file from OjectList target

The way with object list for Dll() and direct setting file path for Library() gives me the similar error message about conflicting with cpp files.

What do I wrong or there is no way to do it at all?

**Comment by ffulin** [comment]
You can build static libraries and dlls at the same time.

(You didn't specify which platform or compiler you are using, so the info below assumes Windows/MSVC)

It's not clear what your constraints are, but there are broadly two options:
a) compiling an ObjectList (or Library) once and consuming it in n times
b) compiling the same code n times to n locations

**a) compiling an ObjectList (or Library) once and consuming it n times**

It seems like this was what you were attempting. 
You can create a shared ObjectList and consume it between both a DLL and a Library (or Executable) as many times as you like, in parallel.

From the example you provided above, it looks like the problem is that your setup is trying to compile the object files twice (once in the original ObjectList that's not shown, and another time in the Library you did show). Presumably both of them are outputing files to the same directory which causes the "conflicting" error you see.

You can change your library to consume the existing already-compiled objects instead of trying to compile it again as follows:
```
Library()
{
    .LibrarianAdditionalInputs = 'obj' // Where 'obj' is the alias for your already defined ObjectList
```
(leaving out all the normal CompilerInputBlah options but adding the ones that control output)

However, you don't actually need that Library() at all. You can just consume the ObjectList directly into your final Executable just as you've consumed it in your DLL.

Whether you go via an intermediate library or not, this approach will result in DLL exports in your executable. Since you mentioned your use-case is a test, this probably won't matter.

If it does, you can:

**b) compile the same code n times to n locations**

You can create multiple ObjectList or Library for the same code and compile it multiple times with different options (such as a define to control DLL symbol export being enabled or not). You only need to make sure that the outputs go to different directories. These can also be compiled in parallel.

---

One additional note:

For the first option, you **may** also need to set .CompilerInputAllowNoFiles to true to allow your Library to have no directly compiled inputs and to only purely consume another library. I just noticed that this is missing from the Library() documentation (only appears in the ObjectList() documentation) so I will fix that.

**Comment by sergegers** [comment]
I made the same way as you write but use .CompilerInputObjectLists of Library() function parameter instead of .LibrarianAdditionalInputs. Documentation here is extremely brief. Now it works. Thank you very much for you answer.

**Comment by ffulin** [comment]
**> .CompilerInputObjectLists of Library() function parameter instead of .LibrarianAdditionalInputs.**

Yes that makes sense for your case.

**> Documentation here is extremely brief.**

Agreed. Documentation improvement is something that will hopefully occur in the future.

**> Now it works**

Glad to hear it! With that in mind, i'll close out this issue.
