### ISSUE TITLE
FASTBuild saves dependency graph file in source tree

### ISSUE THREAD

**Issue by to01z** [fastbuild/fastbuild#960]
Hi again,

FASTBuild currently stores its dependency graph file (`.fdb`) at the same location as the root config file used for the invocation. This puts a "built/ intermediate" file in the source tree which most people end up adding to their `.gitignore`.

A better solution might be to allow the user to move the location of the dependency graph file to a place of their choice. This can be implemented as a `-dbfile <path>` option on the command line.

I have done a rudimentary implementation here: https://github.com/fastbuild/fastbuild/compare/dev...to01z:fastbuild:to01z/depgraph_filename

Let me know if you are interested in a PR.

 /to01z

**Comment by ffulin** [comment]
It is indeed not ideal that the database file is mixed with source. A feature to control the location or otherwise relocate it would be nice.

I took a look at your linked change and it seems pretty reasonable. This change comes with some implications I think we need to consider:

*a) compiling from the command line becomes more difficult.* A Visual Studio project (or other IDE) could be nicely configured to provide the correct argument, but when compiling from the command line it will be necessary to pass the db name/path. A typo (or forgetting to add the arg) would result in a clean build

*b) multiple databases* Right now there is only 1 possible place for the db. Having multiple places for the db would allow multiple copies of the db in different states. In theory, the logic that detects when things need to build handles "external" modification of source or intermediate artifacts which is how a change in dbs between builds would manifest. It's possible though that this might uncover edge-case bugs.

I don't think either of these things is a blocker for the option, so I'd be ok with accepting a PR for this as you have it, but I wonder if there might be a better way to manage this.

One idea I had is to encode the db location in the bff file itself. The problem with that is it creates a chicken and egg problem with the parsing of the bff files. We can't know if they need parsing without parsing them, So this, at least if naively implemented wouldn't quite work. A way to solve this might be to require a special token/sequence as the very first item in the root bff so it could be extracted without needing to do full parsing. I'm not 100% sure how I feel about this option - the implementation is potentially a bit messy, but fairly easy. The end result for the user would be quite nice though.

Any additional thoughts on this?

**Comment by to01z** [comment]
Thanks for sharing your analysis and ideas.

Here is a few thoughts on your sticking points:

*a) compiling from command line becomes more difficult*
In my case this is a non-issue as I always build in VS or using a shell script that wraps the invocation of FASTBuild. In either case, it is easy to add the required arguments. Users could alternatively use command aliases to inject required arguments. I chose the script route to make sure the working dir gets set correctly because I use relative paths for input files in my build scripts.

Side note: At times I wish FASTBuild had a mode where relative input file paths could be interpreted relative to the script itself instead of relative to the working dir. That is probably a discussion for a different issue though...

*b) multiple databases*
I would argue that invocation of FASTBuild with the same root config script and output hierarchy/ files, but different databases should be considered a "user error". This is a tough one to enforce because FASTBuild doesn't have an intrinsic concept of "output root" (akin to CMake's `CMAKE_BINARY_DIR`) and as such would have to rely on something in the config file itself as you mention. Aside from the messy chicken and egg problem, I would also say that it would be an unfortunate coupling to have in the config file as it is useful (and common practise) to have multiple intermediate/ output roots per source tree. I would probably lean on documentation to discourage the user from venturing in that direction.

For my own case, I want multiple databases. I have platform-specific root config files and each invocation of FASTBuild only ever builds for that one platform (internally relying on many shared bff includes). In this setup, some source files are shared between multiple platforms, but always with a per-platform output hierarchy. This works with the current behaviour of the databases, but "pollute" my source tree.

If you are okay with the functionality, I will add some documentation for the option and file a PR.

**Comment by ffulin** [comment]
I've integrated you PR for inclusion in the next release (v1.11) - thanks :). I'll leave this issue open until that version is released.

**Comment by ffulin** [comment]
FASTBuild v1.11 has been release and includes your changes. Thank you for helping to improve FASTBuild!
