### ISSUE TITLE
Distributed compilation doesn't work after correcting "invalid" compiler setup

### ISSUE THREAD

**Issue by msg-programs** [fastbuild/fastbuild#972]
Hello! I've a fbuild.bff that looks a little something like this:
```
Settings {
    .CachePath = './build/cache'
}

.Compiler = '/usr/bin/gcc'

.CommonConfig = [
    .Includes   = ...
    .Defines    = ...
    .CompFlags  = ' -Wall -Wextra'
    .LinkFlags  = ...
    .ExtDeps    = ...
]

.DebugConfig = [
    Using(.CommonConfig)
    .CompFlags  + ' -O0 -g3'
    .ConfigName = 'debug'
]

.ReleaseConfig = [
    Using(.CommonConfig)
    .CompFlags  + ' -O3'
    .ConfigName = 'release'
]

.AllConfigs = {.DebugConfig, .ReleaseConfig}
.AllTargets = {}

ForEach (.Config in .AllConfigs) {
    Using(.Config)
    ObjectList('objs-$ConfigName$') {
        .CompilerOptions            = ' -c "%1" -o "%2"'
                                    + .Includes
                                    + .Defines
                                    + .CompFlags
        .CompilerOutputPath         = './build/tmp-$ConfigName$'
        .CompilerInputPath          = './'
        .CompilerInputPathRecurse   = true
        .CompilerInputPattern       = '*.c'
    }

    Executable('myprog-$ConfigName$') {
        .Linker         = '/usr/bin/gcc'
        .LinkerOptions  = '"%1" -o "%2"'
                        + .LinkFlags
                        + .ExtDeps
        .Libraries      = 'objs-$ConfigName$'
        .LinkerOutput   = 'build/myprog-$ConfigName$'
    }

    Alias('$ConfigName$') {
        .Targets = 'myprog-$ConfigName$'
    }

    ^AllTargets + 'myprog-$ConfigName$'
}

Alias('all') {
    .Targets = .AllTargets
}
```
Everything worked as intended, until I noticed that the way I set up the compiler isn't how other projects I've seen do it (Looking at it now, I'm wondering how it even worked in the first place). Hence, I changed the file as follows:
```
Settings {
    .CachePath = './build/cache'
}

- .Compiler = '/usr/bin/gcc'
+ Compiler('mycc') {
+     .Executable = '/usr/bin/gcc'
+ }

*snip*

ForEach (.Config in .AllConfigs) {
    Using(.Config)
    ObjectList('objs-$ConfigName$') {
+       .Compiler                   = 'mycc'
        *snip*
    }
*snip*
}
*snip*
```
This works for local compilation, but when I tried to use -dist, I get errors like this:
```
Obj: /home/dev/myprog/build/tmp-debug/somefile.o               
-> Obj: /home/dev/myprog/build/tmp-debug/somefile.o <REMOTE: xx.xx.xx.xx>
PROBLEM: /home/dev/myprog/build/tmp-debug/somefile.o           
WARNING: /tmp/_fbuild.tmp/0x00000000/core_1002/somefile.o
gcc: fatal error: cannot execute 'cc1': execvp: No such file or directory
compilation terminated.
Failed to build Object. Error: 1 (0x01) Target: '/tmp/_fbuild.tmp/0x00000000/core_1002/somefile.o'
FBuild: Error: BUILD FAILED: debug                             
Time: 0.293s
```
After adding cc1 to the `.ExtraFiles`, I got an error about libisl.so missing. As none of the examples add anything other than the gcc executable to `Compiler()`, I assume that this isn't the way to go.

Setup (local)
- Ubuntu 22.04.1, 64 bit, kernel version 5.19.0-38-generic
- FASTBuild v1.09, same issue with v1.08
- gcc 11.3.0

Workers are docker containers based on the `ubuntu:latest` image, no gcc/build essentials installed. I've also tried to run a worker locally, to the same effect.

What is causing the distributed build to fail here?

**Comment by ffulin** [comment]
The .Compiler property of ObjectList/Library can either:
a) specify the name of a previously defined Compiler()
OR
b) specify the path to the compiler executable

Your config originally had b). In that case, the Compiler() is automatically/implicitly created, but distributed compilation is disabled. This means compilation would never have been distributed for you in the past.

When you change it to reference an explicitly defined Compiler() instead (i.e. option a) then distributed compilation is allowed by default. However, for distributed compilation to work correctly, the compiler must either:
a) be an entirely self-contained single executable
OR
b) only dependent on installed/available libraries/dlls
OR
c) have the additional libraries/dlls specified in .ExtraFiles on the compile

gcc has additional dependencies so you can chose to either make sure every machine has the appropriate/compatible dependencies available (option b, perhaps by updating your docker image) or specify the additional dependencies with .ExtraFiles (option c)

Generally, option c is preferable as compilation is performed using the host's files so no mismatches should occur. It also makes maintenance of the worker machines simpler and more flexible. I also typically recommend vendorizing compilers within your source control where possible to additionally ensure all developers are using consistent versions.

**Comment by msg-programs** [comment]
Thank you for your quick response! I didn't know the part about how using the `.Compiler` variable disables distributed compilation. I haven't seen this mentioned in the docs of `Compiler()`, could it be added?

a) isn't that case with gcc as I've noticed. I've since re-added cc1 to the `.ExtraFiles`.
b), I've tried using a machine as the worker that had the same version of gcc installed. There seems to be some sort of incompatibility/interference as seven headers deep something in `immintrin.h` breaks. Since c) is the preferred solution, there's no need to look into this further in the scope of this issue.

c) worked for me after specifying `.ExecutableRootPath = '/usr/lib'`. cc1 searches for the libisl.so file in `/usr/lib/**`, but since FASTBuild copies it to its toolchain directory somewhere in `/tmp`, it can't find it. 

Again, thanks for the answer and for creating FASTBuild!

**Comment by ffulin** [comment]
*> I didn't know the part about how using the .Compiler variable disables distributed compilation. I haven't seen this mentioned in the docs of Compiler(), could it be added?*

This is rather a special behavior of ObjectList/Library so would probably be documented there. (The documentation for both of those in general needs a lot of work)

*> Since c) is the preferred solution, there's no need to look into this further in the scope of this issue.*

I'm glad to hear you got it working.

Since this issue is resolved, I'll close it for now, but let me know if you have any followup questions.

**Comment by msg-programs** [comment]
It did, in fact, not work yesterday.

I noticed that the worker's printout `Failed to store fileId xxx for manifest ###` isn't a warning about some metadata not being saved but an error that occurred while setting up the remote toolchain. The cause was a collision between file paths, as there cannot be a program and a directory named "gcc" in the same directory. The addition of `.ExecutableRootPath` didn't actually change anything, gcc still couldn't find its runtime dependencies without me moving files around. So I fell back to option b), installed gcc in the container and used the compiler definition that FASTBuild uses to build itself.

What worked in the end - and this time I'm sure because compilation times halved even for my small project - was looking at the `immintrin.h` error. I think it's a difference in how `-march=native` is evaluated on the worker vs. locally. The option implicitly sets a whole bunch of flags; setting some of them explicitly made the error go away. For me, adding `-march=x86-64 -msse3 -mpopcnt` to the compiler options worked.

I apologize for the inconvenience and thanks again for your help!

**Comment by ffulin** [comment]
It should be possible to get this working in a way that is isolated from the worker. It can be helpful to use a clean install without a compiler present (in a VM for example) for testing to ensure the config is free of dependencies on the host. It's ultimately for you to decide how thorough you want or need to be.

**> "Failed to store fileId xxx for manifest ###" isn't a warning...**

This is a critical error that will prevent all distributed compilation.
The Compiler() has some logic that detects setups with conflicting files. It's probably possible to extend that to detect this conflict and have it caught earlier on the client side during initial bff parsing.

**> I'm sure because compilation times halved even for my small project**

You can use -summary to see how many objects were compiled remotely versus locally. For testing, you can also use the debug option -forceremote to guarantee anything distributable is done remotely.

**> I think it's a difference in how -march=native is evaluated on the worker vs. locally**

I don't think there should be any difference here unless the machines have actual differing architectures (like an intel vs arm mac for example). It might be nice to understand what's going on here. but i'd probably suggest setting your desired architecture explicitly anyway if possible.
