### ISSUE TITLE
Do not mix spaces and tabs

### ISSUE THREAD

**Issue by trufae** [fastbuild/fastbuild#98]
For example like this one: https://github.com/fastbuild/fastbuild/blob/master/Code/Core/Core.bff

**Comment by ffulin** [comment]
Agreed :)  The general convention has been to use tabs in the source code.

**Comment by ffulin** [comment]
I have done a pass that makes all whitespace consistent, replacing all tabs with spaces (4 spaces to a tab).
Thee changes are now in "dev" and will be in the next release (v0.92). I'll keep this ticket open until v0.92 is released.

I chose to remove tab characters because some tools (like GitHub) don't have good support for defining tab width which makes things like diffing painful.

**Comment by ffulin** [comment]
v0.92 has now been released and contains the normalized whitespace. Thanks for reporting this.
