### ISSUE TITLE
Question: How to automatically include Visual Studio include paths?

### ISSUE THREAD

**Issue by petrocket** [fastbuild/fastbuild#991]
I'm working on updating a [CMake with FastBuild generator](https://github.com/petrocket/CMake/tree/fastbuild) to create `.bff` files for [O3DE](https://github.com/o3de/o3de) and it works fine if I configure and build from a command line after running `vcvarsall.bat` which sets the `INCLUDE` environment variable to include standard library paths, but when I try to build from within Visual Studio 2019 I get file not found include errors because the C++ standard library include paths are not included. 

How do I update the `.bff` to add the includes like `vcvarsall.bat` does?  

This is the generated `.bff` Compiler section:
```
Compiler('Compiler-CXX')
{
  .Root = 'C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64'
  .Executable = '$Root$/cl.exe'
  .CompilerFamily = 'msvc'
  .ExtraFiles = 
  {
    '$Root$/c1.dll',
    '$Root$/c1xx.dll',
    '$Root$/c2.dll',
    '$Root$/atlprov.dll',
    '$Root$/msobj140.dll',
    '$Root$/mspdb140.dll',
    '$Root$/mspdbcore.dll',
    '$Root$/mspdbsrv.exe',
    '$Root$/mspft140.dll',
    '$Root$/msvcp140.dll',
    '$Root$/msvcp140_atomic_wait.dll',
    '$Root$/tbbmalloc.dll',
    '$Root$/vcruntime140.dll',
    '$Root$/vcruntime140_1.dll',
    '$Root$/1033/clui.dll',
    '$Root$/1033/mspft140ui.dll'
  }
}
```
The generated `.bff` is missing the toolchain include paths and I can see in the [`VS2019.bff` SDK example](https://github.com/fastbuild/fastbuild/blob/main/External/SDK/VisualStudio/VS2019.bff) has `.VSIncludePaths` but I don't understand how they get used, and where I should add them to my `.bff` generator so it will work for the various versions of Visual Studio.

**Comment by petrocket** [comment]
Ah, looks like the generator I'm using just hard codes the Compiler but not the toolchain settings and it isn't the most recent https://github.com/petrocket/CMake/blob/fastbuild/Source/cmGlobalFastbuildGenerator.cxx#L574

**Comment by ffulin** [comment]
There are broadly 2 ways you can manage include paths with FASTBuild (or combinations/variations of these approaches).

**1. Invisibly to FASTBuild**
You can let the compiler use the INCLUDE or other environment variables.  In this setup FASTBuild won't be able to know that it should recompile things if that environment variable changes. Additionally, some features like the LightCache may not work correctly.

**2. Visible to FASTBuild**
you can suppress the local environment in the Settings() and explicitly set include paths in the bff for the ObjectList or Library functions. If any of these paths change, FASTBuild will know that the relevant object will need recompilation. The LightCache (subject to other requirements) will also work.

I personally recommend setting up as much of your build as is possible/practical to be isolated from the local machine in order to have repeatable builds between machines (i.e. trend towards option #2). I also recommend vendorizing your compilers and 3rd party libraries (checking them into source control) and suppressing all local environment variable and explicitly managing include paths in your bff files.

If using CMake you may be limited in what you can control or do of course. FASTBuild is generally intended to replace CMake rather than be invoked by/from it (but of course the flexibility of being able to try our FASTBuild more easily for an existing CMake build, or perhaps even maintain both options can be convenient).

**Comment by petrocket** [comment]
Thank you for the very thorough and informed reply @ffulin!  I will try your suggestion and attempt to explicitly set the build paths.  As for maintaining  .bff files for building all the O3DE engine and projects, that may to a bit much to maintain considering the size of the codebase (including 3rd party libraries), but I would love to give developers the option to generate .bff files from the cmake files so they can benefit from the Fastbuild distributed compilation - it can bring our full engine compile times down from over an hour to 10-15 minutes with the spare machines, and I see the potential for using cloud machines too.

It would be especially cool if we could also use it for distributed asset processing too!

**Comment by ffulin** [comment]
**> I would love to give developers the option to generate .bff files from the cmake files so they can benefit from the Fastbuild distributed compilation**
Having the option sounds great.

**> it can bring our full engine compile times down from over an hour to 10-15 minutes with the spare machines, and I see the potential for using cloud machines too.**
That's great!
